In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df_renewal = pd.read_csv('../../../data/interim/renewal_calls_cleaned.csv')
df_email = pd.read_csv('../../../data/interim/emails_cleaned.csv')
df_cc = pd.read_csv('../../../data/interim/cc_calls_cleaned.csv')
df_billings = pd.read_csv('../../../data/interim/billings_cleaned.csv')

In [4]:
df_cc.info()

<class 'pandas.DataFrame'>
RangeIndex: 31636 entries, 0 to 31635
Data columns (total 30 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   contact_id                                31636 non-null  float64
 1   call_date                                 31636 non-null  str
 2   direction                                 31636 non-null  str
 3   cc_care_package                           31636 non-null  str
 4   cc_care_package_discussed                 31636 non-null  str
 5   cc_urgency_getting_on_site                31636 non-null  str
 6   cc_external_consultant                    31636 non-null  str
 7   cc_agent_cross_sell_attempt               31636 non-null  str
 8   cc_customer_issues_concerns               31636 non-null  str
 9   cc_business_struggles_financial_hardship  31636 non-null  str
 10  cc_call_initiated_by                      31636 non-null  str
 11  cc_questionnaire_completion               31636 non-null  str
 12  cc_chasing_response                       31636 non-null  str
 13  cc_issues_within_questionnaire            31636 non-null  str
 14  cc_login_issues                           31636 non-null  str
 15  cc_platform_issues                        31636 non-null  str
 16  cc_dissatisfaction_time_to_complete       31636 non-null  str
 17  cc_process_complexity_concerns            31636 non-null  str
 18  cc_questions_harder_than_expected         31636 non-null  str
 19  cc_dissatisfaction_support                31636 non-null  str
 20  cc_contractor_sentiment                   31636 non-null  str
 21  cc_contractor_sentiment_start_score       31636 non-null  float64
 22  cc_contractor_sentiment_end_score         31636 non-null  float64
 23  cc_contractor_sentiment_overall_score     31636 non-null  float64
 24  cc_pricing_mentioned                      31636 non-null  str
 25  cc_pricing_sentiment_impact               31636 non-null  str
 26  cc_refund_discussed                       31636 non-null  str
 27  cc_contractor_suggest_leave               31636 non-null  str
 28  cc_contractor_complained                  31636 non-null  str
 29  co_ref                                    31636 non-null  str
dtypes: float64(4), str(26)
memory usage: 7.2 MB

In [5]:
df_merged = (
    df_billings
    .merge(df_renewal, on='co_ref', how='left', suffixes=('', '_renewal'))
    .merge(df_email, on='co_ref', how='left', suffixes=('', '_email'))
    .merge(df_cc, on='co_ref', how='left', suffixes=('', '_cc'))
)

In [6]:
df_merged.shape

(668008, 130)

In [7]:
for col in df_merged.columns:
    print(df_merged[col].value_counts(dropna=False))
    print(df_merged[col].isnull().sum())
    print("-" * 50)

co_ref
VU9662    3968
AD1657    1610
DB3207    1292
AA0994    1287
FW0890     900
          ...
XQ5674       1
MH5611       1
LQ9360       1
EX0639       1
XU6585       1
Name: count, Length: 47814, dtype: int64
0
--------------------------------------------------
renewal_month
2025-10-01    21429
2025-11-01    21214
2024-11-01    20904
2024-10-01    20506
2025-09-01    19763
2024-09-01    19288
2024-06-01    19064
2025-01-01    18402
2024-05-01    18228
2025-06-01    18111
2025-05-01    18062
2023-11-01    18056
2023-10-01    17873
2026-01-01    17650
2025-07-01    17613
2026-02-01    17569
2024-07-01    17436
2023-09-01    16961
2025-02-01    16928
2024-08-01    16836
2023-06-01    16728
2025-08-01    16650
2026-05-01    16192
2023-05-01    16080
2024-01-01    15590
2023-07-01    15499
2024-02-01    14685
2024-04-01    14473
2023-08-01    14292
2025-04-01    14225
2025-12-01    13923
2023-01-01    13903
2024-12-01    13762
2025-03-01    13443
2023-02-01    13351
2023-04-01    12994
2024-03-01    12716
2023-12-01    12433
2026-04-01    12124
2026-03-01    11817
2023-03-01    11235
Name: count, dtype: int64
0
--------------------------------------------------
sustainability_score
8.0    391285
9.5    194680
9.0     82043
Name: count, dtype: int64
0
--------------------------------------------------
total_renewal_score_new
44.0    82186
43.0    63443
45.5    58934
45.0    56146
44.5    54122
43.5    49857
42.0    41418
41.0    30408
42.5    26827
46.5    24704
41.5    20659
46.0    18823
33.0    17545
40.0    14792
34.0    14686
32.0    14393
32.5    12336
40.5    12028
35.0    11040
33.5    10338
34.5    10038
31.5     5559
39.5     5510
31.0     4270
39.0     3600
36.0     1346
38.5      967
35.5      957
30.5      425
36.5      285
38.0      228
37.5      132
37.0        6
Name: count, dtype: int64
0
--------------------------------------------------
last_years_price
999.00    29450
599.00    21923
639.00    21372
579.00    19819
949.00    18585
          ...
403.20        1
208.75        1
78.75         1
580.00        1
258.75        1
Name: count, Length: 2791, dtype: int64
0
--------------------------------------------------
auto_renewal_score
8    370909
9    297099
Name: count, dtype: int64
0
--------------------------------------------------
status_scores
9    379500
0    103356
8     97434
7     87718
Name: count, dtype: int64
0
--------------------------------------------------
anchoring_score
9.5    229847
8.5    188702
7.5    139722
9.0    109736
8.0         1
Name: count, dtype: int64
0
--------------------------------------------------
tenure_scores
9.5    372359
8.5    128746
9.0    101604
8.0     43184
7.5     20212
7.0      1903
Name: count, dtype: int64
0
--------------------------------------------------
proforma_auto_renewal
True     649142
False     18866
Name: count, dtype: int64
0
--------------------------------------------------
proforma_world_pay_token
False    421635
True     246373
Name: count, dtype: int64
0
--------------------------------------------------
proforma_date
2022-11-07    13903
2023-08-14     9371
2026-02-11     9248
2024-03-12     9202
2024-09-05     8973
              ...
2022-12-06        3
2025-12-01        2
2025-11-14        1
2024-09-20        1
2024-08-13        1
Name: count, Length: 169, dtype: int64
0
--------------------------------------------------
current_anchorings
1      188702
0      139723
2      109736
3       67340
4       38356
        ...
81          3
161         3
105         3
69          2
89          1
Name: count, Length: 107, dtype: int64
0
--------------------------------------------------
payment_timeframe
 0      222526
 1       22491
-1       19500
 2       14041
-2       11910
         ...
-397         1
-140         1
-369         1
-277         1
-87          1
Name: count, Length: 287, dtype: int64
0
--------------------------------------------------

registration_date
2019-03-25    5813
2019-05-08    4112
2025-02-18    1649
2019-04-16    1635
2017-01-25    1411
              ...
2024-10-05       1
2024-10-06       1
2024-07-27       1
2024-11-02       1
2024-12-15       1
Name: count, Length: 5787, dtype: int64
0
--------------------------------------------------
proforma_account_stage
Published          412736
Membership Only    103043
Renewal Process     93415
Unknown             38489
Vetting             14318
Suspended            5995
Retired                12
Name: count, dtype: int64
0
--------------------------------------------------
proforma_audit_status
Accredited                                                  406644
Failed- Renewal Questionnaire not received                   43606
Renewal Questionnaire Received                               40865
Unknown                                                      38489
Renewal Questionnaire Sent                                   24119
Failed- Renewal Additional Information Not Received          22875
Failed- Initial additional info not received                 20602
Failed- Initial Questionnaire not received                   15903
Renewal report sent - Awaiting information                    8855
Initial Questionnaire Received                                8213
1st Renewal questionnaire reminder                            7642
Accredited - SSiP due to expire                               5887
Final renewal questionnaire reminder                          5470
Report sent - Awaiting information                            2918
1st Reminder - Renewal additional info                        2794
Final reminder - Renewal additional info                      2653
SUSPENDED - SSiP Expired                                      2570
1st reminder initial add info                                 1583
Final Reminder (Initial) Additional Information Not Sent      1339
SUSPENDED - 1st reminder SSiP Expired                         1269
SSiP Expired - 1st Reminder                                   1117
Renewal additional information received                       1009
SUSPENDED - 2nd reminder SSiP Expired                          991
Additional information received                                220
Accred Due to Expire                                           199
Failed- Accreditation removed SSiP exp                          65
Suspended - Insurance Out-of-Date                               48
Initial - 1st Questionnaire reminder sent                       32
Initial Questionnaire Sent                                      12
Withdrawn from scheme                                           12
unknown                                                          6
Delete 38                                                        1
Name: count, dtype: int64
0
--------------------------------------------------
current_auto_renewal_flag
y    619015
n     48993
Name: count, dtype: int64
0
--------------------------------------------------
current_world_pay_token
n    370760
y    297248
Name: count, dtype: int64
0
--------------------------------------------------
renewal_score_at_release
28.0    106651
27.0     69402
26.0     67882
27.5     66223
26.5     63622
24.5     51190
25.5     43341
25.0     40859
23.5     33151
23.0     31660
24.0     28379
22.5     17053
22.0     14641
28.2     10725
21.5      9165
20.5      4574
27.7      3658
21.0      2448
27.2      1546
25.2       642
26.7       561
24.7       267
24.2       164
25.7       102
26.2        62
23.7        16
16.5        11
22.7        11
15.5         2
Name: count, dtype: int64
0
--------------------------------------------------

proforma_membership_status
Accredited     476732
Member Only    116314
In Progress     74949
Non Member         13
Name: count, dtype: int64
0
--------------------------------------------------
proforma_approved_lists
1      201363
0      136023
2      103313
3       58093
4       39101
        ...
171         1
130         1
162         1
156         1
137         1
Name: count, Length: 135, dtype: int64
0
--------------------------------------------------
tenure_years
1     84334
2     74855
3     60512
4     52374
5     51055
6     41858
7     39729
8     35607
9     32123
10    28834
11    24042
12    21343
13    19449
14    18324
15    18216
16    16225
17    11723
18     8310
20     8250
19     7597
21     6317
22     4315
0      1589
23      799
24      153
25       71
26        4
Name: count, dtype: int64
0
--------------------------------------------------
band
Band B     174100
Band C1    130048
Band D     102755
Band C2     86650
Band E      53272
Band F1     33888
Band F2     20978
Band A      19490
Band G      16951
Band F      12206
Group        5903
Band H       5232
Band J       3651
Band I       2884
Name: count, dtype: int64
0
--------------------------------------------------
prospect_renewal_date
2026-02-18    2038
2025-05-08    1310
2026-05-08    1275
2023-05-08    1265
2024-05-08    1262
              ...
2025-12-26      20
2024-12-27      19
2025-12-27      13
2023-12-27      12
2024-12-26      10
Name: count, Length: 1242, dtype: int64
0
--------------------------------------------------
starting_net
999     32026
599     27594
684     25565
639     25490
579     25182
        ...
709         1
5010        1
6338        1
8333        1
1164        1
Name: count, Length: 1272, dtype: int64
0
--------------------------------------------------
starting_vat
199.8     31764
119.8     27482
136.8     25499
127.8     25399
115.8     25082
          ...
2.0           1
1002.0        1
1267.6        1
1666.6        1
232.8         1
Name: count, Length: 1273, dtype: int64
0
--------------------------------------------------
starting_gross
1198.8    31764
718.8     27482
820.8     25499
766.8     25399
694.8     25082
          ...
2654.0        1
6012.0        1
7605.6        1
9999.6        1
1396.8        1
Name: count, Length: 1461, dtype: int64
0
--------------------------------------------------
starting_membership_net
864     56500
500     52675
480     49223
664     41448
1214    37952
        ...
5010        1
6836        1
4130        1
5318        1
6963        1
Name: count, Length: 123, dtype: int64
0
--------------------------------------------------
starting_package_net
0      346411
120     73494
150     37103
85      26189
105     24783
140     24780
115     23325
160     21317
100     19667
190     15371
145     12213
175     11809
80       9089
125      6903
155      6180
60       2771
225      2523
185      2203
55        966
70        861
200        50
Name: count, dtype: int64
0
--------------------------------------------------
starting_pqq_net
135     377390
99      188283
200      84495
250      11676
390       2067
320       1465
460       1284
530        404
600        193
740        146
880        133
670        132
0          122
810         40
1790        34
1090        25
1860        21
1510        21
1160        15
1230        14
1930        13
1720        13
950         11
1020         9
1370         2
Name: count, dtype: int64
0
--------------------------------------------------
membership_net
864.0     47366
500.0     39861
480.0     36362
664.0     33591
1214.0    32960
          ...
133.0         1
294.0         1
291.0         1
94.0          1
232.0         1
Name: count, Length: 875, dtype: int64
0
--------------------------------------------------
package_net
0.00      382883
120.00     63824
150.00     28471
140.00     22202
85.00      20388
           ...
93.75          1
92.50          1
77.50          1
111.00         1
33.00          1
Name: count, Length: 122, dtype: int64
0
--------------------------------------------------
pqqnet
 135    367262
 99     185214
 200     83454
 250     11716
 0        6193
         ...
 210         1
 40          1
 10          1
-135         1
 6           1
Name: count, Length: 111, dtype: int64
0
--------------------------------------------------
prospect_outcome
Won        576042
Churned     54362
Open        37604
Name: count, dtype: int64
0
--------------------------------------------------
payment_method
Card         371271
Bacs         198175
Unknown       85774
World Pay     12146
Cheque          642
Name: count, dtype: int64
0
--------------------------------------------------
total_amount
999.0    27149
599.0    22090
639.0    20338
579.0    20250
949.0    19048
         ...
501.1        1
390.3        1
395.0        1
174.0        1
296.0        1
Name: count, Length: 2754, dtype: int64
0
--------------------------------------------------
tenure_group
4+    446718
1      85923
2      74855
3      60512
Name: count, dtype: int64

0
--------------------------------------------------
last_renewal
2024-11-01    19030
2024-10-01    18641
2023-11-01    18223
2023-10-01    17904
2024-09-01    17518
              ...
2025-06-22        1
2025-04-28        1
2025-12-27        1
2025-07-27        1
2025-11-02        1
Name: count, Length: 1155, dtype: int64
0
--------------------------------------------------
last_band
Band B     176683
Band C1    130011
Band D     100940
Band C2     89839
Band E      51013
Band F1     25428
Band F      24191
Band A      19833
Band G      16755
Band F2     15707
Group        6045
Band H       5151
Band I       3645
Band J       2767
Name: count, dtype: int64
0
--------------------------------------------------
last_total_net_paid
539.0     28209
579.0     25316
999.0     22613
684.0     22592
949.0     20335
          ...
184.0         1
872.8         1
1109.2        1
3096.2        1
4589.0        1
Name: count, Length: 1289, dtype: int64
0
--------------------------------------------------
last_connections
0      324178
1      125172
2       64336
3       37815
4       26268
        ...
75          1
163         1
114         1
137         1
156         1
Name: count, Length: 127, dtype: int64
0
--------------------------------------------------
anchor_group
1              201363
Independent    136023
4 to 9         116439
2              103313
3               58093
10+             52777
Name: count, dtype: int64
0
--------------------------------------------------
renewal_year
2025    209763
2024    203488
2023    179405
2026     75352
Name: count, dtype: int64
0
--------------------------------------------------
is_first_year
0    425912
1    242096
Name: count, dtype: int64
0
--------------------------------------------------
has_discount
0    564746
1    103262
Name: count, dtype: int64
0
--------------------------------------------------
discount_pct
0.000    564746
0.200     47610
0.300     16652
0.500     14359
0.400     11417
0.100      6395
0.150      4031
0.350      1793
0.250       822
0.450       175
1.000         5
0.133         3
Name: count, dtype: int64
0
--------------------------------------------------
call_id
NaN             29278
5.950000e+11    22808
5.110000e+11    20596
5.940000e+11    20403
5.090000e+11    20381
5.070000e+11    20223
5.960000e+11    19629
5.080000e+11    19226
5.380000e+11    17538
6.230000e+11    16357
6.220000e+11    16187
5.650000e+11    15907
5.390000e+11    15757
5.100000e+11    15534
5.920000e+11    15458
5.060000e+11    15457
5.910000e+11    15235
5.130000e+11    15056
5.120000e+11    15029
6.260000e+11    14105
5.970000e+11    13934
6.940000e+11    13681
5.900000e+11    13452
6.250000e+11    12887
6.820000e+11    12345
6.790000e+11    11679
6.510000e+11    11665
6.930000e+11    11660
6.850000e+11    11596
6.880000e+11    11478
6.830000e+11    11164
6.860000e+11    11036
6.870000e+11    10864
6.770000e+11    10548
6.920000e+11    10496
6.900000e+11    10482
6.890000e+11     9968
6.240000e+11     9905
6.840000e+11     9761
6.800000e+11     9556
5.400000e+11     9319
5.930000e+11     9052
6.810000e+11     8873
5.640000e+11     8432
6.780000e+11     8034
5.050000e+11     7615
6.520000e+11     6930
6.950000e+11     5917
5.370000e+11     3775
6.910000e+11     3200
5.660000e+11     2810
6.760000e+11     2309
1.940000e+11     1965
1.930000e+11     1456
Name: count, dtype: int64
29278
--------------------------------------------------
call_direction
OUT_BOUND    530673
IN_BOUND     108057
NaN           29278
Name: count, dtype: int64
29278
--------------------------------------------------
call_date
NaN           29278
2025-01-15     2841
2025-01-13     2594
2025-01-27     2516
2025-01-14     2270
              ...
2025-03-25      450
2025-07-10      373
2025-12-24       87
2026-01-17       44
2026-01-11        8
Name: count, Length: 468, dtype: int64
29278
--------------------------------------------------

membership_renewal_decision
No         348456
Unknown    264729
NaN         29278
Yes         25545
Name: count, dtype: int64
29278
--------------------------------------------------
serious_complaint
No         361796
Unknown    274723
NaN         29278
Yes          2211
Name: count, dtype: int64
29278
--------------------------------------------------
other_complaint
No         278697
Unknown    274737
Yes         85296
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
discussion_on_price_increase
No         344093
Unknown    258020
Yes         36617
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
renewal_impact_due_to_price_increase
No         366755
Unknown    258265
NaN         29278
Yes         13710
Name: count, dtype: int64
29278
--------------------------------------------------
discount_or_waiver_requested
No         368528
Unknown    258282
NaN         29278
Yes         11920
Name: count, dtype: int64
29278
--------------------------------------------------
call_reschedule_request
No         374117
Unknown    255676
NaN         29278
Yes          8937
Name: count, dtype: int64
29278
--------------------------------------------------
agent_flagged_membership_status_alert
No         266648
Unknown    255676
Yes        116406
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------

agent_renewal_initiation
Unknown    255676
No         206829
Yes        176225
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
explicit_competitor_mention
No         376986
Unknown    255193
NaN         29278
Yes          6551
Name: count, dtype: int64
29278
--------------------------------------------------
explicit_switching_intent
No         383323
Unknown    255211
NaN         29278
Yes           196
Name: count, dtype: int64
29278
--------------------------------------------------
mentioned_competitors
No         353962
Unknown    255227
Yes         29541
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
price_switching_mentioned
No         370884
Unknown    255396
NaN         29278
Yes         12450
Name: count, dtype: int64
29278
--------------------------------------------------
competitor_value_comparison
Not Applicable    361829
Unknown           255459
NaN                29278
Not Discussed      12951
Better Value        5612
Similar Value       2879
Name: count, dtype: int64
29278
--------------------------------------------------
competitor_benefits_mentioned
Not Applicable    281431
Unknown           270647
Not Discussed      66905
NaN                29278
Discounts          11151
Better Service      8596
Name: count, dtype: int64
29278
--------------------------------------------------
topic_introduced_by
Not Discussed    289190
Unknown          255019
Agent             69173
NaN               29278
Customer          25348
Name: count, dtype: int64
29278
--------------------------------------------------
percentage_price_increase_mentioned
No               377841
Unknown          255019
NaN               29278
Yes                3408
Not Discussed      2462
Name: count, dtype: int64

29278
--------------------------------------------------
monetary_price_increase_mentioned
No               367827
Unknown          255019
NaN               29278
Yes               13422
Not Discussed      2462
Name: count, dtype: int64
29278
--------------------------------------------------
price_range_mentioned
Not Discussed    365197
Unknown          255029
NaN               29278
589.0               594
899.0               233
                  ...
521.0                 1
6.52                  1
7.34                  1
55.0                  1
767.0                 1
Name: count, Length: 1804, dtype: int64
29278
--------------------------------------------------
customer_asked_for_justification
No               355325
Unknown          255019
NaN               29278
Yes               25922
Not Discussed      2464
Name: count, dtype: int64
29278
--------------------------------------------------
customer_response
Neutral          257562
Unknown          255019
Not Discussed    100565
NaN               29278
Negative          22388
Positive           3196
Name: count, dtype: int64
29278
--------------------------------------------------
desire_to_cancel
Unknown              255295
Renewed              188510
Not Discussed        160792
Desired to Cancel     34133
NaN                   29278
Name: count, dtype: int64
29278
--------------------------------------------------
discount_offered
No               356677
Unknown          255019
NaN               29278
Yes               24569
Not Discussed      2465
Name: count, dtype: int64
29278
--------------------------------------------------
call_number
1.0      117544
2.0      109663
3.0       81805
4.0       61709
5.0       47848
          ...
135.0         1
156.0         1
169.0         1
171.0         1
172.0         1
Name: count, Length: 182, dtype: int64
29278
--------------------------------------------------
time_to_renewal
pre_renewal    430001
NaN            238007
Name: count, dtype: int64

238007
--------------------------------------------------
crm_accreditation_completed
NaN              238007
Not Discussed    228307
No               108963
Unknown           47419
Yes               45312
Name: count, dtype: int64
238007
--------------------------------------------------
crm_timely_completion
Not Discussed    345638
NaN              238007
Unknown           47419
No                28334
Yes                8610
Name: count, dtype: int64
238007
--------------------------------------------------
crm_progress_towards_accreditation
Not Discussed    290974
NaN              238007
Yes               81971
Unknown           47419
No                 9637
Name: count, dtype: int64
238007
--------------------------------------------------
crm_delays_in_accreditation
No               287375
NaN              238007
Yes               90025
Unknown           47419
Not Discussed      5182
Name: count, dtype: int64
238007
--------------------------------------------------
crm_contractor_suggested_leave
No               288816
NaN              238007
Yes               48027
Unknown           47419
Not Discussed     45739
Name: count, dtype: int64
238007
--------------------------------------------------
crm_contractor_engagement
Yes              245873
NaN              238007
No               136683
Unknown           47419
Not Discussed        26
Name: count, dtype: int64
238007
--------------------------------------------------
crm_contractor_sentiment
NaN             238007
Unknown         183901
neutral         174977
satisfied        40831
dissatisfied     30292
Name: count, dtype: int64
238007
--------------------------------------------------
crm_contractor_sentiment_score
 NaN      238007
-1.0      183955
 50.0     174849
 80.0      28849
 20.0      15867
 90.0       8626
 30.0       5526
 0.0        4832
 40.0       3993
 100.0      3297
 84.0         36
 55.0         36
 16.0         30
 98.0         21
 31.0         20
 48.0         15
 60.0         15
 70.0         15
 25.5          9
 96.0          8
 91.0          2
Name: count, dtype: int64
238007
--------------------------------------------------
crm_dts_or_ssip_mentioned
No               299444
NaN              238007
Yes               83137
Unknown           47419
Not Discussed         1
Name: count, dtype: int64
238007
--------------------------------------------------
crm_customer_payment_intention
NaN              238007
Not Discussed    206593
Yes              131801
Unknown           47419
No                44188
Name: count, dtype: int64
238007
--------------------------------------------------
crm_competitors_mentioned
No               314704
NaN              238007
Not Discussed     76459
Unknown           30105
Yes                8733
Name: count, dtype: int64

238007
--------------------------------------------------
crm_membership_level
NaN               238007
Accredited        158537
Not Discussed     150360
In progress        86802
Unknown            30105
Not Accredited      2066
Members only        1622
Standard             462
Premier               47
Name: count, dtype: int64
238007
--------------------------------------------------
crm_platform_issues_raised
No               307442
NaN              238007
Not Discussed     73446
Unknown           30105
Yes               19008
Name: count, dtype: int64
238007
--------------------------------------------------
crm_agent_chased_contractor
Yes              268890
NaN              238007
No               129393
Unknown           30105
Not Discussed      1613
Name: count, dtype: int64
238007
--------------------------------------------------
crm_agent_chase_count
NaN     238007
1.0     176202
0.0     131032
2.0      95741
3.0      22004
4.0       3503
5.0       1092
6.0        362
7.0         36
11.0        16
8.0          8
10.0         4
13.0         1
Name: count, dtype: int64
238007
--------------------------------------------------
crm_accreditation_issues
Not Discussed    296820
NaN              238007
Yes               57948
No                45128
Unknown           30105
Name: count, dtype: int64
238007
--------------------------------------------------
crm_membership_overdue
NaN              238007
Yes              218470
Not Discussed    118078
No                63348
Unknown           30105
Name: count, dtype: int64
238007
--------------------------------------------------
crm_auto_renewal_status
0.0    406467
NaN    238007
2.0     21842
1.0      1692
Name: count, dtype: int64
238007
--------------------------------------------------
crm_dissatisified_with_renewal_price
Not Discussed    271107
NaN              238007
No                98956
Unknown           30105
Yes               29833
Name: count, dtype: int64
238007
--------------------------------------------------
crm_customer_complained
No               366680
NaN              238007
Unknown           32106
Yes               31179
Not Discussed        36
Name: count, dtype: int64
238007
--------------------------------------------------
crm_refund_mentioned
No               392454
NaN              238007
Unknown           32106
Yes                5405
Not Discussed        36
Name: count, dtype: int64
238007
--------------------------------------------------
crm_negative_customer_experience
NaN              238007
No               218529
Not Discussed    102868
Yes               76498
Unknown           32106
Name: count, dtype: int64
238007
--------------------------------------------------
crm_dissatisfaction_with_support
NaN              238007
No               215597
Not Discussed    151577
Unknown           32106
Yes               30721
Name: count, dtype: int64

238007
--------------------------------------------------
crm_financial_hardship_mentioned
Not Discussed    303264
NaN              238007
No                67911
Unknown           32106
Yes               26720
Name: count, dtype: int64
238007
--------------------------------------------------
year
2025.0    302539
NaN       238007
2026.0    127462
Name: count, dtype: int64
238007
--------------------------------------------------
sentiment_score_missing
0.0    246046
NaN    238007
1.0    183955
Name: count, dtype: int64
238007
--------------------------------------------------
contact_id
NaN             300559
6.854460e+11      2761
6.914790e+11      2653
6.862780e+11      2640
6.916730e+11      2621
                 ...
6.217010e+11         4
5.645430e+11         3
5.647580e+11         3
5.640720e+11         2
5.647570e+11         1
Name: count, Length: 495, dtype: int64
300559
--------------------------------------------------
call_date_cc
NaN           300559
2025-11-26      2894
2025-10-20      2835
2025-10-22      2758
2026-01-05      2653
               ...
2024-09-23         6
2024-09-25         4
2024-09-12         3
2024-10-15         1
2024-10-17         1
Name: count, Length: 324, dtype: int64
300559
--------------------------------------------------
direction
NaN          300559
OUT_BOUND    271539
IN_BOUND      95910
Name: count, dtype: int64
300559
--------------------------------------------------
cc_care_package
NaN              300559
Not Discussed    290460
Standard          41348
Express           26544
Premier            5252
Unknown            2595
Assisted           1250
Name: count, dtype: int64
300559
--------------------------------------------------
cc_care_package_discussed
NaN        300559
No         289322
Yes         76270
Unknown      1857
Name: count, dtype: int64
300559
--------------------------------------------------
cc_urgency_getting_on_site
No         322685
NaN        300559
Yes         42907
Unknown      1857
Name: count, dtype: int64
300559
--------------------------------------------------
cc_external_consultant
No         328005
NaN        300559
Yes         37587
Unknown      1857
Name: count, dtype: int64
300559
--------------------------------------------------
cc_agent_cross_sell_attempt
No         352396
NaN        300559
Yes         12989
Unknown      2064
Name: count, dtype: int64
300559
--------------------------------------------------
cc_customer_issues_concerns
No         325845
NaN        300559
Yes         39543
Unknown      2061
Name: count, dtype: int64
300559
--------------------------------------------------
cc_business_struggles_financial_hardship
No         354281
NaN        300559
Yes         11230
Unknown      1938
Name: count, dtype: int64
300559
--------------------------------------------------
cc_call_initiated_by
NaN             300559
Customer        252371
Agent            92683
Not Relevant     20289
Unknown           2106
Name: count, dtype: int64

300559
--------------------------------------------------
cc_questionnaire_completion
NaN        300559
No         294543
Yes         72442
Unknown       464
Name: count, dtype: int64
300559
--------------------------------------------------
cc_chasing_response
NaN        300559
No         271194
Yes         93403
Unknown      2852
Name: count, dtype: int64
300559
--------------------------------------------------
cc_issues_within_questionnaire
No         307343
NaN        300559
Yes         45870
Unknown     14236
Name: count, dtype: int64
300559
--------------------------------------------------
cc_login_issues
No         346227
NaN        300559
Yes         20580
Unknown       642
Name: count, dtype: int64
300559
--------------------------------------------------
cc_platform_issues
No         340017
NaN        300559
Yes         26904
Unknown       528
Name: count, dtype: int64
300559
--------------------------------------------------
cc_dissatisfaction_time_to_complete
No         348753
NaN        300559
Yes         18200
Unknown       496
Name: count, dtype: int64
300559
--------------------------------------------------
cc_process_complexity_concerns
No         327438
NaN        300559
Yes         39199
Unknown       812
Name: count, dtype: int64
300559
--------------------------------------------------
cc_questions_harder_than_expected
No         365463
NaN        300559
Yes          1373
Unknown       613
Name: count, dtype: int64
300559
--------------------------------------------------
cc_dissatisfaction_support
No         356450
NaN        300559
Yes         10453
Unknown       546
Name: count, dtype: int64
300559
--------------------------------------------------
cc_contractor_sentiment
NaN              300559
Satisfied        174142
Neutral          146013
Not Discussed     31698
Dissatisfied      13994
Unknown            1602
Name: count, dtype: int64
300559
--------------------------------------------------
cc_contractor_sentiment_start_score
50.0     301721
NaN      300559
80.0      38241
20.0      13374
40.0       6412
60.0       6182
0.0        1153
100.0       134
30.0        105
70.0         86
10.0         41
Name: count, dtype: int64

300559
--------------------------------------------------
cc_contractor_sentiment_end_score
NaN      300559
90.0     146573
80.0     130716
50.0      61015
100.0      8776
60.0       7514
70.0       5400
0.0        2975
40.0       1727
95.0       1260
20.0        899
30.0        503
10.0         87
75.0          4
Name: count, dtype: int64
300559
--------------------------------------------------
cc_contractor_sentiment_overall_score
NaN      300559
80.0     174182
90.0     112350
85.0      26652
70.0      15842
50.0      11658
60.0       8203
100.0      6489
40.0       3073
65.0       1689
55.0       1610
95.0       1459
0.0        1057
20.0        922
30.0        853
75.0        612
92.0        481
45.0        164
10.0         93
25.0         60
Name: count, dtype: int64
300559
--------------------------------------------------
cc_pricing_mentioned
No         317709
NaN        300559
Yes         48156
Unknown      1584
Name: count, dtype: int64
300559
--------------------------------------------------
cc_pricing_sentiment_impact
No         352796
NaN        300559
Yes         13441
Unknown      1212
Name: count, dtype: int64
300559
--------------------------------------------------
cc_refund_discussed
No         364269
NaN        300559
Yes          2090
Unknown      1090
Name: count, dtype: int64
300559
--------------------------------------------------
cc_contractor_suggest_leave
No         356154
NaN        300559
Yes          9597
Unknown      1698
Name: count, dtype: int64
300559
--------------------------------------------------
cc_contractor_complained
No         335970
NaN        300559
Yes         29832
Unknown      1647
Name: count, dtype: int64
300559
--------------------------------------------------

In [8]:
df_merged

,co_ref,renewal_month,sustainability_score,total_renewal_score_new,last_years_price,auto_renewal_score,status_scores,anchoring_score,tenure_scores,proforma_auto_renewal,proforma_world_pay_token,proforma_date,current_anchorings,payment_timeframe,registration_date,proforma_account_stage,proforma_audit_status,current_auto_renewal_flag,current_world_pay_token,renewal_score_at_release,proforma_membership_status,proforma_approved_lists,tenure_years,band,prospect_renewal_date,starting_net,starting_vat,starting_gross,starting_membership_net,starting_package_net,starting_pqq_net,membership_net,package_net,pqqnet,prospect_outcome,payment_method,total_amount,tenure_group,last_renewal,last_band,last_total_net_paid,last_connections,anchor_group,renewal_year,is_first_year,has_discount,discount_pct,call_id,call_direction,call_date,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,call_number,time_to_renewal,crm_accreditation_completed,crm_timely_completion,crm_progress_towards_accreditation,crm_delays_in_accreditation,crm_contractor_suggested_leave,crm_contractor_engagement,crm_contractor_sentiment,crm_contractor_sentiment_score,crm_dts_or_ssip_mentioned,crm_customer_payment_intention,crm_competitors_mentioned,crm_membership_level,crm_platform_issues_raised,crm_agent_chased_contractor,crm_agent_chase_count,crm_accreditation_issues,crm_membership_overdue,crm_auto_renewal_status,crm_dissatisified_with_renewal_price,crm_customer_complained,crm_refund_mentioned,crm_negative_customer_experience,crm_dissatisfaction_with_support,crm_financial_hardship_mentioned,year,sentiment_score_missing,contact_id,call_date_cc,direction,cc_care_package,cc_care_package_discussed,cc_urgency_getting_on_site,cc_external_consultant,cc_agent_cross_sell_attempt,cc_customer_issues_concerns,cc_business_struggles_financial_hardship,cc_call_initiated_by,cc_questionnaire_completion,cc_chasing_response,cc_issues_within_questionnaire,cc_login_issues,cc_platform_issues,cc_dissatisfaction_time_to_complete,cc_process_complexity_concerns,cc_questions_harder_than_expected,cc_dissatisfaction_support,cc_contractor_sentiment,cc_contractor_sentiment_start_score,cc_contractor_sentiment_end_score,cc_contractor_sentiment_overall_score,cc_pricing_mentioned,cc_pricing_sentiment_impact,cc_refund_discussed,cc_contractor_suggest_leave,cc_contractor_complained
0,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,True,2024-09-06,0,0,2021-11-05,Published,Accredited,y,y,26.0,Accredited,1,3,Band C1,2024-11-05,919,183.8,1102.8,664,120,135,664.0,0.0,135,Won,Card,799.0,3,2023-11-01,Band B,664.0,1,1,2024,0,0,0.0,6.920000e+11,OUT_BOUND,2026-01-13,No,No,No,No,No,No,Yes,No,Yes,No,No,No,No,Not Applicable,Not Applicable,Not Discussed,No,No,Not Discussed,No,Neutral,Not Discussed,No,5.0,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,neutral,50.0,No,Yes,No,Accredited,No,No,0.0,Not Discussed,Not Discussed,0.0,Not Discussed,No,No,No,No,Not Discussed,2025.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,True,2024-09-06,0,0,2021-11-05,Published,Accredited,y,y,26.0,Accredited,1,3,Band C1,2024-11-05,919,183.8,1102.8,664,120,135,664.0,0.0,135,Won,Card,799.0,3,2023-11-01,Band B,664.0,1,1,2024,0,0,0.0,6.870000e+11,OUT_BOUND,2025-11-05,No,No,Yes,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Not Discussed,Not Discussed,No,No,Not Discussed,No,Neutral,Renewed,No,4.0,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,neutral,50.0,No,Yes,No,Accredited,No,No,0.0,Not Discussed,Not Discussed,0.0,Not Discussed,No,No,No,No,Not Discussed,2025.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,True,2024-09-06,0,0,2021-11-05,Published,Accredited,y,y,26.0,Accredited,1,3,Band C1,2024-11-05,919,183.8,1102.8,664,120,135,664.0,0.0,135,Won,Card,799.0,3,2023-11-01,Band B,664.0,1,1,2024,0,0,0.0,6.850000e+11,OUT_BOUND,2025-10-09,No,No,No,Yes,No,No,No,No,Yes,No,No,No,No,Not Applicable,Not Applicable,Agent,No,No,769.0,Yes,Neutral,Renewed,No,2.0,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,neutral,50.0,No,Yes,No,Accredited,No,No,0.0,Not Discussed,Not Discussed,0.0,Not Discussed,No,No,No,No,Not Discussed,2025.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,True,2024-09-06,0,0,2021-11-05,Published,Accredited,y,y,26.0,Accredited,1,3,Band C1,2024-11-05,919,183.8,1102.8,664,120,135,664.0,0.0,135,Won,Card,799.0,3,2023-11-01,Band B,664.0,1,1,2024,0,0,0.0,6.860000e+11,OUT_BOUND,2025-10-29,No,No,Yes,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better Service,Customer,No,No,Not Discussed,Yes,Negative,Renewed,No,3.0,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,neutral,50.0,No,Yes,No,Accredited,No,No,0.0,Not Discussed,Not Discussed,0.0,Not Discussed,No,No,No,No,Not Discussed,2025.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,True,2024-09-06,0,0,2021-11-05,Published,Accredited,y,y,26.0,Accredited,1,3,Band C1,2024-11-05,919,183.8,1102.8,664,120,135,664.0,0.0,135,Won,Card,799.0,3,2023-11-01,Band B,664.0,1,1,2024,0,0,0.0,5.640000e+11,OUT_BOUND,2024-10-09,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Not Applicable,Agent,No,Yes,Not Discussed,No,Neutral,Renewed,No,1.0,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,neutral,50.0,No,Yes,No,Accredited,No,No,0.0,Not Discussed,Not Discussed,0.0,Not Discussed,No,No,No,No,Not Discussed,2025.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668003,DO6023,2023-09-01,8.0,33.0,539.0,9,0,7.5,8.5,True,False,2023-07-06,0,-4,2020-09-15,Published,Accredited,y,y,25.5,Accredited,0,3,Band B,2023-09-15,539,107.8,646.8,440,0,99,440.0,0.0,99,Won,Card,539.0,3,2023-09-15,Band B,539.0,0,Independent,2023,1,0,0.0,5.380000e+11,OUT_BOUND,2024-08-23,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668004,KR5815,2023-08-01,8.0,40.5,539.0,9,7,7.5,9.0,True,False,2023-06-07,0,48,2020-08-03,Published,Accredited,y,y,25.5,Accredited,0,3,Band B,2023-08-03,539,107.8,646.8,440,0,99,440.0,0.0,99,Won,Card,539.0,3,2023-08-03,Band B,539.0,0,Independent,2023,1,0,0.0,5.110000e+11,OUT_BOUND,2024-07-08,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Not Applicable,Not Discussed,No,No,Not Discussed,No,Neutral,Renewed,No,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668005,KR5815,2023-08-01,8.0,40.5,539.0,9,7,7.5,9.0,True,False,2023-06-07,0,48,2020-08-03,Published,Accredited,y,y,25.5,Accredited,0,3,Band B,2023-08-03,539,107.8,646.8,440,0,99,440.0,0.0,99,Won,Card,539.0,3,2023-08-03,Band B,539.0,0,Independent,2023,1,0,0.0,6.780000e+11,OUT_BOUND,2025-07-07,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668006,MA8737,2023-07-01,8.0,42.5,539.0,9,9,7.5,9.0,True,False,2023-05-10,0,12,2020-07-08,Published,Accredited,y,y,25.5,Accredited,0,3,Band B,2023-07-08,539,107.8,646.8,440,0,99,440.0,0.0,99,Won,Card,539.0,3,2023-07-08,Band B,539.0,0,Independent,2023,1,0,0.0,5.110000e+11,OUT_BOUND,2024-07-02,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Not Applicable,Not Discussed,No,No,Not Discussed,No,Neutral,Renewed,No,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.936970e+11,2025-01-08,IN_BOUND,Not Discussed,No,No,No,No,No,No,Customer,Yes,No,Yes,No,No,No,No,No,No,Satisfied,50.0,90.0,90.0,No,No,No,No,No
668007,MA8737,2023-07-01,8.0,42.5,539.0,9,9,7.5,9.0,True,False,2023-05-10,0,12,2020-07-08,Published,Accredited,y,y,25.5,Accredited,0,3,Band B,2023-07-08,539,107.8,646.8,440,0,99,440.0,0.0,99,Won,Card,539.0,3,2023-07-08,Band B,539.0,0,Independent,2023,1,0,0.0,6.520000e+11,OUT_BOUND,2025-06-12,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.936970e+11,2025-01-08,IN_BOUND,Not Discussed,No,No,No,No,No,No,Customer,Yes,No,Yes,No,No,No,No,No,No,Satisfied,50.0,90.0,90.0,No,No,No,No,No

In [9]:

for col in df_merged.columns:
    if 'date' in col or 'month' in col:
        df_merged[col] = pd.to_datetime(df_merged[col])
        print(col)
        print(df_merged[col])

renewal_month
0        2024-11-01
1        2024-11-01
2        2024-11-01
3        2024-11-01
4        2024-11-01
            ...
668003   2023-09-01
668004   2023-08-01
668005   2023-08-01
668006   2023-07-01
668007   2023-07-01
Name: renewal_month, Length: 668008, dtype: datetime64[us]
proforma_date
0        2024-09-06
1        2024-09-06
2        2024-09-06
3        2024-09-06
4        2024-09-06
            ...
668003   2023-07-06
668004   2023-06-07
668005   2023-06-07
668006   2023-05-10
668007   2023-05-10
Name: proforma_date, Length: 668008, dtype: datetime64[us]
registration_date
0        2021-11-05
1        2021-11-05
2        2021-11-05
3        2021-11-05
4        2021-11-05
            ...
668003   2020-09-15
668004   2020-08-03
668005   2020-08-03
668006   2020-07-08
668007   2020-07-08
Name: registration_date, Length: 668008, dtype: datetime64[us]
prospect_renewal_date
0        2024-11-05
1        2024-11-05
2        2024-11-05
3        2024-11-05
4        2024-11-05
            ...
668003   2023-09-15
668004   2023-08-03
668005   2023-08-03
668006   2023-07-08
668007   2023-07-08
Name: prospect_renewal_date, Length: 668008, dtype: datetime64[us]
call_date
0        2026-01-13
1        2025-11-05
2        2025-10-09
3        2025-10-29
4        2024-10-09
            ...
668003   2024-08-23
668004   2024-07-08
668005   2025-07-07
668006   2024-07-02
668007   2025-06-12
Name: call_date, Length: 668008, dtype: datetime64[us]
call_date_cc
0               NaT
1               NaT
2               NaT
3               NaT
4               NaT
            ...
668003          NaT
668004          NaT
668005          NaT
668006   2025-01-08
668007   2025-01-08
Name: call_date_cc, Length: 668008, dtype: datetime64[us]

In [10]:
open_prospects = df_merged[df_merged['prospect_outcome'] == 'Open']

In [11]:
open_prospects['prospect_outcome'].value_counts()

prospect_outcome
Open    37604
Name: count, dtype: int64

In [12]:
df_merged.shape

(668008, 130)

In [13]:
df_filtered = df_merged[
    (
        # Group all date logic together first
        (
            ((df_merged['prospect_renewal_date'] - df_merged['call_date']).dt.days.between(0, 14)) |
            ((df_merged['prospect_renewal_date'] - df_merged['call_date_cc']).dt.days.between(0, 14))
        )
    ) 
    & 
    (df_merged['prospect_outcome'] != 'Open') # Now applies to both date conditions
]

In [14]:
df_filtered.shape

(78325, 130)

In [15]:
print(df_filtered['prospect_outcome'].value_counts())

prospect_outcome
Won        68967
Churned     9358
Name: count, dtype: int64

In [16]:
for col in df_filtered.columns:
    print(df_filtered[col].value_counts(dropna=False))
    print(df_filtered[col].isnull().sum())
    print("-" * 50)

co_ref
AA0994    243
RE6328    102
VU9662     93
GK6414     80
XB6908     78
         ...
MR9914      1
AH3239      1
NS9452      1
IK6353      1
HG7200      1
Name: count, Length: 21206, dtype: int64
0
--------------------------------------------------
renewal_month
2025-02-01    4530
2025-10-01    4279
2025-09-01    4257
2025-01-01    4216
2024-10-01    4128
2024-11-01    4121
2025-11-01    4069
2024-09-01    3880
2024-07-01    3730
2024-05-01    3675
2025-03-01    3614
2024-08-01    3423
2025-07-01    3275
2025-08-01    3208
2024-06-01    3161
2024-12-01    2920
2025-06-01    2902
2024-04-01    2711
2025-05-01    2673
2025-12-01    2548
2026-01-01    2516
2025-04-01    2473
2026-02-01    2016
Name: count, dtype: int64
0
--------------------------------------------------
sustainability_score
8.0    44439
9.5    24068
9.0     9818
Name: count, dtype: int64
0
--------------------------------------------------
total_renewal_score_new
44.0    9954
43.0    7409
45.5    7115
45.0    6731
44.5    6652
43.5    6314
42.0    5026
42.5    3345
41.0    3198
41.5    2544
46.5    2364
32.0    1972
33.0    1883
46.0    1783
34.0    1454
32.5    1439
40.5    1438
40.0    1397
35.0    1125
33.5    1007
34.5     937
31.0     937
39.5     754
31.5     704
39.0     315
38.5     166
36.0     133
35.5      77
30.5      59
36.5      55
38.0      29
37.5       8
37.0       1
Name: count, dtype: int64
0
--------------------------------------------------
last_years_price
599.00     3454
999.00     3427
799.00     2901
949.00     2341
579.00     2242
           ...
702.00        1
813.60        1
833.40        1
1592.10       1
258.75        1
Name: count, Length: 1416, dtype: int64
0
--------------------------------------------------
auto_renewal_score
8    49575
9    28750
Name: count, dtype: int64
0
--------------------------------------------------
status_scores
9    46080
0    11791
8    11577
7     8877
Name: count, dtype: int64
0
--------------------------------------------------
anchoring_score
9.5    28019
8.5    22037
7.5    15370
9.0    12898
8.0        1
Name: count, dtype: int64
0
--------------------------------------------------
tenure_scores
9.5    43387
8.5    13612
9.0    10311
8.0     7623
7.5     3193
7.0      199
Name: count, dtype: int64
0
--------------------------------------------------
proforma_auto_renewal
True     75981
False     2344
Name: count, dtype: int64
0
--------------------------------------------------
proforma_world_pay_token
False    57203
True     21122
Name: count, dtype: int64
0
--------------------------------------------------
proforma_date
2024-03-15    1863
2024-08-09    1712
2024-09-05    1689
2024-03-12    1650
2024-10-10    1624
              ...
2024-09-09       1
2024-08-30       1
2024-08-16       1
2024-10-17       1
2024-04-19       1
Name: count, Length: 98, dtype: int64
0
--------------------------------------------------
current_anchorings
1      22037
0      15371
2      12898
3       8186
4       4663
       ...
102        1
103        1
65         1
84         1
207        1
Name: count, Length: 90, dtype: int64
0
--------------------------------------------------
payment_timeframe
 0      25323
-1       4598
 1       4038
-2       2484
 2       2442
        ...
 142        1
 182        1
 156        1
-362        1
-140        1
Name: count, Length: 228, dtype: int64
0
--------------------------------------------------
registration_date
2019-03-25    689
2017-01-25    256
2020-02-12    136
2024-02-12    127
2011-07-13    119
             ...
2023-05-07      1
2024-06-30      1
2024-06-09      1
2024-10-05      1
2024-12-15      1
Name: count, Length: 4878, dtype: int64
0
--------------------------------------------------
proforma_account_stage
Published          52494
Membership Only    11680
Renewal Process    11625
Vetting             1714
Suspended            812
Name: count, dtype: int64
0
--------------------------------------------------
proforma_audit_status
Accredited                                                  51641
Renewal Questionnaire Received                               4991
Failed- Renewal Questionnaire not received                   4836
Renewal Questionnaire Sent                                   3392
Failed- Renewal Additional Information Not Received          2472
Failed- Initial additional info not received                 2347
Failed- Initial Questionnaire not received                   2026
Initial Questionnaire Received                               1130
1st Renewal questionnaire reminder                            931
Renewal report sent - Awaiting information                    867
Accredited - SSiP due to expire                               839
Final renewal questionnaire reminder                          696
SUSPENDED - SSiP Expired                                      358
1st Reminder - Renewal additional info                        283
Final reminder - Renewal additional info                      278
Report sent - Awaiting information                            261
Renewal additional information received                       186
SUSPENDED - 2nd reminder SSiP Expired                         185
Final Reminder (Initial) Additional Information Not Sent      155
SUSPENDED - 1st reminder SSiP Expired                         136
SSiP Expired - 1st Reminder                                   132
1st reminder initial add info                                 130
Additional information received                                22
Initial - 1st Questionnaire reminder sent                      16
Accred Due to Expire                                           13
Suspended - Insurance Out-of-Date                               1
unknown                                                         1
Name: count, dtype: int64
0
--------------------------------------------------
current_auto_renewal_flag
y    72749
n     5576
Name: count, dtype: int64
0
--------------------------------------------------
current_world_pay_token
n    49571
y    28754
Name: count, dtype: int64
0
--------------------------------------------------
renewal_score_at_release
28.0    16749
27.5     8456
27.0     8350
26.0     7380
24.5     6612
26.5     6605
25.0     5004
23.5     4398
25.5     4119
23.0     3138
24.0     2459
22.0     1689
22.5     1192
21.5     1058
20.5      942
28.2      100
21.0       20
26.7       17
27.7       16
27.2       13
24.7        4
25.2        3
25.7        1
Name: count, dtype: int64
0
--------------------------------------------------
proforma_membership_status
Accredited     56865
Member Only    12493
In Progress     8967
Name: count, dtype: int64
0
--------------------------------------------------
proforma_approved_lists
1      22742
0      14770
2      12574
3       6910
4       4886
       ...
75         1
99         1
100        1
61         1
83         1
Name: count, Length: 90, dtype: int64
0
--------------------------------------------------
tenure_years
1     11275
2      7562
3      6376
5      5516
4      5095
6      5086
7      4386
8      3956
9      3739
10     3505
11     3281
12     2942
13     2384
15     2285
16     2282
14     2192
17     1881
21     1260
18      929
20      910
19      708
22      607
0        94
23       57
24       17
Name: count, dtype: int64
0
--------------------------------------------------
band
Band B     18783
Band C1    15008
Band D     12740
Band C2    10121
Band E      6794
Band F1     5441
Band F2     3164
Band G      2156
Band A      2037
Group        680
Band H       635
Band J       529
Band I       237
Name: count, dtype: int64
0
--------------------------------------------------
prospect_renewal_date
2025-01-25    384
2025-01-31    373
2025-09-30    362
2025-02-12    289
2025-02-05    287
             ...
2024-12-27      3
2026-01-03      2
2025-01-01      2
2024-12-30      2
2026-01-01      2
Name: count, Length: 692, dtype: int64
0
--------------------------------------------------
starting_net
599     5093
799     4197
949     4106
684     3554
999     3358
        ...
5794       1
3814       1
3824       1
3589       1
585        1
Name: count, Length: 696, dtype: int64
0
--------------------------------------------------
starting_vat
119.80    5060
159.80    4172
189.80    4080
136.80    3536
199.80    3331
          ...
764.80       1
717.80       1
117.00       1
1.28         1
1.41         1
Name: count, Length: 695, dtype: int64
0
--------------------------------------------------
starting_gross
718.80     5060
958.80     4172
1138.80    4080
820.80     3536
1198.80    3331
           ...
702.00        1
640.28        1
1789.00       1
705.41        1
3299.00       1
Name: count, Length: 789, dtype: int64
0
--------------------------------------------------
starting_membership_net
500      9586
664      8456
1024     7045
1214     6527
864      5946
         ...
12487       3
4444        3
10427       2
3894        2
4173        2
Name: count, Length: 72, dtype: int64
0
--------------------------------------------------
starting_package_net
0      40913
120    12400
150     5168
85      3763
160     3505
140     3338
105     3146
190     2321
175     1295
100      957
125      783
60       364
225      281
70        87
200        4
Name: count, dtype: int64
0
--------------------------------------------------
starting_pqq_net
135     45409
99      19992
200     10830
250      1384
390       252
460       168
320       149
530        53
600        28
880        22
670         9
1230        7
1790        5
1720        5
810         3
740         3
950         3
0           3
Name: count, dtype: int64
0
--------------------------------------------------
membership_net
500.00     7445
664.00     6845
1024.00    5628
1214.00    5496
864.00     4704
           ...
1929.00       1
475.50        1
909.35        1
1679.00       1
914.00        1
Name: count, Length: 402, dtype: int64
0
--------------------------------------------------
package_net
0.00      44160
120.00    10659
150.00     3942
160.00     3069
85.00      2941
          ...
82.50         2
57.75         2
131.25        1
104.00        1
113.75        1
Name: count, Length: 82, dtype: int64
0
--------------------------------------------------
pqqnet
 135     44580
 99      20617
 200     10740
 250      1400
 390       249
 320       149
 460       130
 530        65
 9          59
 0          43
 600        33
 29         28
 49         27
 880        22
 85         21
-65         17
-35         13
 69         12
-71         10
 45          9
-101         8
-15          8
 670         6
-51          5
 25          5
-31          5
 270         5
 1720        5
-131         4
 65          4
-91          4
 36          4
 150         3
 810         3
 740         3
 950         3
 1860        3
-11          3
-115         3
-50          3
 70          2
-95          2
-36          2
 1790        2
 105         2
 400         2
 30          2
Name: count, dtype: int64
0
--------------------------------------------------
prospect_outcome
Won        68967
Churned     9358
Name: count, dtype: int64
0
--------------------------------------------------
payment_method
Bacs         37722
Card         30354
Unknown       9358
World Pay      848
Cheque          43
Name: count, dtype: int64
0
--------------------------------------------------
total_amount
599.00     4197
799.00     3661
949.00     3187
999.00     2672
684.00     2569
           ...
813.60        1
833.40        1
1592.10       1
1037.85       1
1015.50       1
Name: count, Length: 1283, dtype: int64
0
--------------------------------------------------
tenure_group
4+    53018
1     11369
2      7562
3      6376
Name: count, dtype: int64
0
--------------------------------------------------
last_renewal
2024-02-01    3826
2023-10-01    3600
2024-01-01    3533
2023-11-01    3520
2024-11-01    3475
              ...
2025-06-09       1
2025-10-05       1
2025-11-30       1
2024-08-12       1
2025-12-15       1
Name: count, Length: 558, dtype: int64
0
--------------------------------------------------
last_band
Band B     18881
Band C1    15351
Band D     12542
Band C2    10487
Band E      6437
Band F1     4073
Band F2     2383
Band G      2122
Band A      2086
Band F      1863
Group        708
Band H       637
Band J       406
Band I       349
Name: count, dtype: int64
0
--------------------------------------------------
last_total_net_paid
579.0     3726
999.0     3324
684.0     2870
749.0     2725
949.0     2714
          ...
511.1        1
2004.1       1
2487.0       1
1729.2       1
3299.0       1
Name: count, Length: 821, dtype: int64
0
--------------------------------------------------
last_connections
0      22997
1      18318
2      10390
3       6526
4       4566
       ...
98         1
97         1
84         1
86         1
108        1
Name: count, Length: 95, dtype: int64
0
--------------------------------------------------
anchor_group
1              22742
4 to 9         15080
Independent    14770
2              12574
3               6910
10+             6249
Name: count, dtype: int64
0
--------------------------------------------------
renewal_year
2025    42044
2024    31749
2026     4532
Name: count, dtype: int64
0
--------------------------------------------------
is_first_year
0    66754
1    11571
Name: count, dtype: int64
0
--------------------------------------------------
has_discount
0    65027
1    13298
Name: count, dtype: int64
0
--------------------------------------------------
discount_pct
0.00    65027
0.20     6571
0.30     1977
0.50     1768
0.40     1101
0.10      822
0.15      704
0.35      218
0.25      107
0.45       30
Name: count, dtype: int64
0
--------------------------------------------------
call_id
5.950000e+11    2684
5.110000e+11    2625
5.380000e+11    2389
5.390000e+11    2387
5.940000e+11    2344
5.070000e+11    2239
5.960000e+11    2232
5.910000e+11    2227
5.090000e+11    2182
5.080000e+11    2143
5.650000e+11    2065
5.920000e+11    2025
6.220000e+11    1954
5.100000e+11    1946
5.130000e+11    1875
5.120000e+11    1867
6.830000e+11    1803
5.900000e+11    1794
6.820000e+11    1790
6.850000e+11    1667
6.880000e+11    1664
6.870000e+11    1595
6.790000e+11    1588
5.060000e+11    1530
6.230000e+11    1488
6.930000e+11    1486
6.890000e+11    1472
6.510000e+11    1467
6.940000e+11    1443
5.970000e+11    1434
6.860000e+11    1428
6.800000e+11    1367
6.260000e+11    1340
6.840000e+11    1310
6.770000e+11    1275
6.810000e+11    1260
5.400000e+11    1251
6.920000e+11    1214
6.250000e+11    1191
5.640000e+11    1187
6.780000e+11    1097
6.900000e+11     951
5.050000e+11     856
6.240000e+11     848
6.520000e+11     808
5.930000e+11     797
6.950000e+11     664
5.370000e+11     464
5.660000e+11     395
6.910000e+11     287
1.940000e+11     274
6.760000e+11     272
NaN              240
1.930000e+11     144
Name: count, dtype: int64
240
--------------------------------------------------
call_direction
OUT_BOUND    66821
IN_BOUND     11264
NaN            240
Name: count, dtype: int64
240
--------------------------------------------------
call_date
2025-01-17    353
2024-09-24    331
2024-07-01    328
2025-01-23    327
2025-02-21    313
             ...
2025-07-10     61
2025-03-25     47
2025-12-17     40
2025-12-23     30
2025-12-24      1
Name: count, Length: 466, dtype: int64
240
--------------------------------------------------
membership_renewal_decision
No         44994
Unknown    30248
Yes         2843
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
serious_complaint
No         46186
Unknown    31655
Yes          244
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
other_complaint
No         37439
Unknown    31659
Yes         8987
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
discussion_on_price_increase
No         44561
Unknown    29655
Yes         3869
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
renewal_impact_due_to_price_increase
No         46823
Unknown    29675
Yes         1587
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
discount_or_waiver_requested
No         47005
Unknown    29676
Yes         1404
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
call_reschedule_request
No         47670
Unknown    29379
Yes         1036
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
agent_flagged_membership_status_alert
No         32461
Unknown    29379
Yes        16245
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
agent_renewal_initiation
Unknown    29379
No         25867
Yes        22839
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
explicit_competitor_mention
No         47974
Unknown    29333
Yes          778
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
explicit_switching_intent
No         48732
Unknown    29333
NaN          240
Yes           20
Name: count, dtype: int64
240
--------------------------------------------------
mentioned_competitors
No         45446
Unknown    29334
Yes         3305
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
price_switching_mentioned
No         47381
Unknown    29340
Yes         1364
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
competitor_value_comparison
Not Applicable    46088
Unknown           29352
Not Discussed      1702
Better Value        609
Similar Value       334
NaN                 240
Name: count, dtype: int64
240
--------------------------------------------------
competitor_benefits_mentioned
Not Applicable    35983
Unknown           31236
Not Discussed      8717
Discounts          1271
Better Service      878
NaN                 240
Name: count, dtype: int64
240
--------------------------------------------------
topic_introduced_by
Not Discussed    37279
Unknown          29306
Agent             8692
Customer          2808
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
percentage_price_increase_mentioned
No               48060
Unknown          29306
Yes                382
Not Discussed      337
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
monetary_price_increase_mentioned
No               46742
Unknown          29306
Yes               1700
Not Discussed      337
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
price_range_mentioned
Not Discussed    46802
Unknown          29306
NaN                240
589.0               71
899.0               20
                 ...
766.5                1
932.0                1
634.0                1
521.0                1
7.34                 1
Name: count, Length: 766, dtype: int64
240
--------------------------------------------------
customer_asked_for_justification
No               45561
Unknown          29306
Yes               2881
Not Discussed      337
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
customer_response
Neutral          32742
Unknown          29306
Not Discussed    13057
Negative          2581
Positive           399
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
desire_to_cancel
Unknown              29328
Renewed              24184
Not Discussed        20654
Desired to Cancel     3919
NaN                    240
Name: count, dtype: int64
240
--------------------------------------------------
discount_offered
No               45846
Unknown          29306

17879

--------------------------------------------------
crm_contractor_sentiment_score
 50.0     27170
-1.0      21710
 NaN      17879
 80.0      5039
 20.0      2235
 90.0      1439
 30.0       894
 40.0       742
 0.0        651
 100.0      507
 16.0        18
 98.0        12
 84.0         9
 48.0         5
 55.0         5
 60.0         3
 31.0         3
 25.5         2
 70.0         1
 91.0         1
Name: count, dtype: int64
17879
--------------------------------------------------
crm_dts_or_ssip_mentioned
No               41820
NaN              17879
Yes              13064
Unknown           5561
Not Discussed        1
Name: count, dtype: int64
17879
--------------------------------------------------
crm_customer_payment_intention
Not Discussed    25887
Yes              23151
NaN              17879
No                5847
Unknown           5561
Name: count, dtype: int64
17879
--------------------------------------------------
crm_competitors_mentioned
No               45735
NaN              17879
Not Discussed     9002
Unknown           4224
Yes               1485
Name: count, dtype: int64
17879
--------------------------------------------------
crm_membership_level
Accredited        23834
Not Discussed     19355
NaN               17879
In progress       12522
Unknown            4224
Not Accredited      238
Members only        192
Standard             69
Premier              12
Name: count, dtype: int64
17879
--------------------------------------------------
crm_platform_issues_raised
No               44690
NaN              17879
Not Discussed     8560
Unknown           4224
Yes               2972
Name: count, dtype: int64
17879
--------------------------------------------------
crm_agent_chased_contractor
Yes              39574
NaN              17879
No               16525
Unknown           4224
Not Discussed      123
Name: count, dtype: int64
17879
--------------------------------------------------
crm_agent_chase_count
1.0     24479
NaN     17879
0.0     16643
2.0     14782
3.0      3661
4.0       653
5.0       160
6.0        50
7.0        10
8.0         7
10.0        1
Name: count, dtype: int64
17879
--------------------------------------------------
crm_accreditation_issues
Not Discussed    40911
NaN              17879
Yes               8787
No                6524
Unknown           4224
Name: count, dtype: int64
17879
--------------------------------------------------
crm_membership_overdue
Yes              32200
NaN              17879
Not Discussed    14184
No                9838
Unknown           4224
Name: count, dtype: int64
17879
--------------------------------------------------
crm_auto_renewal_status
0.0    57319
NaN    17879
2.0     2875
1.0      252
Name: count, dtype: int64
17879
--------------------------------------------------
crm_dissatisified_with_renewal_price
Not Discussed    36860
NaN              17879
No               14772
Yes               4590
Unknown           4224
Name: count, dtype: int64
17879
--------------------------------------------------
crm_customer_complained
No         51275
NaN        17879
Yes         4656
Unknown     4515
Name: count, dtype: int64
17879
--------------------------------------------------
crm_refund_mentioned
No         55188
NaN        17879
Unknown     4515
Yes          743
Name: count, dtype: int64
17879
--------------------------------------------------
crm_negative_customer_experience
No               31832
NaN              17879
Not Discussed    13117
Yes              10982
Unknown           4515
Name: count, dtype: int64
17879
--------------------------------------------------
crm_dissatisfaction_with_support
No               32268
Not Discussed    19346
NaN              17879
Unknown           4515
Yes               4317
Name: count, dtype: int64
17879
--------------------------------------------------
crm_financial_hardship_mentioned
Not Discussed    42966
NaN              17879
No                9106
Unknown           4515
Yes               3859
Name: count, dtype: int64
17879
--------------------------------------------------
year
2025.0    45489
NaN       17879
2026.0    14957
Name: count, dtype: int64
17879
--------------------------------------------------
sentiment_score_missing
0.0    38736
1.0    21710
NaN    17879
Name: count, dtype: int64
17879
--------------------------------------------------
contact_id
NaN             30939
6.854460e+11      363
6.914790e+11      317
6.862780e+11      312
6.884230e+11      311
                ...
6.234770e+11        1
6.784020e+11        1
5.645430e+11        1
5.647580e+11        1
5.640710e+11        1
Name: count, Length: 490, dtype: int64
30939
--------------------------------------------------
call_date_cc
NaT           30939
2025-10-20      371
2025-12-09      323
2025-01-23      321
2025-11-24      320
              ...
2024-10-16        2
2024-09-30        2
2024-09-23        2
2024-10-02        1
2024-10-10        1
Name: count, Length: 320, dtype: int64
30939
--------------------------------------------------
direction
OUT_BOUND    35694
NaN          30939
IN_BOUND     11692
Name: count, dtype: int64
30939
--------------------------------------------------
cc_care_package
Not Discussed    37430
NaN              30939
Standard          5175
Express           3561
Premier            733
Unknown            320
Assisted           167
Name: count, dtype: int64
30939
--------------------------------------------------
cc_care_package_discussed
No         37304
NaN        30939
Yes         9863
Unknown      219
Name: count, dtype: int64
30939
--------------------------------------------------
cc_urgency_getting_on_site
No         42240
NaN        30939
Yes         4927
Unknown      219
Name: count, dtype: int64
30939
--------------------------------------------------
cc_external_consultant
No         42453
NaN        30939
Yes         4714
Unknown      219
Name: count, dtype: int64
30939
--------------------------------------------------
cc_agent_cross_sell_attempt
No         45529
NaN        30939
Yes         1607
Unknown      250
Name: count, dtype: int64
30939
--------------------------------------------------
cc_customer_issues_concerns
No         42090
NaN        30939
Yes         5041
Unknown      255
Name: count, dtype: int64
30939
--------------------------------------------------
cc_business_struggles_financial_hardship
No         45527
NaN        30939
Yes         1629
Unknown      230
Name: count, dtype: int64
30939
--------------------------------------------------
cc_call_initiated_by
Customer        32766
NaN             30939
Agent           11803
Not Relevant     2559
Unknown           258
Name: count, dtype: int64
30939
--------------------------------------------------
cc_questionnaire_completion
No         38171
NaN        30939
Yes         9145
Unknown       70
Name: count, dtype: int64
30939
--------------------------------------------------
cc_chasing_response
No         35388
NaN        30939
Yes        11667
Unknown      331
Name: count, dtype: int64
30939
--------------------------------------------------
cc_issues_within_questionnaire
No         39663
NaN        30939
Yes         5821
Unknown     1902
Name: count, dtype: int64
30939
--------------------------------------------------
cc_login_issues
No         44827
NaN        30939
Yes         2472
Unknown       87
Name: count, dtype: int64
30939
--------------------------------------------------
cc_platform_issues
No         43666
NaN        30939
Yes         3640
Unknown       80
Name: count, dtype: int64
30939
--------------------------------------------------
cc_dissatisfaction_time_to_complete
No         45018
NaN        30939
Yes         2292
Unknown       76
Name: count, dtype: int64
30939
--------------------------------------------------
cc_process_complexity_concerns
No         42594
NaN        30939
Yes         4689
Unknown      103
Name: count, dtype: int64
30939
--------------------------------------------------
cc_questions_harder_than_expected
No         47152
NaN        30939
Yes          149
Unknown       85
Name: count, dtype: int64
30939
--------------------------------------------------
cc_dissatisfaction_support
No         46113
NaN        30939
Yes         1191
Unknown       82
Name: count, dtype: int64
30939
--------------------------------------------------
cc_contractor_sentiment
NaN              30939
Satisfied        22368
Neutral          19253
Not Discussed     3949
Dissatisfied      1613
Unknown            203
Name: count, dtype: int64
30939
--------------------------------------------------
cc_contractor_sentiment_start_score
50.0     39151
NaN      30939
80.0      4892
20.0      1543
60.0       789
40.0       774
0.0        175
100.0       25
30.0        18
70.0        14
10.0         5
Name: count, dtype: int64
30939
--------------------------------------------------
cc_contractor_sentiment_end_score
NaN      30939
90.0     18806
80.0     16953
50.0      7875
100.0     1249
60.0       954
70.0       627
0.0        368
40.0       185
20.0       146
95.0       145
30.0        56
10.0        22
Name: count, dtype: int64
30939
--------------------------------------------------
cc_contractor_sentiment_overall_score
NaN      30939
80.0     22637
90.0     14547
85.0      3331
70.0      1975
50.0      1542
60.0       952
100.0      872
40.0       367
55.0       231
95.0       199
65.0       177
20.0       148
0.0        121
30.0       108
75.0        81
92.0        54
10.0        22
45.0        17
25.0         5
Name: count, dtype: int64
30939
--------------------------------------------------
cc_pricing_mentioned
No         41020
NaN        30939
Yes         6166
Unknown      200
Name: count, dtype: int64
30939
--------------------------------------------------
cc_pricing_sentiment_impact
No         45442
NaN        30939
Yes         1781
Unknown      163
Name: count, dtype: int64
30939
--------------------------------------------------
cc_refund_discussed
No         46958
NaN        30939
Yes          285
Unknown      143
Name: count, dtype: int64
30939
--------------------------------------------------
cc_contractor_suggest_leave
No         45727
NaN        30939
Yes         1443
Unknown      216
Name: count, dtype: int64
30939
--------------------------------------------------
cc_contractor_complained
No         43635
NaN        30939
Yes         3548
Unknown      203
Name: count, dtype: int64
30939
--------------------------------------------------

In [17]:
# Columns to remove: identifiers, dates used for filtering, derived scores that may cause leakage, proforma statuses, and other non-beneficial columns
columns_to_drop = [
    'co_ref', 'renewal_month', 'contact_id', 'call_id', 'proforma_date', 'call_date', 'call_date_cc', 
    'registration_date', 'prospect_renewal_date', 'starting_vat', 'starting_gross',
    'proforma_world_pay_token', 'current_world_pay_token', 'proforma_audit_status',
    'proforma_approved_lists', 'proforma_account_stage', 'sentiment_score_missing',
    'year', 'renewal_year', 'direction'
]

df_filtered = df_filtered.drop(columns=columns_to_drop)

In [18]:
num_cols = []

for col in df_filtered.columns:
    if df_filtered[col].dtype in ['int64', 'float64']:
        print(f"Column: {col}")
        num_cols.append(col)
        print(df_filtered[col].value_counts())
        print(f"Null values: {df_filtered[col].isnull().sum()}")
        print("-" * 50)

Column: sustainability_score
sustainability_score
8.0    44439
9.5    24068
9.0     9818
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: total_renewal_score_new
total_renewal_score_new
44.0    9954
43.0    7409
45.5    7115
45.0    6731
44.5    6652
43.5    6314
42.0    5026
42.5    3345
41.0    3198
41.5    2544
46.5    2364
32.0    1972
33.0    1883
46.0    1783
34.0    1454
32.5    1439
40.5    1438
40.0    1397
35.0    1125
33.5    1007
34.5     937
31.0     937
39.5     754
31.5     704
39.0     315
38.5     166
36.0     133
35.5      77
30.5      59
36.5      55
38.0      29
37.5       8
37.0       1
Name: count, dtype: int64

Null values: 0
--------------------------------------------------
Column: last_years_price
last_years_price
599.00     3454
999.00     3427
799.00     2901
949.00     2341
579.00     2242
           ...
702.00        1
813.60        1
833.40        1
1592.10       1
258.75        1
Name: count, Length: 1416, dtype: int64
Null values: 0
--------------------------------------------------
Column: auto_renewal_score
auto_renewal_score
8    49575
9    28750
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: status_scores
status_scores
9    46080
0    11791
8    11577
7     8877
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: anchoring_score
anchoring_score
9.5    28019
8.5    22037
7.5    15370
9.0    12898
8.0        1
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: tenure_scores
tenure_scores
9.5    43387
8.5    13612
9.0    10311
8.0     7623
7.5     3193
7.0      199
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: current_anchorings
current_anchorings
1      22037
0      15371
2      12898
3       8186
4       4663
       ...
102        1
103        1
65         1
84         1
207        1
Name: count, Length: 90, dtype: int64
Null values: 0
--------------------------------------------------
Column: payment_timeframe
payment_timeframe
 0      25323
-1       4598
 1       4038
-2       2484
 2       2442
        ...
 142        1
 182        1
 156        1
-362        1
-140        1
Name: count, Length: 228, dtype: int64
Null values: 0
--------------------------------------------------
Column: renewal_score_at_release
renewal_score_at_release
28.0    16749
27.5     8456
27.0     8350
26.0     7380
24.5     6612
26.5     6605
25.0     5004
23.5     4398
25.5     4119
23.0     3138
24.0     2459
22.0     1689
22.5     1192
21.5     1058
20.5      942
28.2      100
21.0       20
26.7       17
27.7       16
27.2       13
24.7        4
25.2        3
25.7        1
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: tenure_years
tenure_years
1     11275
2      7562
3      6376
5      5516
4      5095
6      5086
7      4386
8      3956
9      3739
10     3505
11     3281
12     2942
13     2384
15     2285
16     2282
14     2192
17     1881
21     1260
18      929
20      910
19      708
22      607
0        94
23       57
24       17
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_net
starting_net
599     5093
799     4197
949     4106
684     3554
999     3358
        ...
5794       1
3814       1
3824       1
3589       1
585        1
Name: count, Length: 696, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_membership_net
starting_membership_net
500      9586
664      8456
1024     7045
1214     6527
864      5946
         ...
12487       3
4444        3
10427       2
3894        2
4173        2
Name: count, Length: 72, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_package_net
starting_package_net
0      40913
120    12400
150     5168
85      3763
160     3505
140     3338
105     3146
190     2321
175     1295
100      957
125      783
60       364
225      281
70        87
200        4
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_pqq_net
starting_pqq_net
135     45409
99      19992
200     10830
250      1384
390       252
460       168
320       149
530        53
600        28
880        22
670         9
1230        7
1790        5
1720        5
810         3
740         3
950         3
0           3
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: membership_net
membership_net
500.00     7445
664.00     6845
1024.00    5628
1214.00    5496
864.00     4704
           ...
1929.00       1
475.50        1
909.35        1
1679.00       1
914.00        1
Name: count, Length: 402, dtype: int64
Null values: 0
--------------------------------------------------
Column: package_net
package_net
0.00      44160
120.00    10659
150.00     3942
160.00     3069
85.00      2941
          ...
82.50         2
57.75         2
131.25        1
104.00        1
113.75        1
Name: count, Length: 82, dtype: int64
Null values: 0
--------------------------------------------------
Column: pqqnet
pqqnet
 135     44580
 99      20617
 200     10740
 250      1400
 390       249
 320       149
 460       130
 530        65
 9          59
 0          43
 600        33
 29         28
 49         27
 880        22
 85         21
-65         17
-35         13
 69         12
-71         10
 45          9
-101         8
-15          8
 670         6
-51          5
 25          5
-31          5
 270         5
 1720        5
-131         4
 65          4
-91          4
 36          4
 150         3
 810         3
 740         3
 950         3
 1860        3
-11          3
-115         3
-50          3
 70          2
-95          2
-36          2
 1790        2
 105         2
 400         2
 30          2
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: total_amount
total_amount
599.00     4197
799.00     3661
949.00     3187
999.00     2672
684.00     2569
           ...
813.60        1
833.40        1
1592.10       1
1037.85       1
1015.50       1
Name: count, Length: 1283, dtype: int64
Null values: 0
--------------------------------------------------
Column: last_total_net_paid
last_total_net_paid
579.0     3726
999.0     3324
684.0     2870
749.0     2725
949.0     2714
          ...
511.1        1
2004.1       1
2487.0       1
1729.2       1
3299.0       1
Name: count, Length: 821, dtype: int64
Null values: 0
--------------------------------------------------
Column: last_connections
last_connections
0      22997
1      18318
2      10390
3       6526
4       4566
       ...
98         1
97         1
84         1
86         1
108        1
Name: count, Length: 95, dtype: int64
Null values: 0
--------------------------------------------------
Column: is_first_year
is_first_year
0    66754
1    11571
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: has_discount
has_discount
0    65027
1    13298
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: discount_pct
discount_pct
0.00    65027
0.20     6571
0.30     1977
0.50     1768
0.40     1101
0.10      822
0.15      704
0.35      218
0.25      107
0.45       30
Name: count, dtype: int64

Null values: 0
--------------------------------------------------
Column: call_number
call_number
2.0     16823
1.0     14241
3.0     13346
4.0      9584
5.0      6490
        ...
58.0        1
42.0        1
51.0        1
49.0        1
54.0        1
Name: count, Length: 61, dtype: int64
Null values: 240
--------------------------------------------------
Column: crm_contractor_sentiment_score
crm_contractor_sentiment_score
 50.0     27170
-1.0      21710
 80.0      5039
 20.0      2235
 90.0      1439
 30.0       894
 40.0       742
 0.0        651
 100.0      507
 16.0        18
 98.0        12
 84.0         9
 48.0         5
 55.0         5
 60.0         3
 31.0         3
 25.5         2
 70.0         1
 91.0         1
Name: count, dtype: int64
Null values: 17879
--------------------------------------------------
Column: crm_agent_chase_count
crm_agent_chase_count
1.0     24479
0.0     16643
2.0     14782
3.0      3661
4.0       653
5.0       160
6.0        50
7.0        10
8.0         7
10.0        1
Name: count, dtype: int64
Null values: 17879
--------------------------------------------------
Column: crm_auto_renewal_status
crm_auto_renewal_status
0.0    57319
2.0     2875
1.0      252
Name: count, dtype: int64
Null values: 17879
--------------------------------------------------
Column: cc_contractor_sentiment_start_score
cc_contractor_sentiment_start_score
50.0     39151
80.0      4892
20.0      1543
60.0       789
40.0       774
0.0        175
100.0       25
30.0        18
70.0        14
10.0         5
Name: count, dtype: int64
Null values: 30939
--------------------------------------------------
Column: cc_contractor_sentiment_end_score
cc_contractor_sentiment_end_score
90.0     18806
80.0     16953
50.0      7875
100.0     1249
60.0       954
70.0       627
0.0        368
40.0       185
20.0       146
95.0       145
30.0        56
10.0        22
Name: count, dtype: int64
Null values: 30939
--------------------------------------------------
Column: cc_contractor_sentiment_overall_score
cc_contractor_sentiment_overall_score
80.0     22637
90.0     14547
85.0      3331
70.0      1975
50.0      1542
60.0       952
100.0      872
40.0       367
55.0       231
95.0       199
65.0       177
20.0       148
0.0        121
30.0       108
75.0        81
92.0        54
10.0        22
45.0        17
25.0         5
Name: count, dtype: int64
Null values: 30939
--------------------------------------------------

In [19]:
def fill_numericals_refined(df, num_cols):
    for col in num_cols:
        if df[col].isnull().sum() > 0:
            
            # 1. Logical Zero Fill: These columns likely mean "None" if NaN
            zero_fill = ['call_number', 'crm_agent_chase_count', 'crm_auto_renewal_status']
            if any(x in col for x in zero_fill):
                df[col] = df[col].fillna(0)
                continue

            # 2. Sentiment Score Logic: Neutral point is 50.0
            # If sentiment is missing, we shouldn't assume perfection (90) or failure (0).
            # Filling with the median is safest for these specific distributions.
            sentiment_cols = ['sentiment_score', 'sentiment_start', 'sentiment_end', 'sentiment_overall']
            if any(x in col for x in sentiment_cols):
                df[col] = df[col].fillna(df[col].median())
                continue

            # 3. General Distribution Logic for any other columns
            skewness = df[col].skew()
            if abs(skewness) > 1:
                df[col] = df[col].fillna(df[col].median())
            else:
                df[col] = df[col].fillna(df[col].mean())

In [20]:
fill_numericals_refined(df_filtered, num_cols)

In [21]:
for col in df_filtered.columns:
    if df_filtered[col].dtype in ['int64', 'float64']:
        print(f"Column: {col}")
        print(df_filtered[col].value_counts())
        print(f"Null values: {df_filtered[col].isnull().sum()}")
        print("-" * 50)

Column: sustainability_score
sustainability_score
8.0    44439
9.5    24068
9.0     9818
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: total_renewal_score_new
total_renewal_score_new
44.0    9954
43.0    7409
45.5    7115
45.0    6731
44.5    6652
43.5    6314
42.0    5026
42.5    3345
41.0    3198
41.5    2544
46.5    2364
32.0    1972
33.0    1883
46.0    1783
34.0    1454
32.5    1439
40.5    1438
40.0    1397
35.0    1125
33.5    1007
34.5     937
31.0     937
39.5     754
31.5     704
39.0     315
38.5     166
36.0     133
35.5      77
30.5      59
36.5      55
38.0      29
37.5       8
37.0       1
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: last_years_price
last_years_price
599.00     3454
999.00     3427
799.00     2901
949.00     2341
579.00     2242
           ...
702.00        1
813.60        1
833.40        1
1592.10       1
258.75        1
Name: count, Length: 1416, dtype: int64
Null values: 0
--------------------------------------------------
Column: auto_renewal_score
auto_renewal_score
8    49575
9    28750
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: status_scores
status_scores
9    46080
0    11791
8    11577
7     8877
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: anchoring_score
anchoring_score
9.5    28019
8.5    22037
7.5    15370
9.0    12898
8.0        1
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: tenure_scores
tenure_scores
9.5    43387
8.5    13612
9.0    10311
8.0     7623
7.5     3193
7.0      199
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: current_anchorings
current_anchorings
1      22037
0      15371
2      12898
3       8186
4       4663
       ...
102        1
103        1
65         1
84         1
207        1
Name: count, Length: 90, dtype: int64
Null values: 0
--------------------------------------------------
Column: payment_timeframe
payment_timeframe
 0      25323
-1       4598
 1       4038
-2       2484
 2       2442
        ...
 142        1
 182        1
 156        1
-362        1
-140        1
Name: count, Length: 228, dtype: int64
Null values: 0
--------------------------------------------------
Column: renewal_score_at_release
renewal_score_at_release
28.0    16749
27.5     8456
27.0     8350
26.0     7380
24.5     6612
26.5     6605
25.0     5004
23.5     4398
25.5     4119
23.0     3138
24.0     2459
22.0     1689
22.5     1192
21.5     1058
20.5      942
28.2      100
21.0       20
26.7       17
27.7       16
27.2       13
24.7        4
25.2        3
25.7        1
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: tenure_years
tenure_years
1     11275
2      7562
3      6376
5      5516
4      5095
6      5086
7      4386
8      3956
9      3739
10     3505
11     3281
12     2942
13     2384
15     2285
16     2282
14     2192
17     1881
21     1260
18      929
20      910
19      708
22      607
0        94
23       57
24       17
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_net
starting_net
599     5093
799     4197
949     4106
684     3554
999     3358
        ...
5794       1
3814       1
3824       1
3589       1
585        1
Name: count, Length: 696, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_membership_net
starting_membership_net
500      9586
664      8456
1024     7045
1214     6527
864      5946
         ...
12487       3
4444        3
10427       2
3894        2
4173        2
Name: count, Length: 72, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_package_net
starting_package_net
0      40913
120    12400
150     5168
85      3763
160     3505
140     3338
105     3146
190     2321
175     1295
100      957
125      783
60       364
225      281
70        87
200        4
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: starting_pqq_net
starting_pqq_net
135     45409
99      19992
200     10830
250      1384
390       252
460       168
320       149
530        53
600        28
880        22
670         9
1230        7
1790        5
1720        5
810         3
740         3
950         3
0           3
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: membership_net
membership_net
500.00     7445
664.00     6845
1024.00    5628
1214.00    5496
864.00     4704
           ...
1929.00       1
475.50        1
909.35        1
1679.00       1
914.00        1
Name: count, Length: 402, dtype: int64
Null values: 0
--------------------------------------------------
Column: package_net
package_net
0.00      44160
120.00    10659
150.00     3942
160.00     3069
85.00      2941
          ...
82.50         2
57.75         2
131.25        1
104.00        1
113.75        1
Name: count, Length: 82, dtype: int64
Null values: 0
--------------------------------------------------
Column: pqqnet
pqqnet
 135     44580
 99      20617
 200     10740
 250      1400
 390       249
 320       149
 460       130
 530        65
 9          59
 0          43
 600        33
 29         28
 49         27
 880        22
 85         21
-65         17
-35         13
 69         12
-71         10
 45          9
-101         8
-15          8
 670         6
-51          5
 25          5
-31          5
 270         5
 1720        5
-131         4
 65          4
-91          4
 36          4
 150         3
 810         3
 740         3
 950         3
 1860        3
-11          3
-115         3
-50          3
 70          2
-95          2
-36          2
 1790        2
 105         2
 400         2
 30          2
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: total_amount
total_amount
599.00     4197
799.00     3661
949.00     3187
999.00     2672
684.00     2569
           ...
813.60        1
833.40        1
1592.10       1
1037.85       1
1015.50       1
Name: count, Length: 1283, dtype: int64
Null values: 0
--------------------------------------------------
Column: last_total_net_paid
last_total_net_paid
579.0     3726
999.0     3324
684.0     2870
749.0     2725
949.0     2714
          ...
511.1        1
2004.1       1
2487.0       1
1729.2       1
3299.0       1
Name: count, Length: 821, dtype: int64
Null values: 0
--------------------------------------------------
Column: last_connections
last_connections
0      22997
1      18318
2      10390
3       6526
4       4566
       ...
98         1
97         1
84         1
86         1
108        1
Name: count, Length: 95, dtype: int64
Null values: 0
--------------------------------------------------
Column: is_first_year
is_first_year
0    66754
1    11571
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: has_discount
has_discount
0    65027
1    13298
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: discount_pct
discount_pct
0.00    65027
0.20     6571
0.30     1977
0.50     1768
0.40     1101
0.10      822
0.15      704
0.35      218
0.25      107
0.45       30
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: call_number
call_number
2.0     16823
1.0     14241
3.0     13346
4.0      9584
5.0      6490
        ...
58.0        1
42.0        1
51.0        1
49.0        1
54.0        1
Name: count, Length: 62, dtype: int64
Null values: 0
--------------------------------------------------
Column: crm_contractor_sentiment_score
crm_contractor_sentiment_score
 50.0     45049
-1.0      21710
 80.0      5039
 20.0      2235
 90.0      1439
 30.0       894
 40.0       742
 0.0        651
 100.0      507
 16.0        18
 98.0        12
 84.0         9
 48.0         5
 55.0         5
 60.0         3
 31.0         3
 25.5         2
 70.0         1
 91.0         1
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: crm_agent_chase_count
crm_agent_chase_count
0.0     34522
1.0     24479
2.0     14782
3.0      3661
4.0       653
5.0       160
6.0        50
7.0        10
8.0         7
10.0        1
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: crm_auto_renewal_status
crm_auto_renewal_status
0.0    75198
2.0     2875
1.0      252
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: cc_contractor_sentiment_start_score
cc_contractor_sentiment_start_score
50.0     70090
80.0      4892
20.0      1543
60.0       789
40.0       774
0.0        175
100.0       25
30.0        18
70.0        14
10.0         5
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: cc_contractor_sentiment_end_score
cc_contractor_sentiment_end_score
80.0     47892
90.0     18806
50.0      7875
100.0     1249
60.0       954
70.0       627
0.0        368
40.0       185
20.0       146
95.0       145
30.0        56
10.0        22
Name: count, dtype: int64
Null values: 0
--------------------------------------------------
Column: cc_contractor_sentiment_overall_score
cc_contractor_sentiment_overall_score
80.0     53576
90.0     14547
85.0      3331
70.0      1975
50.0      1542
60.0       952
100.0      872
40.0       367
55.0       231
95.0       199
65.0       177
20.0       148
0.0        121
30.0       108
75.0        81
92.0        54
10.0        22
45.0        17
25.0         5
Name: count, dtype: int64
Null values: 0
--------------------------------------------------

In [22]:
df_filtered = df_filtered.fillna('Unknown')

In [23]:
df_filtered.shape

(78325, 110)

In [24]:
for col in df_filtered.columns:
    print(df_filtered[col].value_counts(dropna=False))
    print(df_filtered[col].isnull().sum())
    print("-" * 50)

sustainability_score
8.0    44439
9.5    24068
9.0     9818
Name: count, dtype: int64
0
--------------------------------------------------
total_renewal_score_new
44.0    9954
43.0    7409
45.5    7115
45.0    6731
44.5    6652
43.5    6314
42.0    5026
42.5    3345
41.0    3198
41.5    2544
46.5    2364
32.0    1972
33.0    1883
46.0    1783
34.0    1454
32.5    1439
40.5    1438
40.0    1397
35.0    1125
33.5    1007
34.5     937
31.0     937
39.5     754
31.5     704
39.0     315
38.5     166
36.0     133
35.5      77
30.5      59
36.5      55
38.0      29
37.5       8
37.0       1
Name: count, dtype: int64
0
--------------------------------------------------
last_years_price
599.00     3454
999.00     3427
799.00     2901
949.00     2341
579.00     2242
           ...
702.00        1
813.60        1
833.40        1
1592.10       1
258.75        1
Name: count, Length: 1416, dtype: int64
0
--------------------------------------------------
auto_renewal_score
8    49575
9    28750
Name: count, dtype: int64
0
--------------------------------------------------
status_scores
9    46080
0    11791
8    11577
7     8877
Name: count, dtype: int64
0
--------------------------------------------------
anchoring_score
9.5    28019
8.5    22037
7.5    15370
9.0    12898
8.0        1
Name: count, dtype: int64
0
--------------------------------------------------
tenure_scores
9.5    43387
8.5    13612
9.0    10311
8.0     7623
7.5     3193
7.0      199
Name: count, dtype: int64
0
--------------------------------------------------
proforma_auto_renewal
True     75981
False     2344
Name: count, dtype: int64
0
--------------------------------------------------
current_anchorings
1      22037
0      15371
2      12898
3       8186
4       4663
       ...
102        1
103        1
65         1
84         1
207        1
Name: count, Length: 90, dtype: int64
0
--------------------------------------------------
payment_timeframe
 0      25323
-1       4598
 1       4038
-2       2484
 2       2442
        ...
 142        1
 182        1
 156        1
-362        1
-140        1
Name: count, Length: 228, dtype: int64
0
--------------------------------------------------
current_auto_renewal_flag
y    72749
n     5576
Name: count, dtype: int64
0
--------------------------------------------------
renewal_score_at_release
28.0    16749
27.5     8456
27.0     8350
26.0     7380
24.5     6612
26.5     6605
25.0     5004
23.5     4398
25.5     4119
23.0     3138
24.0     2459
22.0     1689
22.5     1192
21.5     1058
20.5      942
28.2      100
21.0       20
26.7       17
27.7       16
27.2       13
24.7        4
25.2        3
25.7        1
Name: count, dtype: int64
0
--------------------------------------------------
proforma_membership_status
Accredited     56865
Member Only    12493
In Progress     8967
Name: count, dtype: int64
0
--------------------------------------------------
tenure_years
1     11275
2      7562
3      6376
5      5516
4      5095
6      5086
7      4386
8      3956
9      3739
10     3505
11     3281
12     2942
13     2384
15     2285
16     2282
14     2192
17     1881
21     1260
18      929
20      910
19      708
22      607
0        94
23       57
24       17
Name: count, dtype: int64
0
--------------------------------------------------
band
Band B     18783
Band C1    15008
Band D     12740
Band C2    10121
Band E      6794
Band F1     5441
Band F2     3164
Band G      2156
Band A      2037
Group        680
Band H       635
Band J       529
Band I       237
Name: count, dtype: int64
0
--------------------------------------------------
starting_net
599     5093
799     4197
949     4106
684     3554
999     3358
        ...
5794       1
3814       1
3824       1
3589       1
585        1
Name: count, Length: 696, dtype: int64
0
--------------------------------------------------
starting_membership_net
500      9586
664      8456
1024     7045
1214     6527
864      5946
         ...
12487       3
4444        3
10427       2
3894        2
4173        2
Name: count, Length: 72, dtype: int64
0
--------------------------------------------------
starting_package_net
0      40913
120    12400
150     5168
85      3763
160     3505
140     3338
105     3146
190     2321
175     1295
100      957
125      783
60       364
225      281
70        87
200        4
Name: count, dtype: int64
0
--------------------------------------------------
starting_pqq_net
135     45409
99      19992
200     10830
250      1384
390       252
460       168
320       149
530        53
600        28
880        22
670         9
1230        7
1790        5
1720        5
810         3
740         3
950         3
0           3
Name: count, dtype: int64
0
--------------------------------------------------
membership_net
500.00     7445
664.00     6845
1024.00    5628
1214.00    5496
864.00     4704
           ...
1929.00       1
475.50        1
909.35        1
1679.00       1
914.00        1
Name: count, Length: 402, dtype: int64
0
--------------------------------------------------
package_net
0.00      44160
120.00    10659
150.00     3942
160.00     3069
85.00      2941
          ...
82.50         2
57.75         2
131.25        1
104.00        1
113.75        1
Name: count, Length: 82, dtype: int64
0
--------------------------------------------------
pqqnet
 135     44580
 99      20617
 200     10740
 250      1400
 390       249
 320       149
 460       130
 530        65
 9          59
 0          43
 600        33
 29         28
 49         27
 880        22
 85         21
-65         17
-35         13
 69         12
-71         10
 45          9
-101         8
-15          8
 670         6
-51          5
 25          5
-31          5
 270         5
 1720        5
-131         4
 65          4
-91          4
 36          4
 150         3
 810         3
 740         3
 950         3
 1860        3
-11          3
-115         3
-50          3
 70          2
-95          2
-36          2
 1790        2
 105         2
 400         2
 30          2
Name: count, dtype: int64
0
--------------------------------------------------
prospect_outcome
Won        68967
Churned     9358
Name: count, dtype: int64
0
--------------------------------------------------
payment_method
Bacs         37722
Card         30354
Unknown       9358
World Pay      848
Cheque          43
Name: count, dtype: int64
0
--------------------------------------------------
total_amount
599.00     4197
799.00     3661
949.00     3187
999.00     2672
684.00     2569
           ...
813.60        1
833.40        1
1592.10       1
1037.85       1
1015.50       1
Name: count, Length: 1283, dtype: int64
0
--------------------------------------------------
tenure_group
4+    53018
1     11369
2      7562
3      6376
Name: count, dtype: int64
0
--------------------------------------------------
last_renewal
2024-02-01    3826
2023-10-01    3600
2024-01-01    3533
2023-11-01    3520
2024-11-01    3475
              ...
2025-06-09       1
2025-10-05       1
2025-11-30       1
2024-08-12       1
2025-12-15       1
Name: count, Length: 558, dtype: int64
0
--------------------------------------------------
last_band
Band B     18881
Band C1    15351
Band D     12542
Band C2    10487
Band E      6437
Band F1     4073
Band F2     2383
Band G      2122
Band A      2086
Band F      1863
Group        708
Band H       637
Band J       406
Band I       349
Name: count, dtype: int64
0
--------------------------------------------------
last_total_net_paid
579.0     3726
999.0     3324
684.0     2870
749.0     2725
949.0     2714
          ...
511.1        1
2004.1       1
2487.0       1
1729.2       1
3299.0       1
Name: count, Length: 821, dtype: int64
0
--------------------------------------------------
last_connections
0      22997
1      18318
2      10390
3       6526
4       4566
       ...
98         1
97         1
84         1
86         1
108        1
Name: count, Length: 95, dtype: int64
0
--------------------------------------------------
anchor_group
1              22742
4 to 9         15080
Independent    14770
2              12574
3               6910
10+             6249
Name: count, dtype: int64
0
--------------------------------------------------
is_first_year
0    66754
1    11571
Name: count, dtype: int64
0
--------------------------------------------------
has_discount
0    65027
1    13298
Name: count, dtype: int64
0
--------------------------------------------------
discount_pct
0.00    65027
0.20     6571
0.30     1977
0.50     1768
0.40     1101
0.10      822
0.15      704
0.35      218
0.25      107
0.45       30
Name: count, dtype: int64
0
--------------------------------------------------
call_direction
OUT_BOUND    66821
IN_BOUND     11264
Unknown        240
Name: count, dtype: int64
0
--------------------------------------------------
membership_renewal_decision
No         44994
Unknown    30488
Yes         2843
Name: count, dtype: int64
0
--------------------------------------------------
serious_complaint
No         46186
Unknown    31895
Yes          244
Name: count, dtype: int64
0
--------------------------------------------------
other_complaint
No         37439
Unknown    31899
Yes         8987
Name: count, dtype: int64
0
--------------------------------------------------
discussion_on_price_increase
No         44561
Unknown    29895
Yes         3869
Name: count, dtype: int64
0
--------------------------------------------------
renewal_impact_due_to_price_increase
No         46823
Unknown    29915
Yes         1587
Name: count, dtype: int64
0
--------------------------------------------------
discount_or_waiver_requested
No         47005
Unknown    29916
Yes         1404
Name: count, dtype: int64
0
--------------------------------------------------
call_reschedule_request
No         47670
Unknown    29619
Yes         1036
Name: count, dtype: int64
0
--------------------------------------------------
agent_flagged_membership_status_alert
No         32461
Unknown    29619
Yes        16245
Name: count, dtype: int64
0
--------------------------------------------------
agent_renewal_initiation
Unknown    29619
No         25867
Yes        22839
Name: count, dtype: int64
0
--------------------------------------------------
explicit_competitor_mention
No         47974
Unknown    29573
Yes          778
Name: count, dtype: int64
0
--------------------------------------------------
explicit_switching_intent
No         48732
Unknown    29573
Yes           20
Name: count, dtype: int64
0
--------------------------------------------------
mentioned_competitors
No         45446
Unknown    29574
Yes         3305
Name: count, dtype: int64
0
--------------------------------------------------
price_switching_mentioned
No         47381
Unknown    29580
Yes         1364
Name: count, dtype: int64
0
--------------------------------------------------
competitor_value_comparison
Not Applicable    46088
Unknown           29592
Not Discussed      1702
Better Value        609
Similar Value       334
Name: count, dtype: int64
0
--------------------------------------------------
competitor_benefits_mentioned
Not Applicable    35983
Unknown           31476
Not Discussed      8717
Discounts          1271
Better Service      878
Name: count, dtype: int64
0
--------------------------------------------------
topic_introduced_by
Not Discussed    37279
Unknown          29546
Agent             8692
Customer          2808
Name: count, dtype: int64
0
--------------------------------------------------
percentage_price_increase_mentioned
No               48060
Unknown          29546
Yes                382
Not Discussed      337
Name: count, dtype: int64
0
--------------------------------------------------
monetary_price_increase_mentioned
No               46742
Unknown          29546
Yes               1700
Not Discussed      337
Name: count, dtype: int64
0
--------------------------------------------------
price_range_mentioned
Not Discussed    46802
Unknown          29546
589.0               71
899.0               20
140.0               20
                 ...
766.5                1
932.0                1
634.0                1
521.0                1
7.34                 1
Name: count, Length: 765, dtype: int64
0
--------------------------------------------------
customer_asked_for_justification
No               45561
Unknown          29546
Yes               2881
Not Discussed      337
Name: count, dtype: int64
0
--------------------------------------------------
customer_response
Neutral          32742
Unknown          29546
Not Discussed    13057
Negative          2581
Positive           399
Name: count, dtype: int64
0
--------------------------------------------------
desire_to_cancel
Unknown              29568
Renewed              24184
Not Discussed        20654
Desired to Cancel     3919
Name: count, dtype: int64
0
--------------------------------------------------
discount_offered
No               45846
Unknown          29546
Yes               2596
Not Discussed      337
Name: count, dtype: int64

0
--------------------------------------------------
call_number
2.0     16823
1.0     14241
3.0     13346
4.0      9584
5.0      6490
        ...
58.0        1
42.0        1
51.0        1
49.0        1
54.0        1
Name: count, Length: 62, dtype: int64
0
--------------------------------------------------
time_to_renewal
pre_renewal    60446
Unknown        17879
Name: count, dtype: int64
0
--------------------------------------------------
crm_accreditation_completed
Not Discussed    31469
Unknown          23440
No               16443
Yes               6973
Name: count, dtype: int64
0
--------------------------------------------------
crm_timely_completion
Not Discussed    48628
Unknown          23440
No                4679
Yes               1578
Name: count, dtype: int64
0
--------------------------------------------------
crm_progress_towards_accreditation
Not Discussed    40655
Unknown          23440
Yes              12793
No                1437
Name: count, dtype: int64
0
--------------------------------------------------
crm_delays_in_accreditation
No               41607
Unknown          23440
Yes              12752
Not Discussed      526
Name: count, dtype: int64
0
--------------------------------------------------
crm_contractor_suggested_leave
No               42415
Unknown          23440
Yes               7111
Not Discussed     5359
Name: count, dtype: int64
0
--------------------------------------------------
crm_contractor_engagement
Yes        38705
Unknown    23440
No         16180
Name: count, dtype: int64
0
--------------------------------------------------
crm_contractor_sentiment
Unknown         39587
neutral         27199
satisfied        6991
dissatisfied     4548
Name: count, dtype: int64
0
--------------------------------------------------
crm_contractor_sentiment_score
 50.0     45049
-1.0      21710
 80.0      5039
 20.0      2235
 90.0      1439
 30.0       894
 40.0       742
 0.0        651
 100.0      507
 16.0        18
 98.0        12
 84.0         9
 48.0         5
 55.0         5
 60.0         3
 31.0         3
 25.5         2
 70.0         1
 91.0         1
Name: count, dtype: int64
0
--------------------------------------------------
crm_dts_or_ssip_mentioned
No               41820
Unknown          23440
Yes              13064
Not Discussed        1
Name: count, dtype: int64
0
--------------------------------------------------
crm_customer_payment_intention
Not Discussed    25887
Unknown          23440
Yes              23151
No                5847
Name: count, dtype: int64
0
--------------------------------------------------
crm_competitors_mentioned
No               45735
Unknown          22103
Not Discussed     9002
Yes               1485
Name: count, dtype: int64
0
--------------------------------------------------
crm_membership_level
Accredited        23834
Unknown           22103
Not Discussed     19355
In progress       12522
Not Accredited      238
Members only        192
Standard             69
Premier              12
Name: count, dtype: int64
0
--------------------------------------------------
crm_platform_issues_raised
No               44690
Unknown          22103
Not Discussed     8560
Yes               2972
Name: count, dtype: int64
0
--------------------------------------------------
crm_agent_chased_contractor
Yes              39574
Unknown          22103
No               16525
Not Discussed      123
Name: count, dtype: int64
0
--------------------------------------------------
crm_agent_chase_count
0.0     34522
1.0     24479
2.0     14782
3.0      3661
4.0       653
5.0       160
6.0        50
7.0        10
8.0         7
10.0        1
Name: count, dtype: int64
0
--------------------------------------------------
crm_accreditation_issues
Not Discussed    40911
Unknown          22103
Yes               8787
No                6524
Name: count, dtype: int64
0
--------------------------------------------------
crm_membership_overdue
Yes              32200
Unknown          22103
Not Discussed    14184
No                9838
Name: count, dtype: int64
0
--------------------------------------------------
crm_auto_renewal_status
0.0    75198
2.0     2875
1.0      252
Name: count, dtype: int64
0
--------------------------------------------------
crm_dissatisified_with_renewal_price
Not Discussed    36860
Unknown          22103
No               14772
Yes               4590
Name: count, dtype: int64
0
--------------------------------------------------
crm_customer_complained
No         51275
Unknown    22394
Yes         4656
Name: count, dtype: int64
0
--------------------------------------------------
crm_refund_mentioned
No         55188
Unknown    22394
Yes          743
Name: count, dtype: int64
0
--------------------------------------------------
crm_negative_customer_experience
No               31832
Unknown          22394
Not Discussed    13117
Yes              10982
Name: count, dtype: int64
0
--------------------------------------------------
crm_dissatisfaction_with_support
No               32268
Unknown          22394
Not Discussed    19346
Yes               4317
Name: count, dtype: int64
0
--------------------------------------------------
crm_financial_hardship_mentioned
Not Discussed    42966
Unknown          22394
No                9106
Yes               3859
Name: count, dtype: int64
0
--------------------------------------------------
cc_care_package
Not Discussed    37430
Unknown          31259
Standard          5175
Express           3561
Premier            733
Assisted           167
Name: count, dtype: int64
0
--------------------------------------------------
cc_care_package_discussed
No         37304
Unknown    31158
Yes         9863
Name: count, dtype: int64
0
--------------------------------------------------
cc_urgency_getting_on_site
No         42240
Unknown    31158
Yes         4927
Name: count, dtype: int64
0
--------------------------------------------------
cc_external_consultant
No         42453
Unknown    31158
Yes         4714
Name: count, dtype: int64
0
--------------------------------------------------
cc_agent_cross_sell_attempt
No         45529
Unknown    31189
Yes         1607
Name: count, dtype: int64
0
--------------------------------------------------
cc_customer_issues_concerns
No         42090
Unknown    31194
Yes         5041
Name: count, dtype: int64
0
--------------------------------------------------
cc_business_struggles_financial_hardship
No         45527
Unknown    31169
Yes         1629
Name: count, dtype: int64
0
--------------------------------------------------
cc_call_initiated_by
Customer        32766
Unknown         31197
Agent           11803
Not Relevant     2559
Name: count, dtype: int64
0
--------------------------------------------------
cc_questionnaire_completion
No         38171
Unknown    31009
Yes         9145
Name: count, dtype: int64
0
--------------------------------------------------
cc_chasing_response
No         35388
Unknown    31270
Yes        11667
Name: count, dtype: int64
0
--------------------------------------------------
cc_issues_within_questionnaire
No         39663
Unknown    32841
Yes         5821
Name: count, dtype: int64
0
--------------------------------------------------
cc_login_issues
No         44827
Unknown    31026
Yes         2472
Name: count, dtype: int64
0
--------------------------------------------------
cc_platform_issues
No         43666
Unknown    31019
Yes         3640
Name: count, dtype: int64
0
--------------------------------------------------
cc_dissatisfaction_time_to_complete
No         45018
Unknown    31015
Yes         2292
Name: count, dtype: int64
0
--------------------------------------------------
cc_process_complexity_concerns
No         42594
Unknown    31042
Yes         4689
Name: count, dtype: int64
0
--------------------------------------------------
cc_questions_harder_than_expected
No         47152
Unknown    31024
Yes          149
Name: count, dtype: int64
0
--------------------------------------------------
cc_dissatisfaction_support
No         46113
Unknown    31021
Yes         1191
Name: count, dtype: int64
0
--------------------------------------------------
cc_contractor_sentiment
Unknown          31142
Satisfied        22368
Neutral          19253
Not Discussed     3949
Dissatisfied      1613
Name: count, dtype: int64
0
--------------------------------------------------
cc_contractor_sentiment_start_score
50.0     70090
80.0      4892
20.0      1543
60.0       789
40.0       774
0.0        175
100.0       25
30.0        18
70.0        14
10.0         5
Name: count, dtype: int64
0
--------------------------------------------------
cc_contractor_sentiment_end_score
80.0     47892
90.0     18806
50.0      7875
100.0     1249
60.0       954
70.0       627
0.0        368
40.0       185
20.0       146
95.0       145
30.0        56
10.0        22
Name: count, dtype: int64
0
--------------------------------------------------
cc_contractor_sentiment_overall_score
80.0     53576
90.0     14547
85.0      3331
70.0      1975
50.0      1542
60.0       952
100.0      872
40.0       367
55.0       231
95.0       199
65.0       177
20.0       148
0.0        121
30.0       108
75.0        81
92.0        54
10.0        22
45.0        17
25.0         5
Name: count, dtype: int64
0
--------------------------------------------------
cc_pricing_mentioned
No         41020
Unknown    31139
Yes         6166
Name: count, dtype: int64
0
--------------------------------------------------
cc_pricing_sentiment_impact
No         45442
Unknown    31102
Yes         1781
Name: count, dtype: int64
0
--------------------------------------------------
cc_refund_discussed
No         46958
Unknown    31082
Yes          285
Name: count, dtype: int64
0
--------------------------------------------------
cc_contractor_suggest_leave
No         45727
Unknown    31155
Yes         1443
Name: count, dtype: int64
0
--------------------------------------------------
cc_contractor_complained
No         43635
Unknown    31142
Yes         3548
Name: count, dtype: int64
0
--------------------------------------------------

In [25]:
for col in df_filtered.columns:
    print(col)

sustainability_score
total_renewal_score_new
last_years_price
auto_renewal_score
status_scores
anchoring_score
tenure_scores
proforma_auto_renewal
current_anchorings
payment_timeframe
current_auto_renewal_flag
renewal_score_at_release
proforma_membership_status
tenure_years
band
starting_net
starting_membership_net
starting_package_net
starting_pqq_net
membership_net
package_net
pqqnet
prospect_outcome
payment_method
total_amount
tenure_group
last_renewal
last_band
last_total_net_paid
last_connections
anchor_group
is_first_year
has_discount
discount_pct
call_direction
membership_renewal_decision
serious_complaint
other_complaint
discussion_on_price_increase
renewal_impact_due_to_price_increase
discount_or_waiver_requested
call_reschedule_request
agent_flagged_membership_status_alert
agent_renewal_initiation
explicit_competitor_mention
explicit_switching_intent
mentioned_competitors
price_switching_mentioned
competitor_value_comparison
competitor_benefits_mentioned
topic_introduced_by
percentage_price_increase_mentioned
monetary_price_increase_mentioned
price_range_mentioned
customer_asked_for_justification
customer_response
desire_to_cancel
discount_offered
call_number
time_to_renewal
crm_accreditation_completed
crm_timely_completion
crm_progress_towards_accreditation
crm_delays_in_accreditation
crm_contractor_suggested_leave
crm_contractor_engagement
crm_contractor_sentiment
crm_contractor_sentiment_score
crm_dts_or_ssip_mentioned
crm_customer_payment_intention
crm_competitors_mentioned
crm_membership_level
crm_platform_issues_raised
crm_agent_chased_contractor
crm_agent_chase_count
crm_accreditation_issues
crm_membership_overdue
crm_auto_renewal_status
crm_dissatisified_with_renewal_price
crm_customer_complained
crm_refund_mentioned
crm_negative_customer_experience
crm_dissatisfaction_with_support
crm_financial_hardship_mentioned
cc_care_package
cc_care_package_discussed
cc_urgency_getting_on_site
cc_external_consultant
cc_agent_cross_sell_attempt
cc_customer_issues_concerns
cc_business_struggles_financial_hardship
cc_call_initiated_by
cc_questionnaire_completion
cc_chasing_response
cc_issues_within_questionnaire
cc_login_issues
cc_platform_issues
cc_dissatisfaction_time_to_complete
cc_process_complexity_concerns
cc_questions_harder_than_expected
cc_dissatisfaction_support
cc_contractor_sentiment
cc_contractor_sentiment_start_score
cc_contractor_sentiment_end_score
cc_contractor_sentiment_overall_score
cc_pricing_mentioned
cc_pricing_sentiment_impact
cc_refund_discussed
cc_contractor_suggest_leave
cc_contractor_complained

In [26]:
df_filtered.info()

<class 'pandas.DataFrame'>
Index: 78325 entries, 6 to 665981
Columns: 110 entries, sustainability_score to cc_contractor_complained
dtypes: bool(1), float64(18), int64(13), str(78)
memory usage: 65.8 MB

In [27]:
df_filtered.head()

,sustainability_score,total_renewal_score_new,last_years_price,auto_renewal_score,status_scores,anchoring_score,tenure_scores,proforma_auto_renewal,current_anchorings,payment_timeframe,current_auto_renewal_flag,renewal_score_at_release,proforma_membership_status,tenure_years,band,starting_net,starting_membership_net,starting_package_net,starting_pqq_net,membership_net,package_net,pqqnet,prospect_outcome,payment_method,total_amount,tenure_group,last_renewal,last_band,last_total_net_paid,last_connections,anchor_group,is_first_year,has_discount,discount_pct,call_direction,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,call_number,time_to_renewal,crm_accreditation_completed,crm_timely_completion,crm_progress_towards_accreditation,crm_delays_in_accreditation,crm_contractor_suggested_leave,crm_contractor_engagement,crm_contractor_sentiment,crm_contractor_sentiment_score,crm_dts_or_ssip_mentioned,crm_customer_payment_intention,crm_competitors_mentioned,crm_membership_level,crm_platform_issues_raised,crm_agent_chased_contractor,crm_agent_chase_count,crm_accreditation_issues,crm_membership_overdue,crm_auto_renewal_status,crm_dissatisified_with_renewal_price,crm_customer_complained,crm_refund_mentioned,crm_negative_customer_experience,crm_dissatisfaction_with_support,crm_financial_hardship_mentioned,cc_care_package,cc_care_package_discussed,cc_urgency_getting_on_site,cc_external_consultant,cc_agent_cross_sell_attempt,cc_customer_issues_concerns,cc_business_struggles_financial_hardship,cc_call_initiated_by,cc_questionnaire_completion,cc_chasing_response,cc_issues_within_questionnaire,cc_login_issues,cc_platform_issues,cc_dissatisfaction_time_to_complete,cc_process_complexity_concerns,cc_questions_harder_than_expected,cc_dissatisfaction_support,cc_contractor_sentiment,cc_contractor_sentiment_start_score,cc_contractor_sentiment_end_score,cc_contractor_sentiment_overall_score,cc_pricing_mentioned,cc_pricing_sentiment_impact,cc_refund_discussed,cc_contractor_suggest_leave,cc_contractor_complained
6,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,y,24.5,Accredited,1,Band C1,919,664,120,135,664.0,0.0,135,Won,Card,799.0,1,2025-08-09,Band C1,919.0,0,1,1,0,0.0,OUT_BOUND,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Not Applicable,Not Discussed,No,No,Not Discussed,No,Neutral,Renewed,No,1.0,pre_renewal,No,Not Discussed,Yes,No,No,Yes,neutral,50.0,No,Not Discussed,No,Accredited,No,Yes,1.0,No,Yes,0.0,Yes,No,No,No,No,Not Discussed,Express,Yes,No,No,No,No,No,Agent,No,No,No,No,No,No,No,No,No,Satisfied,50.0,90.0,85.0,Yes,Yes,No,No,No
8,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,y,24.5,Accredited,1,Band C1,919,664,120,135,664.0,0.0,135,Won,Card,799.0,1,2025-08-09,Band C1,919.0,0,1,1,0,0.0,OUT_BOUND,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2.0,pre_renewal,No,Not Discussed,Yes,No,No,Yes,neutral,50.0,No,Not Discussed,No,Accredited,No,Yes,1.0,No,Yes,0.0,Yes,No,No,No,No,Not Discussed,Express,Yes,No,No,No,No,No,Agent,No,No,Unknown,No,Yes,No,No,No,No,Satisfied,80.0,90.0,80.0,No,No,No,No,No
9,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,y,24.5,Accredited,1,Band C1,919,664,120,135,664.0,0.0,135,Won,Card,799.0,1,2025-08-09,Band C1,919.0,0,1,1,0,0.0,OUT_BOUND,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2.0,pre_renewal,No,Not Discussed,Yes,No,No,Yes,neutral,50.0,No,Not Discussed,No,Accredited,No,Yes,1.0,No,Yes,0.0,Yes,No,No,No,No,Not Discussed,Express,Yes,No,No,No,No,No,Agent,No,No,No,No,No,No,No,No,No,Satisfied,50.0,90.0,85.0,Yes,Yes,No,No,No
10,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,y,24.5,Accredited,1,Band C1,919,664,120,135,664.0,0.0,135,Won,Card,799.0,1,2025-08-09,Band C1,919.0,0,1,1,0,0.0,OUT_BOUND,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2.0,pre_renewal,No,Not Discussed,Yes,No,No,Yes,neutral,50.0,No,Not Discussed,No,Accredited,No,Yes,1.0,No,Yes,0.0,Yes,No,No,No,No,Not Discussed,Not Discussed,No,No,No,No,No,No,Customer,No,No,No,No,No,No,No,No,No,Satisfied,50.0,90.0,90.0,No,No,No,No,No
11,8.0,33.0,799.0,8,0,7.5,9.5,True,0,0,n,24.0,Member Only,10,Band C1,799,664,0,135,664.0,0.0,135,Won,Card,799.0,4+,2024-03-01,Band C1,749.0,1,1,0,0,0.0,IN_BOUND,Yes,Yes,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Not Applicable,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,6.0,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Yes,Yes,neutral,50.0,No,Yes,No,Not Discussed,No,Yes,1.0,Not Discussed,Not Discussed,0.0,Not Discussed,Yes,No,Yes,No,Not Discussed,Not Discussed,No,No,Yes,No,Yes,No,Customer,Yes,No,Yes,No,Yes,Yes,No,Yes,No,Dissatisfied,20.0,60.0,40.0,Yes,Yes,Yes,Yes,Yes

In [28]:
categorical_cols = [col for col in df_filtered.columns if col not in num_cols]

In [29]:
print(len(categorical_cols))

79

In [30]:
for col in categorical_cols:
    print(f"Column: {col}")
    print(df_filtered[col].nunique())
    print(df_filtered[col].isnull().sum())
    print("-" * 50)

Column: proforma_auto_renewal
2
0
--------------------------------------------------
Column: current_auto_renewal_flag
2
0
--------------------------------------------------
Column: proforma_membership_status
3
0
--------------------------------------------------
Column: band
13
0
--------------------------------------------------
Column: prospect_outcome
2
0
--------------------------------------------------
Column: payment_method
5
0
--------------------------------------------------
Column: tenure_group
4
0
--------------------------------------------------
Column: last_renewal
558
0
--------------------------------------------------
Column: last_band
14
0
--------------------------------------------------
Column: anchor_group
6
0
--------------------------------------------------
Column: call_direction
3
0
--------------------------------------------------
Column: membership_renewal_decision
3
0
--------------------------------------------------
Column: serious_complaint
3
0
--------------------------------------------------
Column: other_complaint
3
0
--------------------------------------------------
Column: discussion_on_price_increase
3
0
--------------------------------------------------
Column: renewal_impact_due_to_price_increase
3
0
--------------------------------------------------
Column: discount_or_waiver_requested
3
0
--------------------------------------------------
Column: call_reschedule_request
3
0
--------------------------------------------------
Column: agent_flagged_membership_status_alert
3
0
--------------------------------------------------
Column: agent_renewal_initiation
3
0
--------------------------------------------------
Column: explicit_competitor_mention
3
0
--------------------------------------------------
Column: explicit_switching_intent
3
0
--------------------------------------------------
Column: mentioned_competitors
3
0
--------------------------------------------------
Column: price_switching_mentioned
3
0
--------------------------------------------------
Column: competitor_value_comparison
5
0
--------------------------------------------------
Column: competitor_benefits_mentioned
5

0
--------------------------------------------------
Column: topic_introduced_by

4
0
--------------------------------------------------
Column: percentage_price_increase_mentioned
4
0
--------------------------------------------------
Column: monetary_price_increase_mentioned
4
0
--------------------------------------------------
Column: price_range_mentioned
765
0
--------------------------------------------------
Column: customer_asked_for_justification
4
0
--------------------------------------------------
Column: customer_response
5
0
--------------------------------------------------
Column: desire_to_cancel
4
0
--------------------------------------------------
Column: discount_offered
4
0
--------------------------------------------------
Column: time_to_renewal
2
0
--------------------------------------------------
Column: crm_accreditation_completed
4
0
--------------------------------------------------
Column: crm_timely_completion
4
0
--------------------------------------------------
Column: crm_progress_towards_accreditation
4

0
--------------------------------------------------
Column: crm_delays_in_accreditation
4
0
--------------------------------------------------
Column: crm_contractor_suggested_leave

4
0
--------------------------------------------------
Column: crm_contractor_engagement
3
0
--------------------------------------------------
Column: crm_contractor_sentiment
4
0
--------------------------------------------------
Column: crm_dts_or_ssip_mentioned
4
0
--------------------------------------------------
Column: crm_customer_payment_intention
4
0
--------------------------------------------------
Column: crm_competitors_mentioned
4
0
--------------------------------------------------
Column: crm_membership_level
8
0
--------------------------------------------------
Column: crm_platform_issues_raised
4
0
--------------------------------------------------
Column: crm_agent_chased_contractor
4
0
--------------------------------------------------
Column: crm_accreditation_issues
4
0
--------------------------------------------------
Column: crm_membership_overdue
4
0
--------------------------------------------------
Column: crm_dissatisified_with_renewal_price
4
0
--------------------------------------------------
Column: crm_customer_complained
3
0
--------------------------------------------------
Column: crm_refund_mentioned
3
0
--------------------------------------------------
Column: crm_negative_customer_experience
4
0
--------------------------------------------------
Column: crm_dissatisfaction_with_support
4
0
--------------------------------------------------
Column: crm_financial_hardship_mentioned
4
0
--------------------------------------------------
Column: cc_care_package
6
0
--------------------------------------------------
Column: cc_care_package_discussed
3
0
--------------------------------------------------
Column: cc_urgency_getting_on_site
3
0
--------------------------------------------------
Column: cc_external_consultant
3
0
--------------------------------------------------
Column: cc_agent_cross_sell_attempt
3
0
--------------------------------------------------
Column: cc_customer_issues_concerns
3
0
--------------------------------------------------
Column: cc_business_struggles_financial_hardship

3
0
--------------------------------------------------
Column: cc_call_initiated_by
4
0
--------------------------------------------------
Column: cc_questionnaire_completion
3
0
--------------------------------------------------
Column: cc_chasing_response
3
0
--------------------------------------------------
Column: cc_issues_within_questionnaire
3
0
--------------------------------------------------
Column: cc_login_issues
3
0
--------------------------------------------------
Column: cc_platform_issues
3
0
--------------------------------------------------
Column: cc_dissatisfaction_time_to_complete
3
0
--------------------------------------------------
Column: cc_process_complexity_concerns
3
0
--------------------------------------------------
Column: cc_questions_harder_than_expected
3
0
--------------------------------------------------
Column: cc_dissatisfaction_support

3
0
--------------------------------------------------
Column: cc_contractor_sentiment
5

0
--------------------------------------------------
Column: cc_pricing_mentioned
3
0
--------------------------------------------------
Column: cc_pricing_sentiment_impact
3
0
--------------------------------------------------
Column: cc_refund_discussed
3
0
--------------------------------------------------
Column: cc_contractor_suggest_leave
3
0
--------------------------------------------------
Column: cc_contractor_complained
3
0
--------------------------------------------------

In [31]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def preprocess_and_encode(df):
    """
    Preprocesses the dataframe by:
    1. Removing date columns (those with 'date' in name or datetime dtype).
    2. Encoding categorical columns based on unique value count:
       - 2 uniques: Label encoding
       - 3-10 uniques: One-hot encoding (drop_first=True)
       - >10 uniques: Frequency encoding
    
    Args:
        df (pd.DataFrame): Input dataframe
    
    Returns:
        pd.DataFrame: Processed dataframe with dates removed and categoricals encoded
    """
    # Step 1: Identify and remove date columns
    date_cols = [
        col for col in df.columns 
        if 'date' in col.lower() or df[col].dtype == 'datetime64[ns]'
    ]
    df = df.drop(columns=date_cols, errors='ignore')
    print(f"Removed date columns: {date_cols}")
    
    # Step 2: Identify categorical columns
    cat_cols = df.select_dtypes(include=['object', 'category']).columns
    
    # Step 3: Encode categoricals
    for col in cat_cols:
        n_unique = df[col].nunique()
        
        if n_unique <= 3:
            # Label encoding for binary
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col])
            print(f"Label encoded: {col} ({n_unique} uniques)")
            
        elif 4 <= n_unique <= 10:
            # One-hot encoding
            df = pd.get_dummies(df, columns=[col], drop_first=True)
            print(f"One-hot encoded: {col} ({n_unique} uniques)")
            
        else:
            # Frequency encoding for high cardinality
            freq_map = df[col].value_counts()
            df[col] = df[col].map(freq_map)
            print(f"Frequency encoded: {col} ({n_unique} uniques)")
    
    print(f"Final shape: {df.shape}")
    return df

In [32]:
df_encoded = preprocess_and_encode(df_filtered.copy())

Removed date columns: []
Label encoded: current_auto_renewal_flag (2 uniques)
Label encoded: proforma_membership_status (3 uniques)
Frequency encoded: band (13 uniques)
Label encoded: prospect_outcome (2 uniques)
One-hot encoded: payment_method (5 uniques)
One-hot encoded: tenure_group (4 uniques)
Frequency encoded: last_renewal (558 uniques)
Frequency encoded: last_band (14 uniques)
One-hot encoded: anchor_group (6 uniques)
Label encoded: call_direction (3 uniques)
Label encoded: membership_renewal_decision (3 uniques)
Label encoded: serious_complaint (3 uniques)
Label encoded: other_complaint (3 uniques)
Label encoded: discussion_on_price_increase (3 uniques)
Label encoded: renewal_impact_due_to_price_increase (3 uniques)
Label encoded: discount_or_waiver_requested (3 uniques)
Label encoded: call_reschedule_request (3 uniques)
Label encoded: agent_flagged_membership_status_alert (3 uniques)
Label encoded: agent_renewal_initiation (3 uniques)
Label encoded: explicit_competitor_mention (3 uniques)
Label encoded: explicit_switching_intent (3 uniques)

C:\Users\Gaurav Garg\AppData\Local\Temp\ipykernel_14808\3224478787.py:28: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object', 'category']).columns

Label encoded: mentioned_competitors (3 uniques)
Label encoded: price_switching_mentioned (3 uniques)
One-hot encoded: competitor_value_comparison (5 uniques)
One-hot encoded: competitor_benefits_mentioned (5 uniques)
One-hot encoded: topic_introduced_by (4 uniques)
One-hot encoded: percentage_price_increase_mentioned (4 uniques)
One-hot encoded: monetary_price_increase_mentioned (4 uniques)
Frequency encoded: price_range_mentioned (765 uniques)
One-hot encoded: customer_asked_for_justification (4 uniques)
One-hot encoded: customer_response (5 uniques)
One-hot encoded: desire_to_cancel (4 uniques)
One-hot encoded: discount_offered (4 uniques)

Label encoded: time_to_renewal (2 uniques)
One-hot encoded: crm_accreditation_completed (4 uniques)
One-hot encoded: crm_timely_completion (4 uniques)
One-hot encoded: crm_progress_towards_accreditation (4 uniques)
One-hot encoded: crm_delays_in_accreditation (4 uniques)
One-hot encoded: crm_contractor_suggested_leave (4 uniques)
Label encoded: crm_contractor_engagement (3 uniques)
One-hot encoded: crm_contractor_sentiment (4 uniques)
One-hot encoded: crm_dts_or_ssip_mentioned (4 uniques)
One-hot encoded: crm_customer_payment_intention (4 uniques)
One-hot encoded: crm_competitors_mentioned (4 uniques)

One-hot encoded: crm_membership_level (8 uniques)
One-hot encoded: crm_platform_issues_raised (4 uniques)
One-hot encoded: crm_agent_chased_contractor (4 uniques)
One-hot encoded: crm_accreditation_issues (4 uniques)
One-hot encoded: crm_membership_overdue (4 uniques)
One-hot encoded: crm_dissatisified_with_renewal_price (4 uniques)
Label encoded: crm_customer_complained (3 uniques)
Label encoded: crm_refund_mentioned (3 uniques)
One-hot encoded: crm_negative_customer_experience (4 uniques)
One-hot encoded: crm_dissatisfaction_with_support (4 uniques)
One-hot encoded: crm_financial_hardship_mentioned (4 uniques)

One-hot encoded: cc_care_package (6 uniques)
Label encoded: cc_care_package_discussed (3 uniques)
Label encoded: cc_urgency_getting_on_site (3 uniques)
Label encoded: cc_external_consultant (3 uniques)
Label encoded: cc_agent_cross_sell_attempt (3 uniques)
Label encoded: cc_customer_issues_concerns (3 uniques)
Label encoded: cc_business_struggles_financial_hardship (3 uniques)
One-hot encoded: cc_call_initiated_by (4 uniques)
Label encoded: cc_questionnaire_completion (3 uniques)
Label encoded: cc_chasing_response (3 uniques)

Label encoded: cc_issues_within_questionnaire (3 uniques)
Label encoded: cc_login_issues (3 uniques)
Label encoded: cc_platform_issues (3 uniques)
Label encoded: cc_dissatisfaction_time_to_complete (3 uniques)
Label encoded: cc_process_complexity_concerns (3 uniques)
Label encoded: cc_questions_harder_than_expected (3 uniques)
Label encoded: cc_dissatisfaction_support (3 uniques)
One-hot encoded: cc_contractor_sentiment (5 uniques)
Label encoded: cc_pricing_mentioned (3 uniques)
Label encoded: cc_pricing_sentiment_impact (3 uniques)
Label encoded: cc_refund_discussed (3 uniques)
Label encoded: cc_contractor_suggest_leave (3 uniques)

Label encoded: cc_contractor_complained (3 uniques)
Final shape: (78325, 189)

In [33]:
# Check the result
print(df_encoded.head())
print(df_encoded.info())

    sustainability_score  total_renewal_score_new  last_years_price  \
6                    8.0                     41.5             799.0
8                    8.0                     41.5             799.0
9                    8.0                     41.5             799.0
10                   8.0                     41.5             799.0
11                   8.0                     33.0             799.0

    auto_renewal_score  status_scores  anchoring_score  tenure_scores  \
6                    9              9              7.5            8.0
8                    9              9              7.5            8.0
9                    9              9              7.5            8.0
10                   9              9              7.5            8.0
11                   8              0              7.5            9.5

    proforma_auto_renewal  current_anchorings  payment_timeframe  \
6                    True                   0                  0
8                    True                   0                  0
9                    True                   0                  0
10                   True                   0                  0
11                   True                   0                  0

    current_auto_renewal_flag  renewal_score_at_release  \
6                           1                      24.5
8                           1                      24.5
9                           1                      24.5
10                          1                      24.5
11                          0                      24.0

    proforma_membership_status  tenure_years   band  starting_net  \
6                            0             1  15008           919
8                            0             1  15008           919
9                            0             1  15008           919
10                           0             1  15008           919
11                           2            10  15008           799

    starting_membership_net  starting_package_net  starting_pqq_net  \
6                       664                   120               135
8                       664                   120               135
9                       664                   120               135
10                      664                   120               135
11                      664                     0               135

    membership_net  package_net  pqqnet  prospect_outcome  total_amount  \
6            664.0          0.0     135                 1         799.0
8            664.0          0.0     135                 1         799.0
9            664.0          0.0     135                 1         799.0
10           664.0          0.0     135                 1         799.0
11           664.0          0.0     135                 1         799.0

    last_renewal  last_band  last_total_net_paid  last_connections  \
6             21      15351                919.0                 0
8             21      15351                919.0                 0
9             21      15351                919.0                 0
10            21      15351                919.0                 0
11          3064      15351                749.0                 1

    is_first_year  has_discount  discount_pct  call_direction  \
6               1             0           0.0               1
8               1             0           0.0               1
9               1             0           0.0               1
10              1             0           0.0               1
11              0             0           0.0               0

    membership_renewal_decision  serious_complaint  other_complaint  \
6                             0                  0                0
8                             1                  1                1
9                             1                  1                1
10                            1                  1                1
11                            2                  2                0

    discussion_on_price_increase  renewal_impact_due_to_price_increase  \
6                              0                                     0
8                              1                                     1
9                              1                                     1
10                             1                                     1
11                             0                                     0

    discount_or_waiver_requested  call_reschedule_request  \
6                              0                        0
8                              1                        1
9                              1                        1
10                             1                        1
11                             0                        0

    agent_flagged_membership_status_alert  agent_renewal_initiation  \
6                                       0                         2
8                                       1                         1
9                                       1                         1
10                                      1                         1
11                                      0                         0

    explicit_competitor_mention  explicit_switching_intent  \
6                             0                          0
8                             1                          1
9                             1                          1
10                            1                          1
11                            0                          0

    mentioned_competitors  price_switching_mentioned  price_range_mentioned  \
6                       0                          0                  46802
8                       1                          1                  29546
9                       1                          1                  29546
10                      1                          1                  29546
11                      0                          0                  46802

    call_number  time_to_renewal  crm_contractor_engagement  \
6           1.0                1                          2
8           2.0                1                          2
9           2.0                1                          2
10          2.0                1                          2
11          6.0                1                          2

    crm_contractor_sentiment_score  crm_agent_chase_count  \
6                             50.0                    1.0
8                             50.0                    1.0
9                             50.0                    1.0
10                            50.0                    1.0
11                            50.0                    1.0

    crm_auto_renewal_status  crm_customer_complained  crm_refund_mentioned  \
6                       0.0                        0                     0
8                       0.0                        0                     0
9                       0.0                        0                     0
10                      0.0                        0                     0
11                      0.0                        2                     0

    cc_care_package_discussed  cc_urgency_getting_on_site  \
6                           2                           0
8                           2                           0
9                           2                           0
10                          0                           0
11                          0                           0

    cc_external_consultant  cc_agent_cross_sell_attempt  \
6                        0                            0
8                        0                            0
9                        0                            0
10                       0                            0
11                       2                            0

    cc_customer_issues_concerns  cc_business_struggles_financial_hardship  \
6                             0                                         0
8                             0                                         0
9                             0                                         0
10                            0                                         0
11                            2                                         0

    cc_questionnaire_completion  cc_chasing_response  \
6                             0                    0
8                             0                    0
9                             0                    0
10                            0                    0
11                            2                    0

    cc_issues_within_questionnaire  cc_login_issues  cc_platform_issues  \
6                                0                0                   0
8                                1                0                   2
9                                0                0                   0
10                               0                0                   0
11                               2                0                   2

    cc_dissatisfaction_time_to_complete  cc_process_complexity_concerns  \
6                                     0                               0
8                                     0                               0
9                                     0                               0
10                                    0                               0
11                                    2                               0

    cc_questions_harder_than_expected  cc_dissatisfaction_support  \
6                                   0                           0
8                                   0                           0
9                                   0                           0
10                                  0                           0
11                                  2                           0

    cc_contractor_sentiment_start_score  cc_contractor_sentiment_end_score  \
6                                  50.0                               90.0
8                                  80.0                               90.0
9                                  50.0                               90.0
10                                 50.0                               90.0
11                                 20.0                               60.0

    cc_contractor_sentiment_overall_score  cc_pricing_mentioned  \
6                                    85.0                     2
8                                    80.0                     0
9                                    85.0                     2
10                                   90.0                     0
11                                   40.0                     2

    cc_pricing_sentiment_impact  cc_refund_discussed  \
6                             2                    0
8                             0                    0
9                             2                    0
10                            0                    0
11                            2                    2

    cc_contractor_suggest_leave  cc_contractor_complained  \
6                             0                         0
8                             0                         0
9                             0                         0
10                            0                         0
11                            2                         2

    payment_method_Card  payment_method_Cheque  payment_method_Unknown  \
6                  True                  False                   False
8                  True                  False                   False
9                  True                  False                   False
10                 True                  False                   False
11                 True                  False                   False

    payment_method_World Pay  tenure_group_2  tenure_group_3  tenure_group_4+  \
6                      False           False           False            False
8                      False           False           False            False
9                      False           False           False            False
10                     False           False           False            False
11                     False           False           False             True

    anchor_group_10+  anchor_group_2  anchor_group_3  anchor_group_4 to 9  \
6              False           False           False                False
8              False           False           False                False
9              False           False           False                False
10             False           False           False                False
11             False           False           False                False

    anchor_group_Independent  competitor_value_comparison_Not Applicable  \
6                      False                                        True
8                      False                                       False
9                      False                                       False
10                     False                                       False
11                     False                                        True

    competitor_value_comparison_Not Discussed  \
6                                       False
8                                       False
9                                       False
10                                      False
11                                      False

    competitor_value_comparison_Similar Value  \
6                                       False
8                                       False
9                                       False
10                                      False
11                                      False

    competitor_value_comparison_Unknown  \
6                                 False
8                                  True
9                                  True
10                                 True
11                                False

    competitor_benefits_mentioned_Discounts  \
6                                     False
8                                     False
9                                     False
10                                    False
11                                    False

    competitor_benefits_mentioned_Not Applicable  \
6                                           True
8                                          False
9                                          False
10                                         False
11                                          True

    competitor_benefits_mentioned_Not Discussed  \
6                                         False
8                                         False
9                                         False
10                                        False
11                                        False

    competitor_benefits_mentioned_Unknown  topic_introduced_by_Customer  \
6                                   False                         False
8                                    True                         False
9                                    True                         False
10                                   True                         False
11                                  False                         False

    topic_introduced_by_Not Discussed  topic_introduced_by_Unknown  \
6                                True                        False
8                               False                         True
9                               False                         True
10                              False                         True
11                               True                        False

    percentage_price_increase_mentioned_Not Discussed  \
6                                               False
8                                               False
9                                               False
10                                              False
11                                              False

    percentage_price_increase_mentioned_Unknown  \
6                                         False
8                                          True
9                                          True
10                                         True
11                                        False

    percentage_price_increase_mentioned_Yes  \
6                                     False
8                                     False
9                                     False
10                                    False
11                                    False

    monetary_price_increase_mentioned_Not Discussed  \
6                                             False
8                                             False
9                                             False
10                                            False
11                                            False

    monetary_price_increase_mentioned_Unknown  \
6                                       False
8                                        True
9                                        True
10                                       True
11                                      False

    monetary_price_increase_mentioned_Yes  \
6                                   False
8                                   False
9                                   False
10                                  False
11                                  False

    customer_asked_for_justification_Not Discussed  \
6                                            False
8                                            False
9                                            False
10                                           False
11                                           False

    customer_asked_for_justification_Unknown  \
6                                      False
8                                       True
9                                       True
10                                      True
11                                     False

    customer_asked_for_justification_Yes  customer_response_Neutral  \
6                                  False                       True
8                                  False                      False
9                                  False                      False
10                                 False                      False
11                                 False                      False

    customer_response_Not Discussed  customer_response_Positive  \
6                             False                       False
8                             False                       False
9                             False                       False
10                            False                       False
11                             True                       False

    customer_response_Unknown  desire_to_cancel_Not Discussed  \
6                       False                           False
8                        True                           False
9                        True                           False
10                       True                           False
11                      False                            True

    desire_to_cancel_Renewed  desire_to_cancel_Unknown  \
6                       True                     False
8                      False                      True
9                      False                      True
10                     False                      True
11                     False                     False

    discount_offered_Not Discussed  discount_offered_Unknown  \
6                            False                     False
8                            False                      True
9                            False                      True
10                           False                      True
11                           False                     False


In [34]:
df_encoded

,sustainability_score,total_renewal_score_new,last_years_price,auto_renewal_score,status_scores,anchoring_score,tenure_scores,proforma_auto_renewal,current_anchorings,payment_timeframe,current_auto_renewal_flag,renewal_score_at_release,proforma_membership_status,tenure_years,band,starting_net,starting_membership_net,starting_package_net,starting_pqq_net,membership_net,package_net,pqqnet,prospect_outcome,total_amount,last_renewal,last_band,last_total_net_paid,last_connections,is_first_year,has_discount,discount_pct,call_direction,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,price_range_mentioned,call_number,time_to_renewal,crm_contractor_engagement,crm_contractor_sentiment_score,crm_agent_chase_count,crm_auto_renewal_status,crm_customer_complained,crm_refund_mentioned,cc_care_package_discussed,cc_urgency_getting_on_site,cc_external_consultant,cc_agent_cross_sell_attempt,cc_customer_issues_concerns,cc_business_struggles_financial_hardship,cc_questionnaire_completion,cc_chasing_response,cc_issues_within_questionnaire,cc_login_issues,cc_platform_issues,cc_dissatisfaction_time_to_complete,cc_process_complexity_concerns,cc_questions_harder_than_expected,cc_dissatisfaction_support,cc_contractor_sentiment_start_score,cc_contractor_sentiment_end_score,cc_contractor_sentiment_overall_score,cc_pricing_mentioned,cc_pricing_sentiment_impact,cc_refund_discussed,cc_contractor_suggest_leave,cc_contractor_complained,payment_method_Card,payment_method_Cheque,payment_method_Unknown,payment_method_World Pay,tenure_group_2,tenure_group_3,tenure_group_4+,anchor_group_10+,anchor_group_2,anchor_group_3,anchor_group_4 to 9,anchor_group_Independent,competitor_value_comparison_Not Applicable,competitor_value_comparison_Not Discussed,competitor_value_comparison_Similar Value,competitor_value_comparison_Unknown,competitor_benefits_mentioned_Discounts,competitor_benefits_mentioned_Not Applicable,competitor_benefits_mentioned_Not Discussed,competitor_benefits_mentioned_Unknown,topic_introduced_by_Customer,topic_introduced_by_Not Discussed,topic_introduced_by_Unknown,percentage_price_increase_mentioned_Not Discussed,percentage_price_increase_mentioned_Unknown,percentage_price_increase_mentioned_Yes,monetary_price_increase_mentioned_Not Discussed,monetary_price_increase_mentioned_Unknown,monetary_price_increase_mentioned_Yes,customer_asked_for_justification_Not Discussed,customer_asked_for_justification_Unknown,customer_asked_for_justification_Yes,customer_response_Neutral,customer_response_Not Discussed,customer_response_Positive,customer_response_Unknown,desire_to_cancel_Not Discussed,desire_to_cancel_Renewed,desire_to_cancel_Unknown,discount_offered_Not Discussed,discount_offered_Unknown,discount_offered_Yes,crm_accreditation_completed_Not Discussed,crm_accreditation_completed_Unknown,crm_accreditation_completed_Yes,crm_timely_completion_Not Discussed,crm_timely_completion_Unknown,crm_timely_completion_Yes,crm_progress_towards_accreditation_Not Discussed,crm_progress_towards_accreditation_Unknown,crm_progress_towards_accreditation_Yes,crm_delays_in_accreditation_Not Discussed,crm_delays_in_accreditation_Unknown,crm_delays_in_accreditation_Yes,crm_contractor_suggested_leave_Not Discussed,crm_contractor_suggested_leave_Unknown,crm_contractor_suggested_leave_Yes,crm_contractor_sentiment_dissatisfied,crm_contractor_sentiment_neutral,crm_contractor_sentiment_satisfied,crm_dts_or_ssip_mentioned_Not Discussed,crm_dts_or_ssip_mentioned_Unknown,crm_dts_or_ssip_mentioned_Yes,crm_customer_payment_intention_Not Discussed,crm_customer_payment_intention_Unknown,crm_customer_payment_intention_Yes,crm_competitors_mentioned_Not Discussed,crm_competitors_mentioned_Unknown,crm_competitors_mentioned_Yes,crm_membership_level_In progress,crm_membership_level_Members only,crm_membership_level_Not Accredited,crm_membership_level_Not Discussed,crm_membership_level_Premier,crm_membership_level_Standard,crm_membership_level_Unknown,crm_platform_issues_raised_Not Discussed,crm_platform_issues_raised_Unknown,crm_platform_issues_raised_Yes,crm_agent_chased_contractor_Not Discussed,crm_agent_chased_contractor_Unknown,crm_agent_chased_contractor_Yes,crm_accreditation_issues_Not Discussed,crm_accreditation_issues_Unknown,crm_accreditation_issues_Yes,crm_membership_overdue_Not Discussed,crm_membership_overdue_Unknown,crm_membership_overdue_Yes,crm_dissatisified_with_renewal_price_Not Discussed,crm_dissatisified_with_renewal_price_Unknown,crm_dissatisified_with_renewal_price_Yes,crm_negative_customer_experience_Not Discussed,crm_negative_customer_experience_Unknown,crm_negative_customer_experience_Yes,crm_dissatisfaction_with_support_Not Discussed,crm_dissatisfaction_with_support_Unknown,crm_dissatisfaction_with_support_Yes,crm_financial_hardship_mentioned_Not Discussed,crm_financial_hardship_mentioned_Unknown,crm_financial_hardship_mentioned_Yes,cc_care_package_Express,cc_care_package_Not Discussed,cc_care_package_Premier,cc_care_package_Standard,cc_care_package_Unknown,cc_call_initiated_by_Customer,cc_call_initiated_by_Not Relevant,cc_call_initiated_by_Unknown,cc_contractor_sentiment_Neutral,cc_contractor_sentiment_Not Discussed,cc_contractor_sentiment_Satisfied,cc_contractor_sentiment_Unknown
6,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,1,24.5,0,1,15008,919,664,120,135,664.0,0.0,135,1,799.0,21,15351,919.0,0,1,0,0.0,1,0,0,0,0,0,0,0,0,2,0,0,0,0,46802,1.0,1,2,50.0,1.0,0.0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.0,90.0,85.0,2,2,0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False
8,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,1,24.5,0,1,15008,919,664,120,135,664.0,0.0,135,1,799.0,21,15351,919.0,0,1,0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29546,2.0,1,2,50.0,1.0,0.0,0,0,2,0,0,0,0,0,0,0,1,0,2,0,0,0,0,80.0,90.0,80.0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False
9,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,1,24.5,0,1,15008,919,664,120,135,664.0,0.0,135,1,799.0,21,15351,919.0,0,1,0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29546,2.0,1,2,50.0,1.0,0.0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.0,90.0,85.0,2,2,0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False
10,8.0,41.5,799.0,9,9,7.5,8.0,True,0,0,1,24.5,0,1,15008,919,664,120,135,664.0,0.0,135,1,799.0,21,15351,919.0,0,1,0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29546,2.0,1,2,50.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.0,90.0,90.0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,True,False
11,8.0,33.0,799.0,8,0,7.5,9.5,True,0,0,0,24.0,2,10,15008,799,664,0,135,664.0,0.0,135,1,799.0,3064,15351,749.0,1,0,0,0.0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,46802,6.0,1,2,50.0,1.0,0.0,2,0,0,0,2,0,2,0,2,0,2,0,2,2,0,2,0,20.0,60.0,40.0,2,2,2,2,2,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,True,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665967,8.0,32.5,579.0,9,0,7.5,8.0,True,0,-1,1,23.5,0,1,18783,579,480,0,99,480.0,0.0,99,1,579.0,29,18881,579.0,0,1,0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29546,1.0,0,1,50.0,0.0,0.0,1,1,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,50.0,80.0,70.0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False
665976,9.5,43.5,579.0,9,9,7.5,8.5,True,0,-11,1,23.5,0,1,18783,579,480,0,99,480.0,0.0,99,1,579.0,17,18881,579.0,0,1,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,46802,2.0,1,2,50.0,0.0,0.0,0,0,2,0,2,0,0,0,0,0,1,0,0,0,0,0,0,80.0,90.0,85.0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
665977,9.5,43.5,579.0,9,9,7.5,8.5,True,0,-11,1,23.5,0,1,18783,579,480,0,99,480.0,0.0,99,1,579.0,17,18881,579.0,0,1,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,46802,2.0,1,2,50.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.0,80.0,80.0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
665980,9.5,43.5,579.0,9,9,7.5,8.5,True,0,-11,1,23.5,0,1,18783,579,480,0,99,480.0,0.0,99,1,579.0,17,18881,579.0,0,1,0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29546,1.0,1,2,50.0,0.0,0.0,0,0,2,0,2,0,0,0,0,0,1,0,0,0,0,0,0,80.0,90.0,85.0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
665981,9.5,43.5,579.0,9,9,7.5,8.5,True,0,-11,1,23.5,0,1,18783,579,480,0,99,480.0,0.0,99,1,579.0,17,18881,579.0,0,1,0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29546,1.0,1,2,50.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.0,80.0,80.0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False

In [35]:
df_encoded.to_csv('../../../data/processed/churn_prediction_dataset.csv', index=False)

# Finalizing Datasets for Next Steps

In [36]:
# Using open_prospects created earlier
df_open_encoded = None
open_refs = open_prospects['co_ref'].copy()
df_open = open_prospects.drop(columns=[c for c in columns_to_drop if c in open_prospects.columns])
num_cols_open = [c for c in df_open.columns if df_open[c].dtype in ['int64', 'float64']]
fill_numericals_refined(df_open, num_cols_open)
df_open = df_open.fillna('Unknown')
    
import sys, os
old_stdout = sys.stdout
sys.stdout = open(os.devnull, 'w')
df_open_encoded = preprocess_and_encode(df_open.copy())
sys.stdout = old_stdout
df_open_encoded['co_ref'] = open_refs.values
    
# Recreate the engineered features on open_prospects to perfectly match df_encoded
df_open_encoded['price_change'] = df_open_encoded['total_amount'] - df_open_encoded['last_years_price']
df_open_encoded['price_change_pct'] = np.where(df_open_encoded['last_years_price'] > 0, (df_open_encoded['total_amount'] - df_open_encoded['last_years_price']) / df_open_encoded['last_years_price'] * 100, 0)
df_open_encoded['price_increase_flag'] = (df_open_encoded['price_change'] > 0).astype(int)
if 'cc_contractor_sentiment_end_score' in df_open_encoded.columns and 'cc_contractor_sentiment_start_score' in df_open_encoded.columns:
    df_open_encoded['cc_sentiment_delta'] = df_open_encoded['cc_contractor_sentiment_end_score'] - df_open_encoded['cc_contractor_sentiment_start_score']
    df_open_encoded['cc_sentiment_improved'] = (df_open_encoded['cc_sentiment_delta'] > 0).astype(int)
    df_open_encoded['cc_sentiment_declined'] = (df_open_encoded['cc_sentiment_delta'] < 0).astype(int)
df_open_encoded['complaint_intensity'] = df_open_encoded.get('serious_complaint', 0) + df_open_encoded.get('other_complaint', 0) + df_open_encoded.get('cc_contractor_complained', 0) + df_open_encoded.get('crm_customer_complained', 0)
df_open_encoded['dissatisfaction_composite'] = df_open_encoded.get('cc_dissatisfaction_time_to_complete', 0) + df_open_encoded.get('cc_dissatisfaction_support', 0) + df_open_encoded.get('cc_process_complexity_concerns', 0) + df_open_encoded.get('cc_platform_issues', 0)
df_open_encoded['competitive_pressure'] = df_open_encoded.get('explicit_competitor_mention', 0) + df_open_encoded.get('mentioned_competitors', 0) + df_open_encoded.get('price_switching_mentioned', 0)
df_open_encoded['payment_delay_flag'] = (df_open_encoded.get('payment_timeframe', 0) < 0).astype(int)
df_open_encoded['abs_payment_timeframe'] = df_open_encoded.get('payment_timeframe', 0).abs()
df_open_encoded['tenure_price_ratio'] = df_open_encoded['total_amount'] / (df_open_encoded.get('tenure_years', 0) + 1)
df_open_encoded['pqq_share'] = np.where(df_open_encoded['total_amount'] > 0, df_open_encoded.get('pqqnet', 0) / df_open_encoded['total_amount'], 0)
df_open_encoded['package_share'] = np.where(df_open_encoded['total_amount'] > 0, df_open_encoded.get('package_net', 0) / df_open_encoded['total_amount'], 0)

df_open_encoded.to_csv('../../../data/processed/open_prospects_dataset.csv', index=False)
print('Saved open prospects dataset to: data/processed/open_prospects_dataset.csv')

C:\Users\Gaurav Garg\AppData\Local\Temp\ipykernel_14808\3224478787.py:28: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object', 'category']).columns

Saved open prospects dataset to: data/processed/open_prospects_dataset.csv