In [1]:
import pandas as pd

In [2]:
df_renewal = pd.read_csv('../../data/interim/renewal_calls_cleaned.csv')
df_email = pd.read_csv('../../data/interim/emails_cleaned.csv')
df_cc = pd.read_csv('../../data/interim/cc_calls_cleaned.csv')
df_billings = pd.read_csv('../../data/interim/billings_cleaned.csv')

In [3]:
df_cc.info()

<class 'pandas.DataFrame'>
RangeIndex: 31636 entries, 0 to 31635
Data columns (total 30 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   contact_id                                31636 non-null  float64
 1   call_date                                 31636 non-null  str
 2   direction                                 31636 non-null  str
 3   cc_care_package                           31636 non-null  str
 4   cc_care_package_discussed                 31636 non-null  str
 5   cc_urgency_getting_on_site                31636 non-null  str
 6   cc_external_consultant                    31636 non-null  str
 7   cc_agent_cross_sell_attempt               31636 non-null  str
 8   cc_customer_issues_concerns               31636 non-null  str
 9   cc_business_struggles_financial_hardship  31636 non-null  str
 10  cc_call_initiated_by                      31636 non-null  str
 11  cc_questionnaire_completion               31636 non-null  str
 12  cc_chasing_response                       31636 non-null  str
 13  cc_issues_within_questionnaire            31636 non-null  str
 14  cc_login_issues                           31636 non-null  str
 15  cc_platform_issues                        31636 non-null  str
 16  cc_dissatisfaction_time_to_complete       31636 non-null  str
 17  cc_process_complexity_concerns            31636 non-null  str
 18  cc_questions_harder_than_expected         31636 non-null  str
 19  cc_dissatisfaction_support                31636 non-null  str
 20  cc_contractor_sentiment                   31636 non-null  str
 21  cc_contractor_sentiment_start_score       31636 non-null  float64
 22  cc_contractor_sentiment_end_score         31636 non-null  float64
 23  cc_contractor_sentiment_overall_score     31636 non-null  float64
 24  cc_pricing_mentioned                      31636 non-null  str
 25  cc_pricing_sentiment_impact               31636 non-null  str
 26  cc_refund_discussed                       31636 non-null  str
 27  cc_contractor_suggest_leave               31636 non-null  str
 28  cc_contractor_complained                  31636 non-null  str
 29  co_ref                                    31636 non-null  str
dtypes: float64(4), str(26)
memory usage: 7.2 MB

In [4]:
df_merged = (
    df_billings
    .merge(df_renewal, on='co_ref', how='left', suffixes=('', '_renewal'))
    .merge(df_email, on='co_ref', how='left', suffixes=('', '_email'))
    .merge(df_cc, on='co_ref', how='left', suffixes=('', '_cc'))
)

In [5]:
df_merged.shape

(668008, 130)

In [6]:
for col in df_merged.columns:
    print(df_merged[col].value_counts(dropna=False))
    print(df_merged[col].isnull().sum())
    print("-" * 50)

co_ref
VU9662    3968
AD1657    1610
DB3207    1292
AA0994    1287
FW0890     900
          ...
XQ5674       1
MH5611       1
LQ9360       1
EX0639       1
XU6585       1
Name: count, Length: 47814, dtype: int64
0
--------------------------------------------------
renewal_month
2025-10-01    21429
2025-11-01    21214
2024-11-01    20904
2024-10-01    20506
2025-09-01    19763
2024-09-01    19288
2024-06-01    19064
2025-01-01    18402
2024-05-01    18228
2025-06-01    18111
2025-05-01    18062
2023-11-01    18056
2023-10-01    17873
2026-01-01    17650
2025-07-01    17613
2026-02-01    17569
2024-07-01    17436
2023-09-01    16961
2025-02-01    16928
2024-08-01    16836
2023-06-01    16728
2025-08-01    16650
2026-05-01    16192
2023-05-01    16080
2024-01-01    15590
2023-07-01    15499
2024-02-01    14685
2024-04-01    14473
2023-08-01    14292
2025-04-01    14225
2025-12-01    13923
2023-01-01    13903
2024-12-01    13762
2025-03-01    13443
2023-02-01    13351
2023-04-01    12994
2024-03-01    12716
2023-12-01    12433
2026-04-01    12124
2026-03-01    11817
2023-03-01    11235
Name: count, dtype: int64
0
--------------------------------------------------
sustainability_score
8.0    391285
9.5    194680
9.0     82043
Name: count, dtype: int64
0
--------------------------------------------------
total_renewal_score_new
44.0    82186
43.0    63443
45.5    58934
45.0    56146
44.5    54122
43.5    49857
42.0    41418
41.0    30408
42.5    26827
46.5    24704
41.5    20659
46.0    18823
33.0    17545
40.0    14792
34.0    14686
32.0    14393
32.5    12336
40.5    12028
35.0    11040
33.5    10338
34.5    10038
31.5     5559
39.5     5510
31.0     4270
39.0     3600
36.0     1346
38.5      967
35.5      957
30.5      425
36.5      285
38.0      228
37.5      132
37.0        6
Name: count, dtype: int64
0
--------------------------------------------------
last_years_price
999.00    29450
599.00    21923
639.00    21372
579.00    19819
949.00    18585
          ...
403.20        1
208.75        1
78.75         1
580.00        1
258.75        1
Name: count, Length: 2791, dtype: int64
0
--------------------------------------------------
auto_renewal_score
8    370909
9    297099
Name: count, dtype: int64
0
--------------------------------------------------
status_scores
9    379500
0    103356
8     97434
7     87718
Name: count, dtype: int64
0
--------------------------------------------------
anchoring_score
9.5    229847
8.5    188702
7.5    139722
9.0    109736
8.0         1
Name: count, dtype: int64
0
--------------------------------------------------
tenure_scores
9.5    372359
8.5    128746
9.0    101604
8.0     43184
7.5     20212
7.0      1903
Name: count, dtype: int64
0
--------------------------------------------------
proforma_auto_renewal
True     649142
False     18866
Name: count, dtype: int64
0
--------------------------------------------------
proforma_world_pay_token
False    421635
True     246373
Name: count, dtype: int64
0
--------------------------------------------------
proforma_date
2022-11-07    13903
2023-08-14     9371
2026-02-11     9248
2024-03-12     9202
2024-09-05     8973
              ...
2022-12-06        3
2025-12-01        2
2025-11-14        1
2024-09-20        1
2024-08-13        1
Name: count, Length: 169, dtype: int64
0
--------------------------------------------------
current_anchorings
1      188702
0      139723
2      109736
3       67340
4       38356
        ...
81          3
161         3
105         3
69          2
89          1
Name: count, Length: 107, dtype: int64
0
--------------------------------------------------
payment_timeframe
 0      222526
 1       22491
-1       19500
 2       14041
-2       11910
         ...
-397         1
-140         1
-369         1
-277         1
-87          1
Name: count, Length: 287, dtype: int64
0
--------------------------------------------------
registration_date
2019-03-25    5813
2019-05-08    4112
2025-02-18    1649
2019-04-16    1635
2017-01-25    1411
              ...
2024-10-05       1
2024-10-06       1
2024-07-27       1
2024-11-02       1
2024-12-15       1
Name: count, Length: 5787, dtype: int64
0
--------------------------------------------------
proforma_account_stage
Published          412736
Membership Only    103043
Renewal Process     93415
Unknown             38489
Vetting             14318
Suspended            5995
Retired                12
Name: count, dtype: int64
0
--------------------------------------------------
proforma_audit_status
Accredited                                                  406644
Failed- Renewal Questionnaire not received                   43606
Renewal Questionnaire Received                               40865
Unknown                                                      38489
Renewal Questionnaire Sent                                   24119
Failed- Renewal Additional Information Not Received          22875
Failed- Initial additional info not received                 20602
Failed- Initial Questionnaire not received                   15903
Renewal report sent - Awaiting information                    8855
Initial Questionnaire Received                                8213
1st Renewal questionnaire reminder                            7642
Accredited - SSiP due to expire                               5887
Final renewal questionnaire reminder                          5470
Report sent - Awaiting information                            2918
1st Reminder - Renewal additional info                        2794
Final reminder - Renewal additional info                      2653
SUSPENDED - SSiP Expired                                      2570
1st reminder initial add info                                 1583
Final Reminder (Initial) Additional Information Not Sent      1339
SUSPENDED - 1st reminder SSiP Expired                         1269
SSiP Expired - 1st Reminder                                   1117
Renewal additional information received                       1009
SUSPENDED - 2nd reminder SSiP Expired                          991
Additional information received                                220
Accred Due to Expire                                           199
Failed- Accreditation removed SSiP exp                          65
Suspended - Insurance Out-of-Date                               48
Initial - 1st Questionnaire reminder sent                       32
Initial Questionnaire Sent                                      12
Withdrawn from scheme                                           12
unknown                                                          6
Delete 38                                                        1
Name: count, dtype: int64
0
--------------------------------------------------
current_auto_renewal_flag
y    619015
n     48993
Name: count, dtype: int64
0
--------------------------------------------------
current_world_pay_token
n    370760
y    297248
Name: count, dtype: int64
0
--------------------------------------------------
renewal_score_at_release
28.0    106651
27.0     69402
26.0     67882
27.5     66223
26.5     63622
24.5     51190
25.5     43341
25.0     40859
23.5     33151
23.0     31660
24.0     28379
22.5     17053
22.0     14641
28.2     10725
21.5      9165
20.5      4574
27.7      3658
21.0      2448
27.2      1546
25.2       642
26.7       561
24.7       267
24.2       164
25.7       102
26.2        62
23.7        16
16.5        11
22.7        11
15.5         2
Name: count, dtype: int64
0
--------------------------------------------------
proforma_membership_status
Accredited     476732
Member Only    116314
In Progress     74949
Non Member         13
Name: count, dtype: int64
0
--------------------------------------------------
proforma_approved_lists
1      201363
0      136023
2      103313
3       58093
4       39101
        ...
171         1
130         1
162         1
156         1
137         1
Name: count, Length: 135, dtype: int64
0
--------------------------------------------------
tenure_years
1     84334
2     74855
3     60512
4     52374
5     51055
6     41858
7     39729
8     35607
9     32123
10    28834
11    24042
12    21343
13    19449
14    18324
15    18216
16    16225
17    11723
18     8310
20     8250
19     7597
21     6317
22     4315
0      1589
23      799
24      153
25       71
26        4
Name: count, dtype: int64
0
--------------------------------------------------
band
Band B     174100
Band C1    130048
Band D     102755
Band C2     86650
Band E      53272
Band F1     33888
Band F2     20978
Band A      19490
Band G      16951
Band F      12206
Group        5903
Band H       5232
Band J       3651
Band I       2884
Name: count, dtype: int64
0
--------------------------------------------------
prospect_renewal_date
2026-02-18    2038
2025-05-08    1310
2026-05-08    1275
2023-05-08    1265
2024-05-08    1262
              ...
2025-12-26      20
2024-12-27      19
2025-12-27      13
2023-12-27      12
2024-12-26      10
Name: count, Length: 1242, dtype: int64
0
--------------------------------------------------
starting_net
999     32026
599     27594
684     25565
639     25490
579     25182
        ...
709         1
5010        1
6338        1
8333        1
1164        1
Name: count, Length: 1272, dtype: int64
0
--------------------------------------------------
starting_vat
199.8     31764
119.8     27482
136.8     25499
127.8     25399
115.8     25082
          ...
2.0           1
1002.0        1
1267.6        1
1666.6        1
232.8         1
Name: count, Length: 1273, dtype: int64
0
--------------------------------------------------
starting_gross
1198.8    31764
718.8     27482
820.8     25499
766.8     25399
694.8     25082
          ...
2654.0        1
6012.0        1
7605.6        1
9999.6        1
1396.8        1
Name: count, Length: 1461, dtype: int64
0
--------------------------------------------------
starting_membership_net
864     56500
500     52675
480     49223
664     41448
1214    37952
        ...
5010        1
6836        1
4130        1
5318        1
6963        1
Name: count, Length: 123, dtype: int64
0
--------------------------------------------------
starting_package_net
0      346411
120     73494
150     37103
85      26189
105     24783
140     24780
115     23325
160     21317
100     19667
190     15371
145     12213
175     11809
80       9089
125      6903
155      6180
60       2771
225      2523
185      2203
55        966
70        861
200        50
Name: count, dtype: int64
0
--------------------------------------------------
starting_pqq_net
135     377390
99      188283
200      84495
250      11676
390       2067
320       1465
460       1284
530        404
600        193
740        146
880        133
670        132
0          122
810         40
1790        34
1090        25
1860        21
1510        21
1160        15
1230        14
1930        13
1720        13
950         11
1020         9
1370         2
Name: count, dtype: int64
0
--------------------------------------------------
membership_net
864.0     47366
500.0     39861
480.0     36362
664.0     33591
1214.0    32960
          ...
133.0         1
294.0         1
291.0         1
94.0          1
232.0         1
Name: count, Length: 875, dtype: int64
0
--------------------------------------------------
package_net
0.00      382883
120.00     63824
150.00     28471
140.00     22202
85.00      20388
           ...
93.75          1
92.50          1
77.50          1
111.00         1
33.00          1
Name: count, Length: 122, dtype: int64
0
--------------------------------------------------
pqqnet
 135    367262
 99     185214
 200     83454
 250     11716
 0        6193
         ...
 210         1
 40          1
 10          1
-135         1
 6           1
Name: count, Length: 111, dtype: int64
0
--------------------------------------------------
prospect_outcome
Won        576042
Churned     54362
Open        37604
Name: count, dtype: int64
0
--------------------------------------------------
payment_method
Card         371271
Bacs         198175
Unknown       85774
World Pay     12146
Cheque          642
Name: count, dtype: int64
0
--------------------------------------------------
total_amount
999.0    27149
599.0    22090
639.0    20338
579.0    20250
949.0    19048
         ...
501.1        1
390.3        1
395.0        1
174.0        1
296.0        1
Name: count, Length: 2754, dtype: int64
0
--------------------------------------------------
tenure_group
4+    446718
1      85923
2      74855
3      60512
Name: count, dtype: int64
0
--------------------------------------------------
last_renewal
2024-11-01    19030
2024-10-01    18641
2023-11-01    18223
2023-10-01    17904
2024-09-01    17518
              ...
2025-06-22        1
2025-04-28        1
2025-12-27        1
2025-07-27        1
2025-11-02        1
Name: count, Length: 1155, dtype: int64
0
--------------------------------------------------
last_band
Band B     176683
Band C1    130011
Band D     100940
Band C2     89839
Band E      51013
Band F1     25428
Band F      24191
Band A      19833
Band G      16755
Band F2     15707
Group        6045
Band H       5151
Band I       3645
Band J       2767
Name: count, dtype: int64
0
--------------------------------------------------
last_total_net_paid
539.0     28209
579.0     25316
999.0     22613
684.0     22592
949.0     20335
          ...
184.0         1
872.8         1
1109.2        1
3096.2        1
4589.0        1
Name: count, Length: 1289, dtype: int64
0
--------------------------------------------------
last_connections
0      324178
1      125172
2       64336
3       37815
4       26268
        ...
75          1
163         1
114         1
137         1
156         1
Name: count, Length: 127, dtype: int64
0
--------------------------------------------------
anchor_group
1              201363
Independent    136023
4 to 9         116439
2              103313
3               58093
10+             52777
Name: count, dtype: int64
0
--------------------------------------------------
renewal_year
2025    209763
2024    203488
2023    179405
2026     75352
Name: count, dtype: int64
0
--------------------------------------------------
is_first_year
0    425912
1    242096
Name: count, dtype: int64
0
--------------------------------------------------
has_discount
0    564746
1    103262
Name: count, dtype: int64
0
--------------------------------------------------
discount_pct
0.000    564746
0.200     47610
0.300     16652
0.500     14359
0.400     11417
0.100      6395
0.150      4031
0.350      1793
0.250       822
0.450       175
1.000         5
0.133         3
Name: count, dtype: int64
0
--------------------------------------------------
call_id
NaN             29278
5.950000e+11    22808
5.110000e+11    20596
5.940000e+11    20403
5.090000e+11    20381
5.070000e+11    20223
5.960000e+11    19629
5.080000e+11    19226
5.380000e+11    17538
6.230000e+11    16357
6.220000e+11    16187
5.650000e+11    15907
5.390000e+11    15757
5.100000e+11    15534
5.920000e+11    15458
5.060000e+11    15457
5.910000e+11    15235
5.130000e+11    15056
5.120000e+11    15029
6.260000e+11    14105
5.970000e+11    13934
6.940000e+11    13681
5.900000e+11    13452
6.250000e+11    12887
6.820000e+11    12345
6.790000e+11    11679
6.510000e+11    11665
6.930000e+11    11660
6.850000e+11    11596
6.880000e+11    11478
6.830000e+11    11164
6.860000e+11    11036
6.870000e+11    10864
6.770000e+11    10548
6.920000e+11    10496
6.900000e+11    10482
6.890000e+11     9968
6.240000e+11     9905
6.840000e+11     9761
6.800000e+11     9556
5.400000e+11     9319
5.930000e+11     9052
6.810000e+11     8873
5.640000e+11     8432
6.780000e+11     8034
5.050000e+11     7615
6.520000e+11     6930
6.950000e+11     5917
5.370000e+11     3775
6.910000e+11     3200
5.660000e+11     2810
6.760000e+11     2309
1.940000e+11     1965
1.930000e+11     1456
Name: count, dtype: int64
29278
--------------------------------------------------
call_direction
OUT_BOUND    530673
IN_BOUND     108057
NaN           29278
Name: count, dtype: int64
29278
--------------------------------------------------
call_date
NaN           29278
2025-01-15     2841
2025-01-13     2594
2025-01-27     2516
2025-01-14     2270
              ...
2025-03-25      450
2025-07-10      373
2025-12-24       87
2026-01-17       44
2026-01-11        8
Name: count, Length: 468, dtype: int64
29278
--------------------------------------------------
membership_renewal_decision
No         348456
Unknown    264729
NaN         29278
Yes         25545
Name: count, dtype: int64
29278
--------------------------------------------------
serious_complaint
No         361796
Unknown    274723
NaN         29278
Yes          2211
Name: count, dtype: int64
29278
--------------------------------------------------
other_complaint
No         278697
Unknown    274737
Yes         85296
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
discussion_on_price_increase
No         344093
Unknown    258020
Yes         36617
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
renewal_impact_due_to_price_increase
No         366755
Unknown    258265
NaN         29278
Yes         13710
Name: count, dtype: int64
29278
--------------------------------------------------
discount_or_waiver_requested
No         368528
Unknown    258282
NaN         29278
Yes         11920
Name: count, dtype: int64
29278
--------------------------------------------------
call_reschedule_request
No         374117
Unknown    255676
NaN         29278
Yes          8937
Name: count, dtype: int64
29278
--------------------------------------------------
agent_flagged_membership_status_alert
No         266648
Unknown    255676
Yes        116406
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
agent_renewal_initiation
Unknown    255676
No         206829
Yes        176225
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
explicit_competitor_mention
No         376986
Unknown    255193
NaN         29278
Yes          6551
Name: count, dtype: int64
29278
--------------------------------------------------
explicit_switching_intent
No         383323
Unknown    255211
NaN         29278
Yes           196
Name: count, dtype: int64
29278
--------------------------------------------------
mentioned_competitors
No         353962
Unknown    255227
Yes         29541
NaN         29278
Name: count, dtype: int64
29278
--------------------------------------------------
price_switching_mentioned
No         370884
Unknown    255396
NaN         29278
Yes         12450
Name: count, dtype: int64
29278
--------------------------------------------------
competitor_value_comparison
Not Applicable    361829
Unknown           255459
NaN                29278
Not Discussed      12951
Better Value        5612
Similar Value       2879
Name: count, dtype: int64
29278
--------------------------------------------------
competitor_benefits_mentioned
Not Applicable    281431
Unknown           270647
Not Discussed      66905
NaN                29278
Discounts          11151
Better Service      8596
Name: count, dtype: int64
29278
--------------------------------------------------
topic_introduced_by
Not Discussed    289190
Unknown          255019
Agent             69173
NaN               29278
Customer          25348
Name: count, dtype: int64
29278
--------------------------------------------------
percentage_price_increase_mentioned
No               377841
Unknown          255019
NaN               29278
Yes                3408
Not Discussed      2462
Name: count, dtype: int64
29278
--------------------------------------------------
monetary_price_increase_mentioned
No               367827
Unknown          255019
NaN               29278
Yes               13422
Not Discussed      2462

In [7]:
df_merged

,co_ref,renewal_month,sustainability_score,total_renewal_score_new,last_years_price,auto_renewal_score,status_scores,anchoring_score,tenure_scores,proforma_auto_renewal,...,cc_dissatisfaction_support,cc_contractor_sentiment,cc_contractor_sentiment_start_score,cc_contractor_sentiment_end_score,cc_contractor_sentiment_overall_score,cc_pricing_mentioned,cc_pricing_sentiment_impact,cc_refund_discussed,cc_contractor_suggest_leave,cc_contractor_complained
0,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VT6174,2024-11-01,8.0,42.5,799.0,9,9,7.5,9.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668003,DO6023,2023-09-01,8.0,33.0,539.0,9,0,7.5,8.5,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668004,KR5815,2023-08-01,8.0,40.5,539.0,9,7,7.5,9.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668005,KR5815,2023-08-01,8.0,40.5,539.0,9,7,7.5,9.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668006,MA8737,2023-07-01,8.0,42.5,539.0,9,9,7.5,9.0,True,...,No,Satisfied,50.0,90.0,90.0,No,No,No,No,No
668007,MA8737,2023-07-01,8.0,42.5,539.0,9,9,7.5,9.0,True,...,No,Satisfied,50.0,90.0,90.0,No,No,No,No,No

In [8]:
df_merged[df_merged['co_ref'] == 'VT6174'].describe()

,sustainability_score,total_renewal_score_new,last_years_price,auto_renewal_score,status_scores,anchoring_score,tenure_scores,current_anchorings,payment_timeframe,renewal_score_at_release,...,call_number,crm_contractor_sentiment_score,crm_agent_chase_count,crm_auto_renewal_status,year,sentiment_score_missing,contact_id,cc_contractor_sentiment_start_score,cc_contractor_sentiment_end_score,cc_contractor_sentiment_overall_score
count,15.0,15.0,15.000000,15.0,15.0,15.0,15.0,15.0,15.000000,15.000000,...,15.00000,15.0,15.0,15.0,15.0,15.0,0.0,0.0,0.0,0.0
mean,8.0,42.5,734.000000,9.0,9.0,7.5,9.0,0.0,7.333333,26.000000,...,3.00000,50.0,0.0,0.0,2025.0,0.0,NaN,NaN,NaN,NaN
std,0.0,0.0,57.165174,0.0,0.0,0.0,0.0,0.0,10.734901,0.422577,...,1.46385,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
min,8.0,42.5,664.000000,9.0,9.0,7.5,9.0,0.0,0.000000,25.500000,...,1.00000,50.0,0.0,0.0,2025.0,0.0,NaN,NaN,NaN,NaN
25%,8.0,42.5,664.000000,9.0,9.0,7.5,9.0,0.0,0.000000,25.500000,...,2.00000,50.0,0.0,0.0,2025.0,0.0,NaN,NaN,NaN,NaN
50%,8.0,42.5,739.000000,9.0,9.0,7.5,9.0,0.0,0.000000,26.000000,...,3.00000,50.0,0.0,0.0,2025.0,0.0,NaN,NaN,NaN,NaN
75%,8.0,42.5,799.000000,9.0,9.0,7.5,9.0,0.0,22.000000,26.500000,...,4.00000,50.0,0.0,0.0,2025.0,0.0,NaN,NaN,NaN,NaN
max,8.0,42.5,799.000000,9.0,9.0,7.5,9.0,0.0,22.000000,26.500000,...,5.00000,50.0,0.0,0.0,2025.0,0.0,NaN,NaN,NaN,NaN

In [9]:

for col in df_merged.columns:
    if 'date' in col or 'month' in col:
        df_merged[col] = pd.to_datetime(df_merged[col])
        print(col)
        print(df_merged[col])

renewal_month
0        2024-11-01
1        2024-11-01
2        2024-11-01
3        2024-11-01
4        2024-11-01
            ...
668003   2023-09-01
668004   2023-08-01
668005   2023-08-01
668006   2023-07-01
668007   2023-07-01
Name: renewal_month, Length: 668008, dtype: datetime64[us]
proforma_date
0        2024-09-06
1        2024-09-06
2        2024-09-06
3        2024-09-06
4        2024-09-06
            ...
668003   2023-07-06
668004   2023-06-07
668005   2023-06-07
668006   2023-05-10
668007   2023-05-10
Name: proforma_date, Length: 668008, dtype: datetime64[us]
registration_date
0        2021-11-05
1        2021-11-05
2        2021-11-05
3        2021-11-05
4        2021-11-05
            ...
668003   2020-09-15
668004   2020-08-03
668005   2020-08-03
668006   2020-07-08
668007   2020-07-08
Name: registration_date, Length: 668008, dtype: datetime64[us]
prospect_renewal_date
0        2024-11-05
1        2024-11-05
2        2024-11-05
3        2024-11-05
4        2024-11-05
            ...
668003   2023-09-15
668004   2023-08-03
668005   2023-08-03
668006   2023-07-08
668007   2023-07-08
Name: prospect_renewal_date, Length: 668008, dtype: datetime64[us]
call_date
0        2026-01-13
1        2025-11-05
2        2025-10-09
3        2025-10-29
4        2024-10-09
            ...
668003   2024-08-23
668004   2024-07-08
668005   2025-07-07
668006   2024-07-02
668007   2025-06-12
Name: call_date, Length: 668008, dtype: datetime64[us]
call_date_cc
0               NaT
1               NaT
2               NaT
3               NaT
4               NaT
            ...
668003          NaT
668004          NaT
668005          NaT
668006   2025-01-08
668007   2025-01-08
Name: call_date_cc, Length: 668008, dtype: datetime64[us]

In [10]:
df_open_outcomes = df_merged[df_merged['prospect_outcome'] == 'Open']

In [11]:
df_filtered = df_merged[
    (
        ((df_merged['prospect_renewal_date'] - df_merged['call_date']).dt.days >= 0) &
        ((df_merged['prospect_renewal_date'] - df_merged['call_date']).dt.days <= 14)
    ) | (
        ((df_merged['prospect_renewal_date'] - df_merged['call_date_cc']).dt.days >= 0) &
        ((df_merged['prospect_renewal_date'] - df_merged['call_date_cc']).dt.days <= 14)
    )
    & 
    (df_merged['prospect_outcome'] != 'Open')
]

In [12]:
df_filtered.shape

(78918, 130)

In [13]:
for col in df_filtered.columns:
    print(df_filtered[col].value_counts(dropna=False))
    print(df_filtered[col].isnull().sum())
    print("-" * 50)

co_ref
AA0994    243
RE6328    102
VU9662     93
GK6414     80
XB6908     78
         ...
MR9914      1
AH3239      1
NS9452      1
IK6353      1
HG7200      1
Name: count, Length: 21338, dtype: int64
0
--------------------------------------------------
renewal_month
2025-02-01    4530
2025-10-01    4418
2025-09-01    4259
2025-01-01    4216
2025-11-01    4164
2024-10-01    4128
2024-11-01    4121
2024-09-01    3880
2024-07-01    3730
2024-05-01    3675
2025-03-01    3614
2024-08-01    3423
2025-07-01    3275
2025-08-01    3208
2024-06-01    3161
2024-12-01    2920
2025-06-01    2902
2024-04-01    2711
2025-05-01    2673
2025-12-01    2647
2026-01-01    2635
2025-04-01    2473
2026-02-01    2155
Name: count, dtype: int64
0
--------------------------------------------------
sustainability_score
8.0    44917
9.5    24098
9.0     9903
Name: count, dtype: int64
0
--------------------------------------------------
total_renewal_score_new
44.0    9965
43.0    7441
45.5    7115
45.0    6734
44.5    6663
43.5    6331
42.0    5081
42.5    3355
41.0    3277
41.5    2581
46.5    2366
32.0    1984
33.0    1895
46.0    1783
40.5    1488
34.0    1469
40.0    1452
32.5    1442
35.0    1131
33.5    1036
31.0     966
34.5     944
39.5     785
31.5     704
39.0     374
38.5     174
36.0     133
35.5      77
30.5      59
36.5      55
38.0      49
37.5       8
37.0       1
Name: count, dtype: int64
0
--------------------------------------------------
last_years_price
599.00     3455
999.00     3446
799.00     2901
949.00     2341
579.00     2242
           ...
702.00        1
813.60        1
833.40        1
1592.10       1
258.75        1
Name: count, Length: 1430, dtype: int64
0
--------------------------------------------------
auto_renewal_score
8    50126
9    28792
Name: count, dtype: int64
0
--------------------------------------------------
status_scores
9    46256
0    11904
8    11684
7     9074
Name: count, dtype: int64
0
--------------------------------------------------
anchoring_score
9.5    28077
8.5    22313
7.5    15592
9.0    12935
8.0        1
Name: count, dtype: int64
0
--------------------------------------------------
tenure_scores
9.5    43518
8.5    13729
9.0    10389
8.0     7697
7.5     3386
7.0      199
Name: count, dtype: int64
0
--------------------------------------------------
proforma_auto_renewal
True     76526
False     2392
Name: count, dtype: int64
0
--------------------------------------------------
proforma_world_pay_token
False    57616
True     21302
Name: count, dtype: int64
0
--------------------------------------------------
proforma_date
2024-03-15    1863
2024-08-09    1712
2024-09-05    1689
2024-03-12    1650
2025-08-11    1631
              ...
2024-09-09       1
2024-08-30       1
2024-08-16       1
2024-10-17       1
2024-04-19       1
Name: count, Length: 98, dtype: int64
0
--------------------------------------------------
current_anchorings
1      22313
0      15593
2      12935
3       8219
4       4671
       ...
102        1
103        1
65         1
84         1
207        1
Name: count, Length: 90, dtype: int64
0
--------------------------------------------------
payment_timeframe
 0      25916
-1       4598
 1       4038
-2       2484
 2       2442
        ...
 142        1
 182        1
 156        1
-362        1
-140        1
Name: count, Length: 228, dtype: int64
0
--------------------------------------------------
registration_date
2019-03-25    689
2017-01-25    256
2020-02-12    136
2024-02-12    127
2011-07-13    119
             ...
2023-05-07      1
2024-06-30      1
2024-06-09      1
2024-10-05      1
2024-12-15      1
Name: count, Length: 4882, dtype: int64
0
--------------------------------------------------
proforma_account_stage
Published          52791
Membership Only    11876
Renewal Process    11688
Vetting             1741
Suspended            822
Name: count, dtype: int64
0
--------------------------------------------------
proforma_audit_status
Accredited                                                  51931
Renewal Questionnaire Received                               5012
Failed- Renewal Questionnaire not received                   4954
Renewal Questionnaire Sent                                   3419
Failed- Renewal Additional Information Not Received          2498
Failed- Initial additional info not received                 2366
Failed- Initial Questionnaire not received                   2059
Initial Questionnaire Received                               1156
1st Renewal questionnaire reminder                            939
Renewal report sent - Awaiting information                    872
Accredited - SSiP due to expire                               846
Final renewal questionnaire reminder                          696
SUSPENDED - SSiP Expired                                      359
1st Reminder - Renewal additional info                        285
Final reminder - Renewal additional info                      278
Report sent - Awaiting information                            261
Renewal additional information received                       186
SUSPENDED - 2nd reminder SSiP Expired                         185
Final Reminder (Initial) Additional Information Not Sent      155
SSiP Expired - 1st Reminder                                   141
SUSPENDED - 1st reminder SSiP Expired                         136
1st reminder initial add info                                 131
Additional information received                                22
Initial - 1st Questionnaire reminder sent                      16
Accred Due to Expire                                           13
Suspended - Insurance Out-of-Date                               1
unknown                                                         1
Name: count, dtype: int64
0
--------------------------------------------------
current_auto_renewal_flag
y    73253
n     5665
Name: count, dtype: int64
0
--------------------------------------------------
current_world_pay_token
n    50122
y    28796
Name: count, dtype: int64
0
--------------------------------------------------
renewal_score_at_release
28.0    16767
27.5     8478
27.0     8398
26.0     7426
24.5     6673
26.5     6637
25.0     5063
23.5     4504
25.5     4132
23.0     3195
24.0     2499
22.0     1732
22.5     1212
21.5     1071
20.5      957
28.2      100
21.0       20
26.7       17
27.7       16
27.2       13
24.7        4
25.2        3
25.7        1
Name: count, dtype: int64
0
--------------------------------------------------
proforma_membership_status
Accredited     57189
Member Only    12699
In Progress     9030
Name: count, dtype: int64
0
--------------------------------------------------
proforma_approved_lists
1      23017
0      14973
2      12640
3       6920
4       4895
       ...
75         1
99         1
100        1
61         1
83         1
Name: count, Length: 90, dtype: int64
0
--------------------------------------------------
tenure_years
1     11465
2      7639
3      6447
5      5551
4      5141
6      5124
7      4414
8      3963
9      3774
10     3535
11     3284
12     2950
13     2386
15     2291
16     2288
14     2201
17     1881
21     1260
18      931
20      910
19      708
22      607
0        94
23       57
24       17
Name: count, dtype: int64
0
--------------------------------------------------
band
Band B     18981
Band C1    15152
Band D     12786
Band C2    10194
Band E      6828
Band F1     5454
Band F2     3177
Band G      2194
Band A      2068
Group        682
Band H       635
Band J       529
Band I       238
Name: count, dtype: int64
0
--------------------------------------------------
prospect_renewal_date
2025-01-25    384
2025-01-31    373
2025-09-30    362
2025-02-12    289
2025-02-05    287
             ...
2024-12-27      3
2026-01-03      2
2025-01-01      2
2024-12-30      2
2026-01-01      2
Name: count, Length: 692, dtype: int64
0
--------------------------------------------------
starting_net
599     5093
799     4199
949     4106
684     3554
999     3416
        ...
5794       1
3814       1
3824       1
3589       1
585        1
Name: count, Length: 698, dtype: int64
0
--------------------------------------------------
starting_vat
119.80    5060
159.80    4174
189.80    4080
136.80    3536
199.80    3388
          ...
764.80       1
717.80       1
117.00       1
1.28         1
1.41         1
Name: count, Length: 697, dtype: int64
0
--------------------------------------------------
starting_gross
718.80     5060
958.80     4174
1138.80    4080
820.80     3536
1198.80    3388
           ...
702.00        1
640.28        1
1789.00       1
705.41        1
3299.00       1
Name: count, Length: 792, dtype: int64
0
--------------------------------------------------
starting_membership_net
500      9586
664      8458
1024     7045
1214     6575
864      6100
         ...
12487       3
4444        3
10427       2
3894        2
4173        2
Name: count, Length: 72, dtype: int64
0
--------------------------------------------------
starting_package_net
0      41166
120    12400
150     5168
85      3763
160     3505
140     3447
105     3146
190     2352
175     1378
100      998
125      835
60       364
225      294
70        98
200        4
Name: count, dtype: int64
0
--------------------------------------------------
starting_pqq_net
135     45723
99      20204
200     10894
250      1385
390       254
460       168
320       149
530        53
600        28
880        22
670         9
1230        7
1790        5
1720        5
810         3
740         3
950         3
0           3
Name: count, dtype: int64
0
--------------------------------------------------
membership_net
500.00     7446
664.00     6845
1024.00    5628
1214.00    5517
864.00     4768
           ...
1929.00       1
475.50        1
909.35        1
1679.00       1
914.00        1
Name: count, Length: 405, dtype: int64
0
--------------------------------------------------
package_net
0.00      44479
120.00    10659
150.00     3942
160.00     3069
85.00      2941
          ...
113.75        2
82.50         2
57.75         2
131.25        1
104.00        1
Name: count, Length: 83, dtype: int64
0
--------------------------------------------------
pqqnet
 135     44883
 99      20840
 200     10804
 250      1401
 390       251
 320       149
 460       130
 530        65
 9          59
 0          43
 600        33
 29         28
 49         27
 880        22
 85         21
-65         17
-35         13
 69         12
-71         10
 45          9
-101         8
-15          8
 670         6
-51          5
 25          5
-31          5
 270         5
 1720        5
-131         4
 65          4
-91          4
 36          4
 150         3
 810         3
 740         3
 950         3
 1860        3
-11          3
-115         3
-50          3
 70          2
-95          2
-36          2
 1790        2
 105         2
 400         2
 30          2
Name: count, dtype: int64
0
--------------------------------------------------
prospect_outcome
Won        68967
Churned     9358
Open         593
Name: count, dtype: int64
0
--------------------------------------------------
payment_method
Bacs         37722
Card         30354
Unknown       9951
World Pay      848
Cheque          43
Name: count, dtype: int64
0
--------------------------------------------------
total_amount
599.0     4198
799.0     3661
949.0     3187
999.0     2681
684.0     2569
          ...
702.0        1
813.6        1
833.4        1
1592.1       1
1015.5       1
Name: count, Length: 1303, dtype: int64
0
--------------------------------------------------
tenure_group
4+    53273
1     11559
2      7639
3      6447
Name: count, dtype: int64
0
--------------------------------------------------
last_renewal
2024-02-01    3826
2023-10-01    3600
2024-01-01    3533
2024-11-01    3529
2023-11-01    3520
              ...
2025-06-09       1
2025-10-05       1
2025-11-30       1
2024-08-12       1
2025-12-15       1
Name: count, Length: 560, dtype: int64
0
--------------------------------------------------
last_band
Band B     19081
Band C1    15499
Band D     12588
Band C2    10554
Band E      6471
Band F1     4086
Band F2     2396
Band G      2160
Band A      2117
Band F      1863
Group        710
Band H       637
Band J       406
Band I       350
Name: count, dtype: int64
0
--------------------------------------------------
last_total_net_paid
579.0     3726
999.0     3338
684.0     2885
949.0     2740
749.0     2725
          ...
511.1        1
2004.1       1
2487.0       1
1729.2       1
3299.0       1
Name: count, Length: 823, dtype: int64
0
--------------------------------------------------
last_connections
0      23318
1      18468
2      10436
3       6550
4       4576
       ...
98         1
97         1
84         1
86         1
108        1
Name: count, Length: 95, dtype: int64
0
--------------------------------------------------
anchor_group
1              23017
4 to 9         15099
Independent    14973
2              12640
3               6920
10+             6269
Name: count, dtype: int64
0
--------------------------------------------------
renewal_year
2025    42379
2024    31749
2026     4790
Name: count, dtype: int64
0
--------------------------------------------------
is_first_year
0    67134
1    11784
Name: count, dtype: int64
0
--------------------------------------------------
has_discount
0    65241
1    13677
Name: count, dtype: int64
0
--------------------------------------------------
discount_pct
0.00    65241
0.20     6639
0.30     2072
0.50     1889
0.40     1175
0.10      823
0.15      713
0.35      223
0.25      113
0.45       30
Name: count, dtype: int64
0
--------------------------------------------------
call_id
5.950000e+11    2684
5.110000e+11    2625
5.380000e+11    2389
5.390000e+11    2387
5.940000e+11    2344
5.070000e+11    2239
5.960000e+11    2232
5.910000e+11    2227
5.090000e+11    2182
5.080000e+11    2143
5.650000e+11    2065
5.920000e+11    2025
6.220000e+11    1954
5.100000e+11    1946
5.130000e+11    1875
5.120000e+11    1867
6.830000e+11    1815
5.900000e+11    1794
6.820000e+11    1791
6.850000e+11    1753
6.880000e+11    1711
6.870000e+11    1626
6.790000e+11    1588
6.940000e+11    1540
6.930000e+11    1534
5.060000e+11    1530
6.890000e+11    1524
6.230000e+11    1488
6.510000e+11    1467
6.860000e+11    1458
5.970000e+11    1434
6.800000e+11    1367
6.260000e+11    1340
6.840000e+11    1331
6.770000e+11    1275
6.920000e+11    1264
6.810000e+11    1260
5.400000e+11    1251
6.250000e+11    1191
5.640000e+11    1187
6.780000e+11    1097
6.900000e+11    1006
5.050000e+11     856
6.240000e+11     848
6.520000e+11     808
5.930000e+11     797
6.950000e+11     721
5.370000e+11     464
5.660000e+11     395
6.910000e+11     293
1.940000e+11     274
6.760000e+11     272
NaN              240
1.930000e+11     144
Name: count, dtype: int64
240
--------------------------------------------------
call_direction
OUT_BOUND    67380
IN_BOUND     11298
NaN            240
Name: count, dtype: int64
240
--------------------------------------------------
call_date
2025-01-17    353
2024-09-24    331
2024-07-01    328
2025-01-23    327
2025-10-10    326
             ...
2025-07-10     61
2025-12-17     47
2025-03-25     47
2025-12-23     30
2025-12-24      1
Name: count, Length: 466, dtype: int64
240
--------------------------------------------------
membership_renewal_decision
No         45245
Unknown    30557
Yes         2876
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
serious_complaint
No         46471
Unknown    31962
Yes          245
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
other_complaint
No         37654
Unknown    31966
Yes         9058
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
discussion_on_price_increase
No         44828
Unknown    29962
Yes         3888
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
renewal_impact_due_to_price_increase
No         47089
Unknown    29982
Yes         1607
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
discount_or_waiver_requested
No         47286
Unknown    29983
Yes         1409
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
call_reschedule_request
No         47950
Unknown    29686
Yes         1042
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
agent_flagged_membership_status_alert
No         32624
Unknown    29686
Yes        16368
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
agent_renewal_initiation
Unknown    29686
No         26030
Yes        22962
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
explicit_competitor_mention
No         48246
Unknown    29640
Yes          792
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
explicit_switching_intent
No         49015
Unknown    29640
NaN          240
Yes           23
Name: count, dtype: int64
240
--------------------------------------------------
mentioned_competitors
No         45701
Unknown    29641
Yes         3336
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
price_switching_mentioned
No         47660
Unknown    29647
Yes         1371
NaN          240
Name: count, dtype: int64
240
--------------------------------------------------
competitor_value_comparison
Not Applicable    46370
Unknown           29659
Not Discussed      1704
Better Value        611
Similar Value       334
NaN                 240
Name: count, dtype: int64
240
--------------------------------------------------
competitor_benefits_mentioned
Not Applicable    36175
Unknown           31551
Not Discussed      8785
Discounts          1272
Better Service      895
NaN                 240
Name: count, dtype: int64
240
--------------------------------------------------
topic_introduced_by
Not Discussed    37497
Unknown          29615
Agent             8738
Customer          2828
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
percentage_price_increase_mentioned
No               48339
Unknown          29615
Yes                382
Not Discussed      342
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
monetary_price_increase_mentioned
No               47019
Unknown          29615
Yes               1702
Not Discussed      342
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
price_range_mentioned
Not Discussed    47080
Unknown          29615
NaN                240
589.0               71
899.0               20
                 ...
766.5                1
932.0                1
634.0                1
521.0                1
7.34                 1
Name: count, Length: 768, dtype: int64
240
--------------------------------------------------
customer_asked_for_justification
No               45814
Unknown          29615
Yes               2907
Not Discussed      342
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
customer_response
Neutral          32934
Unknown          29615
Not Discussed    13117
Negative          2612
Positive           400
NaN                240
Name: count, dtype: int64
240
--------------------------------------------------
desire_to_cancel
Unknown              29637
Renewed              24247
Not Discussed        20817
Desired to Cancel     3977
NaN                    240
Name: count, dtype: int64
240
--------------------------------------------------
discount_offered
No               46098

In [14]:
df_filtered = df_filtered.fillna('Unknown')

In [15]:
df_filtered.shape

(78918, 130)

In [16]:
for col in df_filtered.columns:
    print(df_filtered[col].value_counts(dropna=False))
    print(df_filtered[col].isnull().sum())
    print("-" * 50)

co_ref
AA0994    243
RE6328    102
VU9662     93
GK6414     80
XB6908     78
         ...
MR9914      1
AH3239      1
NS9452      1
IK6353      1
HG7200      1
Name: count, Length: 21338, dtype: int64
0
--------------------------------------------------
renewal_month
2025-02-01    4530
2025-10-01    4418
2025-09-01    4259
2025-01-01    4216
2025-11-01    4164
2024-10-01    4128
2024-11-01    4121
2024-09-01    3880
2024-07-01    3730
2024-05-01    3675
2025-03-01    3614
2024-08-01    3423
2025-07-01    3275
2025-08-01    3208
2024-06-01    3161
2024-12-01    2920
2025-06-01    2902
2024-04-01    2711
2025-05-01    2673
2025-12-01    2647
2026-01-01    2635
2025-04-01    2473
2026-02-01    2155
Name: count, dtype: int64
0
--------------------------------------------------
sustainability_score
8.0    44917
9.5    24098
9.0     9903
Name: count, dtype: int64
0
--------------------------------------------------
total_renewal_score_new
44.0    9965
43.0    7441
45.5    7115
45.0    6734
44.5    6663
43.5    6331
42.0    5081
42.5    3355
41.0    3277
41.5    2581
46.5    2366
32.0    1984
33.0    1895
46.0    1783
40.5    1488
34.0    1469
40.0    1452
32.5    1442
35.0    1131
33.5    1036
31.0     966
34.5     944
39.5     785
31.5     704
39.0     374
38.5     174
36.0     133
35.5      77
30.5      59
36.5      55
38.0      49
37.5       8
37.0       1
Name: count, dtype: int64
0
--------------------------------------------------
last_years_price
599.00     3455
999.00     3446
799.00     2901
949.00     2341
579.00     2242
           ...
702.00        1
813.60        1
833.40        1
1592.10       1
258.75        1
Name: count, Length: 1430, dtype: int64
0
--------------------------------------------------
auto_renewal_score
8    50126
9    28792
Name: count, dtype: int64
0
--------------------------------------------------
status_scores
9    46256
0    11904
8    11684
7     9074
Name: count, dtype: int64
0
--------------------------------------------------
anchoring_score
9.5    28077
8.5    22313
7.5    15592
9.0    12935
8.0        1
Name: count, dtype: int64
0
--------------------------------------------------
tenure_scores
9.5    43518
8.5    13729
9.0    10389
8.0     7697
7.5     3386
7.0      199
Name: count, dtype: int64
0
--------------------------------------------------
proforma_auto_renewal
True     76526
False     2392
Name: count, dtype: int64
0
--------------------------------------------------
proforma_world_pay_token
False    57616
True     21302
Name: count, dtype: int64
0
--------------------------------------------------
proforma_date
2024-03-15    1863
2024-08-09    1712
2024-09-05    1689
2024-03-12    1650
2025-08-11    1631
              ...
2024-09-09       1
2024-08-30       1
2024-08-16       1
2024-10-17       1
2024-04-19       1
Name: count, Length: 98, dtype: int64
0
--------------------------------------------------
current_anchorings
1      22313
0      15593
2      12935
3       8219
4       4671
       ...
102        1
103        1
65         1
84         1
207        1
Name: count, Length: 90, dtype: int64
0
--------------------------------------------------
payment_timeframe
 0      25916
-1       4598
 1       4038
-2       2484
 2       2442
        ...
 142        1
 182        1
 156        1
-362        1
-140        1
Name: count, Length: 228, dtype: int64
0
--------------------------------------------------
registration_date
2019-03-25    689
2017-01-25    256
2020-02-12    136
2024-02-12    127
2011-07-13    119
             ...
2023-05-07      1
2024-06-30      1
2024-06-09      1
2024-10-05      1
2024-12-15      1
Name: count, Length: 4882, dtype: int64
0
--------------------------------------------------
proforma_account_stage
Published          52791
Membership Only    11876
Renewal Process    11688
Vetting             1741
Suspended            822
Name: count, dtype: int64
0
--------------------------------------------------
proforma_audit_status
Accredited                                                  51931
Renewal Questionnaire Received                               5012
Failed- Renewal Questionnaire not received                   4954
Renewal Questionnaire Sent                                   3419
Failed- Renewal Additional Information Not Received          2498
Failed- Initial additional info not received                 2366
Failed- Initial Questionnaire not received                   2059
Initial Questionnaire Received                               1156
1st Renewal questionnaire reminder                            939
Renewal report sent - Awaiting information                    872
Accredited - SSiP due to expire                               846
Final renewal questionnaire reminder                          696
SUSPENDED - SSiP Expired                                      359
1st Reminder - Renewal additional info                        285
Final reminder - Renewal additional info                      278
Report sent - Awaiting information                            261
Renewal additional information received                       186
SUSPENDED - 2nd reminder SSiP Expired                         185
Final Reminder (Initial) Additional Information Not Sent      155
SSiP Expired - 1st Reminder                                   141
SUSPENDED - 1st reminder SSiP Expired                         136
1st reminder initial add info                                 131
Additional information received                                22
Initial - 1st Questionnaire reminder sent                      16
Accred Due to Expire                                           13
Suspended - Insurance Out-of-Date                               1
unknown                                                         1
Name: count, dtype: int64
0
--------------------------------------------------
current_auto_renewal_flag
y    73253
n     5665
Name: count, dtype: int64
0
--------------------------------------------------
current_world_pay_token
n    50122
y    28796
Name: count, dtype: int64
0
--------------------------------------------------
renewal_score_at_release
28.0    16767
27.5     8478
27.0     8398
26.0     7426
24.5     6673
26.5     6637
25.0     5063
23.5     4504
25.5     4132
23.0     3195
24.0     2499
22.0     1732
22.5     1212
21.5     1071
20.5      957
28.2      100
21.0       20
26.7       17
27.7       16
27.2       13
24.7        4
25.2        3
25.7        1
Name: count, dtype: int64
0
--------------------------------------------------
proforma_membership_status
Accredited     57189
Member Only    12699
In Progress     9030
Name: count, dtype: int64
0
--------------------------------------------------
proforma_approved_lists
1      23017
0      14973
2      12640
3       6920
4       4895
       ...
75         1
99         1
100        1
61         1
83         1
Name: count, Length: 90, dtype: int64
0
--------------------------------------------------
tenure_years
1     11465
2      7639
3      6447
5      5551
4      5141
6      5124
7      4414
8      3963
9      3774
10     3535
11     3284
12     2950
13     2386
15     2291
16     2288
14     2201
17     1881
21     1260
18      931
20      910
19      708
22      607
0        94
23       57
24       17
Name: count, dtype: int64
0
--------------------------------------------------
band
Band B     18981
Band C1    15152
Band D     12786
Band C2    10194
Band E      6828
Band F1     5454
Band F2     3177
Band G      2194
Band A      2068
Group        682
Band H       635
Band J       529
Band I       238
Name: count, dtype: int64
0
--------------------------------------------------
prospect_renewal_date
2025-01-25    384
2025-01-31    373
2025-09-30    362
2025-02-12    289
2025-02-05    287
             ...
2024-12-27      3
2026-01-03      2
2025-01-01      2
2024-12-30      2
2026-01-01      2
Name: count, Length: 692, dtype: int64
0
--------------------------------------------------
starting_net
599     5093
799     4199
949     4106
684     3554
999     3416
        ...
5794       1
3814       1
3824       1
3589       1
585        1
Name: count, Length: 698, dtype: int64
0
--------------------------------------------------
starting_vat
119.80    5060
159.80    4174
189.80    4080
136.80    3536
199.80    3388
          ...
764.80       1
717.80       1
117.00       1
1.28         1
1.41         1
Name: count, Length: 697, dtype: int64
0
--------------------------------------------------
starting_gross
718.80     5060
958.80     4174
1138.80    4080
820.80     3536
1198.80    3388
           ...
702.00        1
640.28        1
1789.00       1
705.41        1
3299.00       1
Name: count, Length: 792, dtype: int64
0
--------------------------------------------------
starting_membership_net
500      9586
664      8458
1024     7045
1214     6575
864      6100
         ...
12487       3
4444        3
10427       2
3894        2
4173        2
Name: count, Length: 72, dtype: int64
0
--------------------------------------------------
starting_package_net
0      41166
120    12400
150     5168
85      3763
160     3505
140     3447
105     3146
190     2352
175     1378
100      998
125      835
60       364
225      294
70        98
200        4
Name: count, dtype: int64
0
--------------------------------------------------
starting_pqq_net
135     45723
99      20204
200     10894
250      1385
390       254
460       168
320       149
530        53
600        28
880        22
670         9
1230        7
1790        5
1720        5
810         3
740         3
950         3
0           3
Name: count, dtype: int64
0
--------------------------------------------------
membership_net
500.00     7446
664.00     6845
1024.00    5628
1214.00    5517
864.00     4768
           ...
1929.00       1
475.50        1
909.35        1
1679.00       1
914.00        1
Name: count, Length: 405, dtype: int64
0
--------------------------------------------------
package_net
0.00      44479
120.00    10659
150.00     3942
160.00     3069
85.00      2941
          ...
113.75        2
82.50         2
57.75         2
131.25        1
104.00        1
Name: count, Length: 83, dtype: int64
0
--------------------------------------------------
pqqnet
 135     44883
 99      20840
 200     10804
 250      1401
 390       251
 320       149
 460       130
 530        65
 9          59
 0          43
 600        33
 29         28
 49         27
 880        22
 85         21
-65         17
-35         13
 69         12
-71         10
 45          9
-101         8
-15          8
 670         6
-51          5
 25          5
-31          5
 270         5
 1720        5
-131         4
 65          4
-91          4
 36          4
 150         3
 810         3
 740         3
 950         3
 1860        3
-11          3
-115         3
-50          3
 70          2
-95          2
-36          2
 1790        2
 105         2
 400         2
 30          2
Name: count, dtype: int64
0
--------------------------------------------------
prospect_outcome
Won        68967
Churned     9358
Open         593
Name: count, dtype: int64
0
--------------------------------------------------
payment_method
Bacs         37722
Card         30354
Unknown       9951
World Pay      848
Cheque          43
Name: count, dtype: int64
0
--------------------------------------------------
total_amount
599.0     4198
799.0     3661
949.0     3187
999.0     2681
684.0     2569
          ...
702.0        1
813.6        1
833.4        1
1592.1       1
1015.5       1
Name: count, Length: 1303, dtype: int64
0
--------------------------------------------------
tenure_group
4+    53273
1     11559
2      7639
3      6447
Name: count, dtype: int64
0
--------------------------------------------------
last_renewal
2024-02-01    3826
2023-10-01    3600
2024-01-01    3533
2024-11-01    3529
2023-11-01    3520
              ...
2025-06-09       1
2025-10-05       1
2025-11-30       1
2024-08-12       1
2025-12-15       1
Name: count, Length: 560, dtype: int64
0
--------------------------------------------------
last_band
Band B     19081
Band C1    15499
Band D     12588
Band C2    10554
Band E      6471
Band F1     4086
Band F2     2396
Band G      2160
Band A      2117
Band F      1863
Group        710
Band H       637
Band J       406
Band I       350
Name: count, dtype: int64
0
--------------------------------------------------
last_total_net_paid
579.0     3726
999.0     3338
684.0     2885
949.0     2740
749.0     2725
          ...
511.1        1
2004.1       1
2487.0       1
1729.2       1
3299.0       1
Name: count, Length: 823, dtype: int64
0
--------------------------------------------------
last_connections
0      23318
1      18468
2      10436
3       6550
4       4576
       ...
98         1
97         1
84         1
86         1
108        1
Name: count, Length: 95, dtype: int64
0
--------------------------------------------------
anchor_group
1              23017
4 to 9         15099
Independent    14973
2              12640
3               6920
10+             6269
Name: count, dtype: int64
0
--------------------------------------------------
renewal_year
2025    42379
2024    31749
2026     4790
Name: count, dtype: int64
0
--------------------------------------------------
is_first_year
0    67134
1    11784
Name: count, dtype: int64
0
--------------------------------------------------
has_discount
0    65241
1    13677
Name: count, dtype: int64
0
--------------------------------------------------
discount_pct
0.00    65241
0.20     6639
0.30     2072
0.50     1889
0.40     1175
0.10      823
0.15      713
0.35      223
0.25      113
0.45       30
Name: count, dtype: int64
0
--------------------------------------------------
call_id
595000000000.0    2684
511000000000.0    2625
538000000000.0    2389
539000000000.0    2387
594000000000.0    2344
507000000000.0    2239
596000000000.0    2232
591000000000.0    2227
509000000000.0    2182
508000000000.0    2143
565000000000.0    2065
592000000000.0    2025
622000000000.0    1954
510000000000.0    1946
513000000000.0    1875
512000000000.0    1867
683000000000.0    1815
590000000000.0    1794
682000000000.0    1791
685000000000.0    1753
688000000000.0    1711
687000000000.0    1626
679000000000.0    1588
694000000000.0    1540
693000000000.0    1534
506000000000.0    1530
689000000000.0    1524
623000000000.0    1488
651000000000.0    1467
686000000000.0    1458
597000000000.0    1434
680000000000.0    1367
626000000000.0    1340
684000000000.0    1331
677000000000.0    1275
692000000000.0    1264
681000000000.0    1260
540000000000.0    1251
625000000000.0    1191
564000000000.0    1187
678000000000.0    1097
690000000000.0    1006
505000000000.0     856
624000000000.0     848
652000000000.0     808
593000000000.0     797
695000000000.0     721
537000000000.0     464
566000000000.0     395
691000000000.0     293
194000000000.0     274
676000000000.0     272
Unknown            240
193000000000.0     144
Name: count, dtype: int64
0
--------------------------------------------------
call_direction
OUT_BOUND    67380
IN_BOUND     11298
Unknown        240
Name: count, dtype: int64
0
--------------------------------------------------
call_date
2025-01-17 00:00:00    353
2024-09-24 00:00:00    331
2024-07-01 00:00:00    328
2025-01-23 00:00:00    327
2025-10-10 00:00:00    326
                      ...
2025-07-10 00:00:00     61
2025-12-17 00:00:00     47
2025-03-25 00:00:00     47
2025-12-23 00:00:00     30
2025-12-24 00:00:00      1
Name: count, Length: 466, dtype: int64
0
--------------------------------------------------
membership_renewal_decision
No         45245
Unknown    30797
Yes         2876
Name: count, dtype: int64
0
--------------------------------------------------
serious_complaint
No         46471
Unknown    32202
Yes          245
Name: count, dtype: int64
0
--------------------------------------------------
other_complaint
No         37654
Unknown    32206
Yes         9058
Name: count, dtype: int64
0
--------------------------------------------------
discussion_on_price_increase
No         44828
Unknown    30202
Yes         3888
Name: count, dtype: int64
0
--------------------------------------------------
renewal_impact_due_to_price_increase
No         47089
Unknown    30222
Yes         1607
Name: count, dtype: int64
0
--------------------------------------------------
discount_or_waiver_requested
No         47286
Unknown    30223
Yes         1409
Name: count, dtype: int64
0
--------------------------------------------------
call_reschedule_request
No         47950
Unknown    29926
Yes         1042
Name: count, dtype: int64
0
--------------------------------------------------
agent_flagged_membership_status_alert
No         32624
Unknown    29926
Yes        16368
Name: count, dtype: int64
0
--------------------------------------------------
agent_renewal_initiation
Unknown    29926
No         26030
Yes        22962
Name: count, dtype: int64
0
--------------------------------------------------
explicit_competitor_mention
No         48246
Unknown    29880
Yes          792
Name: count, dtype: int64
0
--------------------------------------------------
explicit_switching_intent
No         49015
Unknown    29880
Yes           23
Name: count, dtype: int64
0
--------------------------------------------------
mentioned_competitors
No         45701
Unknown    29881
Yes         3336
Name: count, dtype: int64
0
--------------------------------------------------
price_switching_mentioned
No         47660
Unknown    29887
Yes         1371
Name: count, dtype: int64
0
--------------------------------------------------
competitor_value_comparison
Not Applicable    46370
Unknown           29899
Not Discussed      1704
Better Value        611
Similar Value       334
Name: count, dtype: int64
0
--------------------------------------------------
competitor_benefits_mentioned
Not Applicable    36175
Unknown           31791
Not Discussed      8785
Discounts          1272
Better Service      895
Name: count, dtype: int64
0
--------------------------------------------------
topic_introduced_by
Not Discussed    37497
Unknown          29855
Agent             8738
Customer          2828
Name: count, dtype: int64
0
--------------------------------------------------
percentage_price_increase_mentioned
No               48339
Unknown          29855
Yes                382
Not Discussed      342
Name: count, dtype: int64
0
--------------------------------------------------
monetary_price_increase_mentioned
No               47019
Unknown          29855
Yes               1702
Not Discussed      342
Name: count, dtype: int64
0
--------------------------------------------------
price_range_mentioned
Not Discussed    47080
Unknown          29855
589.0               71
899.0               20
140.0               20
                 ...
766.5                1
932.0                1
634.0                1
521.0                1
7.34                 1
Name: count, Length: 767, dtype: int64
0
--------------------------------------------------
customer_asked_for_justification
No               45814
Unknown          29855
Yes               2907
Not Discussed      342
Name: count, dtype: int64
0
--------------------------------------------------
customer_response
Neutral          32934
Unknown          29855
Not Discussed    13117
Negative          2612
Positive           400
Name: count, dtype: int64
0
--------------------------------------------------
desire_to_cancel
Unknown              29877
Renewed              24247
Not Discussed        20817
Desired to Cancel     3977
Name: count, dtype: int64
0
--------------------------------------------------
discount_offered
No               46098
Unknown          29855
Yes               2623
Not Discussed      342
Name: count, dtype: int64
0
--------------------------------------------------
call_number
2.0     16909
1.0     14281
3.0     13417
4.0      9639
5.0      6532
        ...
58.0        1
42.0        1

In [17]:
for col in df_filtered.columns:
    print(col)

co_ref
renewal_month
sustainability_score
total_renewal_score_new
last_years_price
auto_renewal_score
status_scores
anchoring_score
tenure_scores
proforma_auto_renewal
proforma_world_pay_token
proforma_date
current_anchorings
payment_timeframe
registration_date
proforma_account_stage
proforma_audit_status
current_auto_renewal_flag
current_world_pay_token
renewal_score_at_release
proforma_membership_status
proforma_approved_lists
tenure_years
band
prospect_renewal_date
starting_net
starting_vat
starting_gross
starting_membership_net
starting_package_net
starting_pqq_net
membership_net
package_net
pqqnet
prospect_outcome
payment_method
total_amount
tenure_group
last_renewal
last_band
last_total_net_paid
last_connections
anchor_group
renewal_year
is_first_year
has_discount
discount_pct
call_id
call_direction
call_date
membership_renewal_decision
serious_complaint
other_complaint
discussion_on_price_increase
renewal_impact_due_to_price_increase
discount_or_waiver_requested
call_reschedule_request
agent_flagged_membership_status_alert
agent_renewal_initiation
explicit_competitor_mention
explicit_switching_intent
mentioned_competitors
price_switching_mentioned
competitor_value_comparison
competitor_benefits_mentioned
topic_introduced_by
percentage_price_increase_mentioned
monetary_price_increase_mentioned
price_range_mentioned
customer_asked_for_justification
customer_response
desire_to_cancel
discount_offered
call_number
time_to_renewal
crm_accreditation_completed
crm_timely_completion
crm_progress_towards_accreditation
crm_delays_in_accreditation
crm_contractor_suggested_leave
crm_contractor_engagement
crm_contractor_sentiment
crm_contractor_sentiment_score
crm_dts_or_ssip_mentioned
crm_customer_payment_intention
crm_competitors_mentioned
crm_membership_level
crm_platform_issues_raised
crm_agent_chased_contractor
crm_agent_chase_count
crm_accreditation_issues
crm_membership_overdue
crm_auto_renewal_status
crm_dissatisified_with_renewal_price
crm_customer_complained
crm_refund_mentioned
crm_negative_customer_experience
crm_dissatisfaction_with_support
crm_financial_hardship_mentioned
year
sentiment_score_missing
contact_id
call_date_cc
direction
cc_care_package
cc_care_package_discussed
cc_urgency_getting_on_site
cc_external_consultant
cc_agent_cross_sell_attempt
cc_customer_issues_concerns
cc_business_struggles_financial_hardship
cc_call_initiated_by
cc_questionnaire_completion
cc_chasing_response
cc_issues_within_questionnaire
cc_login_issues
cc_platform_issues
cc_dissatisfaction_time_to_complete
cc_process_complexity_concerns
cc_questions_harder_than_expected
cc_dissatisfaction_support
cc_contractor_sentiment
cc_contractor_sentiment_start_score
cc_contractor_sentiment_end_score
cc_contractor_sentiment_overall_score
cc_pricing_mentioned
cc_pricing_sentiment_impact
cc_refund_discussed
cc_contractor_suggest_leave
cc_contractor_complained

In [18]:
df_filtered.to_csv("../../data/processed/data_cleared.csv", index=False)

In [19]:
# import seaborn as sns

# import matplotlib.pyplot as plt

# # Select only numeric columns
# numeric_df = df_filtered.select_dtypes(include=['number'])

# # Calculate correlation matrix
# correlation_matrix = numeric_df.corr()

# # Get correlations with target variable (if it's numeric, otherwise skip)
# if 'prospect_outcome' in correlation_matrix.columns:
#     target_corr = correlation_matrix['prospect_outcome'].sort_values(ascending=False)
#     print(target_corr)
    
#     # Create heatmap
#     plt.figure(figsize=(12, 8))
#     sns.heatmap(target_corr.to_frame(), annot=True, cmap='coolwarm', center=0, cbar_kws={'label': 'Correlation'})
#     plt.title('Correlation of Features with prospect_outcome')
#     plt.tight_layout()
#     plt.show()

In [20]:
# # Columns to remove: identifiers, dates used for filtering, derived scores that may cause leakage, proforma statuses, and other non-beneficial columns
# columns_to_drop = [
#     'co_ref',
#     'renewal_month',
#     'proforma_auto_renewal',
#     'proforma_world_pay_token',
#     'proforma_date',
#     'current_anchorings',
#     'payment_timeframe',
#     'registration_date',
#     'proforma_account_stage',
#     'proforma_audit_status',
#     'current_world_pay_token',
#     'renewal_score_at_release',
#     'proforma_membership_status',
#     'proforma_approved_lists',
#     'prospect_renewal_date',
#     'starting_net',
#     'starting_vat',
#     'starting_gross',
#     'starting_membership_net',
#     'starting_package_net',
#     'starting_pqq_net',
#     'renewal_year',
#     'call_id',
#     'call_date',
#     'call_number',
#     'year',
#     'sentiment_score_missing',
#     'contact_id',
#     'call_date_cc'
# ]

# df_filtered = df_filtered.drop(columns=columns_to_drop)

In [21]:
from autoviz.AutoViz_Class import AutoViz_Class

def run_prospect_eda(df_filtered):
    """
    Automated EDA for df_filtered (78,946 rows, 130 columns)
    Target Variable: prospect_outcome
    """
    AV = AutoViz_Class()
    
    # Executing AutoViz with target-specific settings
    dft = AV.AutoViz(
        filename="",
        sep=",",
        depVar="prospect_outcome",    # Your specific target column
        dfte=df_filtered,             # Your cleaned dataframe
        header=0,
        verbose=1,                    # Provides data cleaning insights
        lowess=False,                 # Disabled for speed with 79k rows
        chart_format="html",          # Best for viewing 130 columns clearly
        max_rows_analyzed=80000,      
        max_cols_analyzed=135         # Slightly higher to ensure all 130 are included
    )
    return dft

# To run the analysis, just call:
run_prospect_eda(df_filtered)

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Shape of your Data Set loaded: (78918, 130)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Removing ['call_id', 'call_date', 'call_number', 'crm_contractor_sentiment_score', 'crm_agent_chase_count', 'crm_auto_renewal_status', 'year', 'sentiment_score_missing', 'contact_id', 'call_date_cc', 'cc_contractor_sentiment_start_score', 'cc_contractor_sentiment_end_score', 'cc_contractor_sentiment_overall_score'] column(s) due to mixed data type detected...
co_ref of type=str is not classified
renewal_month of type=datetime64[us] is not classified
proforma_date of type=datetime64[us] is not classified
registration_date of type=datetime64[us] is not classified
proforma_account_stage of type=str is not classified
proforma_audit_status of type=str is not classified
current_auto_renewal_flag of type=str is not classified
current_world_pay_token of type=str is not classified
proforma_membership_status of type=str is not classified
band of type=str is not classified
prospect_renewal_date of type=datetime64[us] is not classified
payment_method of type=str is not classified
tenure_group of type=str is not classified
last_renewal of type=str is not classified
last_band of type=str is not classified
anchor_group of type=str is not classified
call_direction of type=str is not classified
membership_renewal_decision of type=str is not classified
serious_complaint of type=str is not classified
other_complaint of type=str is not classified
discussion_on_price_increase of type=str is not classified
renewal_impact_due_to_price_increase of type=str is not classified
discount_or_waiver_requested of type=str is not classified
call_reschedule_request of type=str is not classified
agent_flagged_membership_status_alert of type=str is not classified
agent_renewal_initiation of type=str is not classified
explicit_competitor_mention of type=str is not classified
explicit_switching_intent of type=str is not classified
mentioned_competitors of type=str is not classified
price_switching_mentioned of type=str is not classified
competitor_value_comparison of type=str is not classified
competitor_benefits_mentioned of type=str is not classified
topic_introduced_by of type=str is not classified
percentage_price_increase_mentioned of type=str is not classified
monetary_price_increase_mentioned of type=str is not classified
price_range_mentioned of type=str is not classified
customer_asked_for_justification of type=str is not classified
customer_response of type=str is not classified
desire_to_cancel of type=str is not classified
discount_offered of type=str is not classified
time_to_renewal of type=str is not classified
crm_accreditation_completed of type=str is not classified
crm_timely_completion of type=str is not classified
crm_progress_towards_accreditation of type=str is not classified
crm_delays_in_accreditation of type=str is not classified
crm_contractor_suggested_leave of type=str is not classified
crm_contractor_engagement of type=str is not classified
crm_contractor_sentiment of type=str is not classified
crm_dts_or_ssip_mentioned of type=str is not classified
crm_customer_payment_intention of type=str is not classified
crm_competitors_mentioned of type=str is not classified
crm_membership_level of type=str is not classified
crm_platform_issues_raised of type=str is not classified
crm_agent_chased_contractor of type=str is not classified
crm_accreditation_issues of type=str is not classified
crm_membership_overdue of type=str is not classified
crm_dissatisified_with_renewal_price of type=str is not classified
crm_customer_complained of type=str is not classified
crm_refund_mentioned of type=str is not classified
crm_negative_customer_experience of type=str is not classified
crm_dissatisfaction_with_support of type=str is not classified
crm_financial_hardship_mentioned of type=str is not classified
direction of type=str is not classified
cc_care_package of type=str is not classified
cc_care_package_discussed of type=str is not classified
cc_urgency_getting_on_site of type=str is not classified
cc_external_consultant of type=str is not classified
cc_agent_cross_sell_attempt of type=str is not classified
cc_customer_issues_concerns of type=str is not classified
cc_business_struggles_financial_hardship of type=str is not classified
cc_call_initiated_by of type=str is not classified
cc_questionnaire_completion of type=str is not classified
cc_chasing_response of type=str is not classified
cc_issues_within_questionnaire of type=str is not classified
cc_login_issues of type=str is not classified
cc_platform_issues of type=str is not classified
cc_dissatisfaction_time_to_complete of type=str is not classified
cc_process_complexity_concerns of type=str is not classified
cc_questions_harder_than_expected of type=str is not classified
cc_dissatisfaction_support of type=str is not classified
cc_contractor_sentiment of type=str is not classified
cc_pricing_mentioned of type=str is not classified
cc_pricing_sentiment_impact of type=str is not classified
cc_refund_discussed of type=str is not classified
cc_contractor_suggest_leave of type=str is not classified
cc_contractor_complained of type=str is not classified
    Number of Numeric Columns =  13
    Number of Integer-Categorical Columns =  12
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  2
    Number of Numeric-Boolean Columns =  3
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  13
No of columns classified 43 does not match 129 total cols. Continuing...
 Missing columns = ['co_ref', 'renewal_month', 'proforma_date', 'registration_date', 'proforma_account_stage', 'proforma_audit_status', 'current_auto_renewal_flag', 'current_world_pay_token', 'proforma_membership_status', 'band', 'prospect_renewal_date', 'payment_method', 'tenure_group', 'last_renewal', 'last_band', 'anchor_group', 'call_direction', 'membership_renewal_decision', 'serious_complaint', 'other_complaint', 'discussion_on_price_increase', 'renewal_impact_due_to_price_increase', 'discount_or_waiver_requested', 'call_reschedule_request', 'agent_flagged_membership_status_alert', 'agent_renewal_initiation', 'explicit_competitor_mention', 'explicit_switching_intent', 'mentioned_competitors', 'price_switching_mentioned', 'competitor_value_comparison', 'competitor_benefits_mentioned', 'topic_introduced_by', 'percentage_price_increase_mentioned', 'monetary_price_increase_mentioned', 'price_range_mentioned', 'customer_asked_for_justification', 'customer_response', 'desire_to_cancel', 'discount_offered', 'time_to_renewal', 'crm_accreditation_completed', 'crm_timely_completion', 'crm_progress_towards_accreditation', 'crm_delays_in_accreditation', 'crm_contractor_suggested_leave', 'crm_contractor_engagement', 'crm_contractor_sentiment', 'crm_dts_or_ssip_mentioned', 'crm_customer_payment_intention', 'crm_competitors_mentioned', 'crm_membership_level', 'crm_platform_issues_raised', 'crm_agent_chased_contractor', 'crm_accreditation_issues', 'crm_membership_overdue', 'crm_dissatisified_with_renewal_price', 'crm_customer_complained', 'crm_refund_mentioned', 'crm_negative_customer_experience', 'crm_dissatisfaction_with_support', 'crm_financial_hardship_mentioned', 'direction', 'cc_care_package', 'cc_care_package_discussed', 'cc_urgency_getting_on_site', 'cc_external_consultant', 'cc_agent_cross_sell_attempt', 'cc_customer_issues_concerns', 'cc_business_struggles_financial_hardship', 'cc_call_initiated_by', 'cc_questionnaire_completion', 'cc_chasing_response', 'cc_issues_within_questionnaire', 'cc_login_issues', 'cc_platform_issues', 'cc_dissatisfaction_time_to_complete', 'cc_process_complexity_concerns', 'cc_questions_harder_than_expected', 'cc_dissatisfaction_support', 'cc_contractor_sentiment', 'cc_pricing_mentioned', 'cc_pricing_sentiment_impact', 'cc_refund_discussed', 'cc_contractor_suggest_leave', 'cc_contractor_complained']
        13 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['call_id', 'call_date', 'call_number', 'crm_contractor_sentiment_score', 'crm_agent_chase_count', 'crm_auto_renewal_status', 'year', 'sentiment_score_missing', 'contact_id', 'call_date_cc', 'cc_contractor_sentiment_start_score', 'cc_contractor_sentiment_end_score', 'cc_contractor_sentiment_overall_score']

################ Multi_Classification problem #####################
   Total columns > 30, too numerous to print.

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

Saving scatterplots in HTML format
  0%|          | 0/13 [00:00<?, ?it/s]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

  8%|▊         | 1/13 [00:16<03:17, 16.47s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 15%|█▌        | 2/13 [00:33<03:01, 16.52s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 23%|██▎       | 3/13 [00:49<02:46, 16.60s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 31%|███       | 4/13 [01:05<02:26, 16.33s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 38%|███▊      | 5/13 [01:21<02:09, 16.16s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 46%|████▌     | 6/13 [01:37<01:53, 16.15s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 54%|█████▍    | 7/13 [01:53<01:36, 16.11s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 62%|██████▏   | 8/13 [02:09<01:20, 16.10s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 69%|██████▉   | 9/13 [02:25<01:04, 16.05s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 77%|███████▋  | 10/13 [02:41<00:48, 16.10s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 85%|████████▍ | 11/13 [02:57<00:32, 16.07s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

 92%|█████████▏| 12/13 [03:13<00:16, 16.08s/it]

WARNING:param.Scatter: Chart elements should only be supplied a single kdim

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='ac3b92d7-ee4c-4ea1-896c-2635cd1ba933', ...)

Saving pair_scatters in HTML format

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='5e50586b-6511-4cfe-9a6c-5a88cdd53519', ...)

MemoryError: