## Import Libraries

Import necessary libraries for data manipulation and regular expressions.

In [1]:
import pandas as pd
import re

## Load Data

Load the raw renewal calls data from CSV file.

In [2]:
df = pd.read_csv('../../data/raw/renewal_calls.csv')

C:\Users\GopikaS\AppData\Local\Temp\ipykernel_10444\1943843009.py:1: DtypeWarning: Columns (0: Churn_Category, 1: Complaint_Category, 2: Customer_Reaction_Category, 3: Agent_Renewal_Pitch_Category, 4: Customer_Renewal_Response_Category, 5: Agent_Response_Category, 6: Membership_Renewal_Decision, 7: Serious_Complaint, 8: Other_Complaint, 9: Discussion_on_Price_Increase, 10: Renewal_Impact_Due_to_Price_Increase, 11: Discount_or_Waiver_Requested, 12: Call_Reschedule_Request, 13: Agent_Flagged_Membership_Status_Alert, 14: Agent_Renewal_Initiation, 15: Explicit_Competitor_Mention, 16: Explicit_Switching_Intent, 17: Mentioned_Competitors, 18: Price_Switching_Mentioned, 19: Competitor_Value_Comparison, 20: Competitor_Benefits_Mentioned, 21: Topic_Introduced_By, 22: Percentage_Price_Increase_Mentioned, 23: Monetary_Price_Increase_Mentioned, 24: Price_Range_Mentioned, 25: Customer_Asked_For_Justification, 26: Customer_Response, 27: Desire_To_Cancel, 28: Discount_Offered, 29: Justification_Category, 30: Reason_For_Renewal_Category, 31: Agent_Response_To_Cancel_Category, 32: Argument_That_Convinced_Customer_to_Stay_Category) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../../data/raw/renewal_calls.csv')

## Set Display Options

Configure pandas to display all columns for better data inspection.

In [3]:
pd.set_option('display.max_columns', None)

## Initial Data Inspection

Display the dataframe to get an overview of the data and its columns.

In [4]:
df

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,Membership_Renewal_Decision,Serious_Complaint,Other_Complaint,Discussion_on_Price_Increase,Renewal_Impact_Due_to_Price_Increase,Discount_or_Waiver_Requested,Call_Reschedule_Request,Agent_Flagged_Membership_Status_Alert,Agent_Renewal_Initiation,Explicit_Competitor_Mention,Unnamed: 20,Explicit_Switching_Intent,Mentioned_Competitors,Price_Switching_Mentioned,Competitor_Value_Comparison,Competitor_Benefits_Mentioned,Topic_Introduced_By,Percentage_Price_Increase_Mentioned,Monetary_Price_Increase_Mentioned,Price_Range_Mentioned,Customer_Asked_For_Justification,Customer_Response,Desire_To_Cancel,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,No,No,No,No,Yes,No,No,Yes,No,NaN,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,No,No,No,No,No,No,No,No,No,NaN,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,Yes,Yes,No,NaN,No,No,No,Not Applicable,Better service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,No,Yes,No,NaN,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,NaN,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186530,5.050000e+11,Outbound,IT3598,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186531,5.050000e+11,Outbound,ZD8460,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186532,5.050000e+11,Outbound,PX0289,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186533,5.050000e+11,Outbound,IL3891,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024

## Remove Unnamed Columns

Remove any unnamed columns that may have been created during CSV import.

In [5]:
# Using loc and a boolean mask
df = df.loc[:, ~df.columns.str.contains('^Unnamed', case=False)]

# OR using the drop method with a list comprehension
df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True)

## Data After Column Removal

Display the dataframe after removing unnamed columns.

In [6]:
df

,Call_ID,Call_Direction,Co_Ref,Call_Date,Churn_Category,Complaint_Category,Customer_Reaction_Category,Agent_Renewal_Pitch_Category,Customer_Renewal_Response_Category,Agent_Response_Category,Membership_Renewal_Decision,Serious_Complaint,Other_Complaint,Discussion_on_Price_Increase,Renewal_Impact_Due_to_Price_Increase,Discount_or_Waiver_Requested,Call_Reschedule_Request,Agent_Flagged_Membership_Status_Alert,Agent_Renewal_Initiation,Explicit_Competitor_Mention,Explicit_Switching_Intent,Mentioned_Competitors,Price_Switching_Mentioned,Competitor_Value_Comparison,Competitor_Benefits_Mentioned,Topic_Introduced_By,Percentage_Price_Increase_Mentioned,Monetary_Price_Increase_Mentioned,Price_Range_Mentioned,Customer_Asked_For_Justification,Customer_Response,Desire_To_Cancel,Discount_Offered,Justification_Category,Reason_For_Renewal_Category,Agent_Response_To_Cancel_Category,Argument_That_Convinced_Customer_to_Stay_Category,Analysed_Call,Call_Number,Call_Year
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186530,5.050000e+11,Outbound,IT3598,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186531,5.050000e+11,Outbound,ZD8460,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186532,5.050000e+11,Outbound,PX0289,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186533,5.050000e+11,Outbound,IL3891,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024

## Import Custom Utilities

Add the project root to the Python path and import custom utility functions for data processing.

In [7]:
import sys
import os
sys.path.append(os.path.abspath('../..'))

## Convert Column Names to Snake Case

Standardize column names by converting them to snake_case format using custom utility function.

In [8]:
from src import utils
df = utils.convert_columns_to_snake_case(df)

## Data After Column Name Standardization

Display the dataframe with standardized column names in snake_case.

In [9]:
df

,call_id,call_direction,co_ref,call_date,churn_category,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,justification_category,reason_for_renewal_category,agent_response_to_cancel_category,argument_that_convinced_customer_to_stay_category,analysed_call,call_number,call_year
0,5.950000e+11,Outbound,UB0899,29-01-2025,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,26-02-2025,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,2,2025
2,5.950000e+11,Outbound,BP5009,24-01-2025,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,09-06-2025,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,1,2025
4,5.370000e+11,Outbound,ZL7978,20-08-2024,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1.0,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186530,5.050000e+11,Outbound,IT3598,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186531,5.050000e+11,Outbound,ZD8460,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186532,5.050000e+11,Outbound,PX0289,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024
186533,5.050000e+11,Outbound,IL3891,02-04-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2024

## Check for Duplicate Columns

Identify any columns that contain identical data values.

In [10]:
duplicates = []
cols = df.columns.tolist()

for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        c1, c2 = cols[i], cols[j]
        if df[c1].astype(str).equals(df[c2].astype(str)):
            duplicates.append((c1, c2))

for c1, c2 in duplicates:
    print(f"{c1}  ==  {c2}")

## Check for Duplicate Rows

Count the number of duplicate rows in the dataset.

In [11]:
duplicate_mask = df.duplicated()
duplicate_count = duplicate_mask.sum()
    
print(f"Total duplicate rows: {duplicate_count}")

Total duplicate rows: 28812

## Remove Duplicate Rows

Remove duplicate rows from the dataframe to ensure data quality.

In [12]:
df = df.drop_duplicates()

## Data Shape After Deduplication

Check the dimensions of the dataframe after removing duplicate rows.

In [13]:
df.shape

(157722, 40)

## Check Data Types

Examine the data types of each column in the dataframe.

In [14]:
df.dtypes

call_id                                              float64
call_direction                                           str
co_ref                                                   str
call_date                                                str
churn_category                                           str
complaint_category                                       str
customer_reaction_category                               str
agent_renewal_pitch_category                             str
customer_renewal_response_category                       str
agent_response_category                                  str
membership_renewal_decision                              str
serious_complaint                                        str
other_complaint                                          str
discussion_on_price_increase                             str
renewal_impact_due_to_price_increase                     str
discount_or_waiver_requested                             str
call_reschedule_request                                  str
agent_flagged_membership_status_alert                    str
agent_renewal_initiation                                 str
explicit_competitor_mention                              str
explicit_switching_intent                                str
mentioned_competitors                                    str
price_switching_mentioned                                str
competitor_value_comparison                              str
competitor_benefits_mentioned                            str
topic_introduced_by                                      str
percentage_price_increase_mentioned                      str
monetary_price_increase_mentioned                        str
price_range_mentioned                                    str
customer_asked_for_justification                         str
customer_response                                        str
desire_to_cancel                                         str
discount_offered                                         str
justification_category                                   str
reason_for_renewal_category                              str
agent_response_to_cancel_category                        str
argument_that_convinced_customer_to_stay_category        str
analysed_call                                        float64
call_number                                            int64
call_year                                              int64
dtype: object

## Convert Data Types

Convert call_date column to datetime type and analysed_call to integer type.

In [15]:
df['call_date'] = pd.to_datetime(df['call_date'])
df['analysed_call'] = df['analysed_call'].astype('Int64')

C:\Users\GopikaS\AppData\Local\Temp\ipykernel_10444\2369527118.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['call_date'] = pd.to_datetime(df['call_date'])

## Verify Data Types After Conversion

Check data types after converting call_date and analysed_call columns.

In [16]:
df.dtypes

call_id                                                     float64
call_direction                                                  str
co_ref                                                          str
call_date                                            datetime64[us]
churn_category                                                  str
complaint_category                                              str
customer_reaction_category                                      str
agent_renewal_pitch_category                                    str
customer_renewal_response_category                              str
agent_response_category                                         str
membership_renewal_decision                                     str
serious_complaint                                               str
other_complaint                                                 str
discussion_on_price_increase                                    str
renewal_impact_due_to_price_increase                            str
discount_or_waiver_requested                                    str
call_reschedule_request                                         str
agent_flagged_membership_status_alert                           str
agent_renewal_initiation                                        str
explicit_competitor_mention                                     str
explicit_switching_intent                                       str
mentioned_competitors                                           str
price_switching_mentioned                                       str
competitor_value_comparison                                     str
competitor_benefits_mentioned                                   str
topic_introduced_by                                             str
percentage_price_increase_mentioned                             str
monetary_price_increase_mentioned                               str
price_range_mentioned                                           str
customer_asked_for_justification                                str
customer_response                                               str
desire_to_cancel                                                str
discount_offered                                                str
justification_category                                          str
reason_for_renewal_category                                     str
agent_response_to_cancel_category                               str
argument_that_convinced_customer_to_stay_category               str
analysed_call                                                 Int64
call_number                                                   int64
call_year                                                     int64
dtype: object

## Data After Type Conversion

Display the dataframe after converting data types.

In [17]:
df

,call_id,call_direction,co_ref,call_date,churn_category,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,justification_category,reason_for_renewal_category,agent_response_to_cancel_category,argument_that_convinced_customer_to_stay_category,analysed_call,call_number,call_year
0,5.950000e+11,Outbound,UB0899,2025-01-29,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,2025-02-26,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,2,2025
2,5.950000e+11,Outbound,BP5009,2025-01-24,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,2025-06-09,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
4,5.370000e+11,Outbound,ZL7978,2024-08-20,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186530,5.050000e+11,Outbound,IT3598,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186531,5.050000e+11,Outbound,ZD8460,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186532,5.050000e+11,Outbound,PX0289,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186533,5.050000e+11,Outbound,IL3891,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024

## Format Call Date

Format the call_date column to a consistent YYYY-MM-DD string format.

In [18]:
df['call_date'] = pd.to_datetime(df['call_date'], dayfirst=True).dt.strftime('%Y-%m-%d')

## Data After Date Formatting

Display the dataframe after formatting the call_date column.

In [19]:
df

,call_id,call_direction,co_ref,call_date,churn_category,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,justification_category,reason_for_renewal_category,agent_response_to_cancel_category,argument_that_convinced_customer_to_stay_category,analysed_call,call_number,call_year
0,5.950000e+11,Outbound,UB0899,2025-01-29,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,2025-02-26,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,2,2025
2,5.950000e+11,Outbound,BP5009,2025-01-24,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,2025-06-09,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
4,5.370000e+11,Outbound,ZL7978,2024-08-20,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186530,5.050000e+11,Outbound,IT3598,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186531,5.050000e+11,Outbound,ZD8460,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186532,5.050000e+11,Outbound,PX0289,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186533,5.050000e+11,Outbound,IL3891,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024

## Check for Missing Values

Count the number of missing values in each column.

In [20]:
df.isnull().sum()

call_id                                                   0
call_direction                                            0
co_ref                                                 4453
call_date                                                 0
churn_category                                       149821
complaint_category                                   138728
customer_reaction_category                           134736
agent_renewal_pitch_category                         103985
customer_renewal_response_category                   103411
agent_response_category                              103743
membership_renewal_decision                           71583
serious_complaint                                     73805
other_complaint                                       73806
discussion_on_price_increase                          70123
renewal_impact_due_to_price_increase                  70152
discount_or_waiver_requested                          70152
call_reschedule_request                               69579
agent_flagged_membership_status_alert                 69579
agent_renewal_initiation                              69579
explicit_competitor_mention                           69453
explicit_switching_intent                             69453
mentioned_competitors                                 69451
price_switching_mentioned                             69495
competitor_value_comparison                           69492
competitor_benefits_mentioned                         71579
topic_introduced_by                                   69436
percentage_price_increase_mentioned                   69436
monetary_price_increase_mentioned                     69436
price_range_mentioned                                 69436
customer_asked_for_justification                      69436
customer_response                                     69436
desire_to_cancel                                      69439
discount_offered                                      69436
justification_category                               144642
reason_for_renewal_category                          141587
agent_response_to_cancel_category                    152795
argument_that_convinced_customer_to_stay_category    155904
analysed_call                                         69413
call_number                                               0
call_year                                                 0
dtype: int64

## Remove Rows with Missing Customer Reference

Remove rows where co_ref (customer reference) is missing as it's a key identifier.

In [21]:
df = df[df['co_ref'].notna()]

## Verify Missing Values After Removal

Check missing values after removing rows with missing customer reference.

In [22]:
df.isnull().sum()

call_id                                                   0
call_direction                                            0
co_ref                                                    0
call_date                                                 0
churn_category                                       145595
complaint_category                                   135320
customer_reaction_category                           131194
agent_renewal_pitch_category                         101259
customer_renewal_response_category                   100765
agent_response_category                              101088
membership_renewal_decision                           70634
serious_complaint                                     72837
other_complaint                                       72838
discussion_on_price_increase                          69252
renewal_impact_due_to_price_increase                  69278
discount_or_waiver_requested                          69278
call_reschedule_request                               68751
agent_flagged_membership_status_alert                 68751
agent_renewal_initiation                              68751
explicit_competitor_mention                           68633
explicit_switching_intent                             68633
mentioned_competitors                                 68631
price_switching_mentioned                             68673
competitor_value_comparison                           68670
competitor_benefits_mentioned                         70682
topic_introduced_by                                   68617
percentage_price_increase_mentioned                   68617
monetary_price_increase_mentioned                     68617
price_range_mentioned                                 68617
customer_asked_for_justification                      68617
customer_response                                     68617
desire_to_cancel                                      68620
discount_offered                                      68617
justification_category                               140689
reason_for_renewal_category                          137794
agent_response_to_cancel_category                    148465
argument_that_convinced_customer_to_stay_category    151524
analysed_call                                         68594
call_number                                               0
call_year                                                 0
dtype: int64

## Data After Removing Missing Customer References

Display the dataframe after removing rows with missing customer reference.

In [23]:
df

,call_id,call_direction,co_ref,call_date,churn_category,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,justification_category,reason_for_renewal_category,agent_response_to_cancel_category,argument_that_convinced_customer_to_stay_category,analysed_call,call_number,call_year
0,5.950000e+11,Outbound,UB0899,2025-01-29,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,2025-02-26,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,2,2025
2,5.950000e+11,Outbound,BP5009,2025-01-24,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,2025-06-09,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
4,5.370000e+11,Outbound,ZL7978,2024-08-20,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,Outbound,EE2165,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186530,5.050000e+11,Outbound,IT3598,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186531,5.050000e+11,Outbound,ZD8460,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186532,5.050000e+11,Outbound,PX0289,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186533,5.050000e+11,Outbound,IL3891,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024

## Standardize Call Direction Values

Standardize call_direction values to consistent 'OUT_BOUND' and 'IN_BOUND' format.

In [24]:
df['call_direction'] = df['call_direction'].replace({
    'Outbound': 'OUT_BOUND',
    'Inbound': 'IN_BOUND'
})
df['call_direction'].value_counts()

call_direction
OUT_BOUND    131468
IN_BOUND      21801
Name: count, dtype: int64

## Data After Call Direction Standardization

Display the dataframe after standardizing call_direction values.

In [25]:
df

,call_id,call_direction,co_ref,call_date,churn_category,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,justification_category,reason_for_renewal_category,agent_response_to_cancel_category,argument_that_convinced_customer_to_stay_category,analysed_call,call_number,call_year
0,5.950000e+11,OUT_BOUND,UB0899,2025-01-29,NaN,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,3,2025
1,5.970000e+11,OUT_BOUND,HN5141,2025-02-26,NaN,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,2,2025
2,5.950000e+11,OUT_BOUND,BP5009,2025-01-24,NaN,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
3,6.520000e+11,OUT_BOUND,XP8119,2025-06-09,NaN,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Offering,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,1,2025
4,5.370000e+11,OUT_BOUND,ZL7978,2024-08-20,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,NaN,NaN,NaN,NaN,1,28,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,OUT_BOUND,EE2165,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186530,5.050000e+11,OUT_BOUND,IT3598,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186531,5.050000e+11,OUT_BOUND,ZD8460,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186532,5.050000e+11,OUT_BOUND,PX0289,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024
186533,5.050000e+11,OUT_BOUND,IL3891,2024-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,2024

## Check Missing Values After Standardization

Check for missing values after standardizing call_direction values.

In [26]:
df.isnull().sum()

call_id                                                   0
call_direction                                            0
co_ref                                                    0
call_date                                                 0
churn_category                                       145595
complaint_category                                   135320
customer_reaction_category                           131194
agent_renewal_pitch_category                         101259
customer_renewal_response_category                   100765
agent_response_category                              101088
membership_renewal_decision                           70634
serious_complaint                                     72837
other_complaint                                       72838
discussion_on_price_increase                          69252
renewal_impact_due_to_price_increase                  69278
discount_or_waiver_requested                          69278
call_reschedule_request                               68751
agent_flagged_membership_status_alert                 68751
agent_renewal_initiation                              68751
explicit_competitor_mention                           68633
explicit_switching_intent                             68633
mentioned_competitors                                 68631
price_switching_mentioned                             68673
competitor_value_comparison                           68670
competitor_benefits_mentioned                         70682
topic_introduced_by                                   68617
percentage_price_increase_mentioned                   68617
monetary_price_increase_mentioned                     68617
price_range_mentioned                                 68617
customer_asked_for_justification                      68617
customer_response                                     68617
desire_to_cancel                                      68620
discount_offered                                      68617
justification_category                               140689
reason_for_renewal_category                          137794
agent_response_to_cancel_category                    148465
argument_that_convinced_customer_to_stay_category    151524
analysed_call                                         68594
call_number                                               0
call_year                                                 0
dtype: int64

## Check Unique Values per Column

Count the number of unique values in each column.

In [27]:
df.nunique()

call_id                                                 53
call_direction                                           2
co_ref                                               36303
call_date                                              467
churn_category                                          18
complaint_category                                      22
customer_reaction_category                              13
agent_renewal_pitch_category                            18
customer_renewal_response_category                      20
agent_response_category                                 20
membership_renewal_decision                              3
serious_complaint                                        3
other_complaint                                          4
discussion_on_price_increase                             4
renewal_impact_due_to_price_increase                    20
discount_or_waiver_requested                            31
call_reschedule_request                                  3
agent_flagged_membership_status_alert                    3
agent_renewal_initiation                                 3
explicit_competitor_mention                              6
explicit_switching_intent                                8
mentioned_competitors                                   11
price_switching_mentioned                                6
competitor_value_comparison                             81
competitor_benefits_mentioned                          347
topic_introduced_by                                      3
percentage_price_increase_mentioned                      3
monetary_price_increase_mentioned                        3
price_range_mentioned                                 3002
customer_asked_for_justification                         3
customer_response                                        4
desire_to_cancel                                       467
discount_offered                                         3
justification_category                                  30
reason_for_renewal_category                             23
agent_response_to_cancel_category                       22
argument_that_convinced_customer_to_stay_category       17
analysed_call                                            1
call_number                                            181
call_year                                                3
dtype: int64

## Detailed Value Counts for Each Column

Display value counts for each column, including null values, to understand data distribution.

In [28]:
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].value_counts(dropna=False))
    print("-" * 40)

Column: call_id
call_id
5.110000e+11    5456
5.090000e+11    5177
5.070000e+11    4689
5.950000e+11    4518
5.080000e+11    4514
5.380000e+11    4404
5.100000e+11    4178
5.120000e+11    4152
5.940000e+11    4077
5.130000e+11    4070
5.960000e+11    3977
5.920000e+11    3892
5.650000e+11    3884
6.230000e+11    3755
5.390000e+11    3737
6.220000e+11    3724
5.060000e+11    3720
5.910000e+11    3694
6.790000e+11    3276
5.970000e+11    3258
6.260000e+11    3199
6.820000e+11    3121
5.900000e+11    3096
6.250000e+11    3066
6.510000e+11    2979
6.770000e+11    2903
6.850000e+11    2885
6.860000e+11    2777
6.830000e+11    2766
6.940000e+11    2717
6.880000e+11    2710
6.800000e+11    2549
6.870000e+11    2548
6.900000e+11    2503
6.810000e+11    2395
6.240000e+11    2392
6.890000e+11    2370
6.920000e+11    2355
6.840000e+11    2353
6.930000e+11    2321
5.400000e+11    2301
6.780000e+11    2178
5.930000e+11    2155
6.520000e+11    1841
5.640000e+11    1822
5.050000e+11    1770
6.950000e+11    1171
5.370000e+11     919
6.910000e+11     769
5.660000e+11     720
6.760000e+11     663
1.940000e+11     433
1.930000e+11     370
Name: count, dtype: int64
----------------------------------------
Column: call_direction
call_direction
OUT_BOUND    131468
IN_BOUND      21801
Name: count, dtype: int64
----------------------------------------
Column: co_ref
co_ref
AD1657    161
UW3387    108
ZF9958     77
XG1277     77
YT5805     67
         ...
XJ3440      1
BG6702      1
VK2854      1
ND8398      1
ED6707      1
Name: count, Length: 36303, dtype: int64
----------------------------------------
Column: call_date
call_date
2025-01-13    536
2025-01-15    518
2024-04-15    508
2024-06-03    503
2024-04-22    498
             ...
2025-03-25     98
2025-07-10     95
2025-12-24     13
2026-01-17      9
2026-01-11      6
Name: count, Length: 467, dtype: int64
----------------------------------------
Column: churn_category
churn_category
NaN                                        145595
Unnecessary / Not needed                     1645
Cost / Price / Too expensive                 1493
Financial struggles / Business Problems       910
Left / Not with client anymore                778
Not Mentioned                                 575
Lack of Benefits                              514
Accreditation / Certification                 329
Switch / Change / Alternate Provider          276
Customer Service / Support                    228
Payment / Invoice Issue                       206
Client Requirement                            190
Process Issues                                146
Account Information                           112
Others                                         87
Auto / Automatic                               68
Value of service                               67
Portal / Technical Issues                      26
Audit                                          24
Name: count, dtype: int64
----------------------------------------
Column: complaint_category
complaint_category
NaN                                135320
Price Increase / Rise and Value      3205
Payment Issues                       2772
Accreditation and Certification      2731
Process and Auto-Renewal Issues      1820
Customer Service                     1274
Billings and Invoices                1160
Portal and Technical Issues          1138
Quality and Satisfaction              643
Cancellation and Refunds              641
Account Information                   567
Audit                                 389
Package and Benefits                  310
Financial Hardship                    296
Login and Access                      255
Discounts                             187
Assessment                            180
Sales and Marketing                   132
Others                                 64
Compliance                             61
Insurance                              56
Privacy and Security                   48
Not Mentioned                          20
Name: count, dtype: int64
----------------------------------------
Column: customer_reaction_category
customer_reaction_category
NaN                                                    131194
Not Mentioned                                           10278
Agreement / Acceptance / Acknowledgement                 3365
Dissatisfaction / Concern / Complaint / Frustration      2998
Clarification / Justification / Inquiry                  2820
Hesitation                                                579
Discount / Offer                                          486
Negotiation                                               418
Financial Hardship / Struggle                             392
Cancellation                                              308
Customer Retention                                        283
Value                                                      74
Payment / Billing                                          49
Other                                                      25
Name: count, dtype: int64
----------------------------------------
Column: agent_renewal_pitch_category
agent_renewal_pitch_category
NaN                                                   101259
Expiration / Due                                       13041
Auto / Automatic                                       11386
Payment and Billings / Invoice                          7019
Annual                                                  6069
Discussion / Introduction / Inquiry                     4356
Accreditation and Certification                         3471
Cancellation / Termination / Non-Renewal / Closure      2748
Price and Cost                                          1080
Discounts and Offers                                     994
Not Mentioned                                            782
Assessment                                               326
Audit                                                    251
Issues and Problems                                      175
Benefits                                                 154
Packages and Schemes                                      94
Customer Service / Support                                40
Insurance                                                 18
Others                                                     6
Name: count, dtype: int64
----------------------------------------
Column: customer_renewal_response_category
customer_renewal_response_category
NaN                                                      100765
Agreement                                                 10255
Payments and Billings / Invoice                            7916
Communication                                              7679
Confusion / Uncertainty / Hesitation                       6178
Price and Cost                                             3229
Accreditation and Certification                            3166
Cancellation / Termination / Non-Renewal / Withdrawal      3017
Not Mentioned                                              2977
Auto / Automatic                                           2624
Financial Hardship / Struggles                             1533
Quality / Value / Satisfaction of service                  1110
Discount and Offer                                          685
Assessment                                                  521
Package                                                     348
Technical                                                   331
Benefits                                                    315
Audit                                                       228
Others                                                      195
Refund                                                      101
Insurance                                                    96
Name: count, dtype: int64
----------------------------------------
Column: agent_response_category
agent_response_category
NaN                                      101088
Payment                                    9855
Customer Communication                     9432
Confirmation / Acceptance / Agreement      6683
Customer Service / Support                 4162
Customer Retention                         3644
Cancellation / Termination / Closure       3549
Accreditation and Certification            3094
Account information                        2716
Discount and Offer                         2395
Auto / Automatic                           2199
Price and Cost                             1423
Audit                                       966
Not Mentioned                               712
Assessment                                  385
Technical                                   352
Benefits and Package                        217
Refund                                      185
Complaints                                   95
Insurance                                    68
Others                                       49
Name: count, dtype: int64
----------------------------------------
Column: membership_renewal_decision
membership_renewal_decision
No        73884
NaN       70634
Yes        8738
Yes/No       13
Name: count, dtype: int64
----------------------------------------
Column: serious_complaint
serious_complaint
No        79842
NaN       72837
Yes         589
Yes/No        1
Name: count, dtype: int64
----------------------------------------
Column: other_complaint
other_complaint
NaN               72838
No                61459
Yes               18970
Not Applicable        1
Yes/No                1
Name: count, dtype: int64
----------------------------------------
Column: discussion_on_price_increase
discussion_on_price_increase
No          75911
NaN         69252
Yes          8079
[Yes/No]       26
**No**          1
Name: count, dtype: int64
----------------------------------------
Column: renewal_impact_due_to_price_increase
renewal_impact_due_to_price_increase
No                                                                                                                                                                                        79877
NaN                                                                                                                                                                                       69278
Yes                                                                                                                                                                                        4062
[Yes/No]                                                                                                                                                                                     26
Not applicable                                                                                                                                                                               10
Yes (The customer had already initiated the cancellation of their membership)                                                                                                                 1
Yes (The customer's account is being cancelled, but it's not explicitly stated that it's due to a price increase, however, the context implies that the customer is not renewing)             1
Yes (The customer mentioned they are not going to go ahead with the membership at the moment, which can be inferred as not renewing)                                                          1
Yes (the customer is calling to inquire about not renewing their membership)                                                                                                                  1
Yes (the customer mentioned they might have to close the membership due to budget constraints, but it was not directly related to a price increase)                                           1
Yes (due to other reasons, not price increase)                                                                                                                                                1
Yes (the customer mentioned that if they can't offer any reduction in price, they'd be looking elsewhere)                                                                                     1
Yes, the customer decided not to renew their membership due to financial difficulties, not a price increase.                                                                                  1
Yes, the customer is considering not renewing due to lack of perceived value, not specifically because of a price increase.                                                                   1
Yes (The customer mentioned that they don't think they're going to be continuing with the membership and later stated that they would rather just cancel it.)                                 1
Yes, the customer mentioned that they are not renewing this year, but it was not explicitly stated that this decision was due to a price increase, as no price increase was mentioned.        1
Yes, the customer implied they would not renew their membership due to the organization's handling of their situation.                                                                        1
Yes (the customer mentioned that they cannot afford to pay £500 for the service and decided not to renew their membership)                                                                    1
Yes (the customer mentioned they were questioning whether to sign up again because they only have one person who requires it)                                                                 1
Yes (the customer mentioned that they cannot renew due to financial reasons)                                                                                                                  1
**No**                                                                                                                                                                                        1
Name: count, dtype: int64
----------------------------------------
Column: discount_or_waiver_requested
discount_or_waiver_requested
No                                                                                                                                                                           81242
NaN                                                                                                                                                                          69278
Yes                                                                                                                                                                           2685
[Yes/No]                                                                                                                                                                        26
Not applicable                                                                                                                                                                  11
Yes (The customer is seeking a discount.)                                                                                                                                        1
Yes, the customer mentioned trying to use a discount code for the renewal.                                                                                                       1
No (the agent offered a discount, but the customer did not ask for one)                                                                                                          1
Yes (the customer asked about the cost of downgrading their package and the potential cost savings)                                                                              1
No (although a discount was offered)                                                                                                                                             1
Yes, the customer asked for an additional discount to help with the payment.                                                                                                     1
No (but the agent offered a discount)                                                                                                                                            1
No, the agent offered the discount.                                                                                                                                              1
Yes (Customer inquired about reducing the bill and had a previously applied discount re-applied)                                                                                 1
The customer was not asking for a discount on a price increase, but was instead confirming and proceeding with a previously negotiated price from last year's discussion.        1
Yes (the agent offers a discount to the customer)                                                                                                                                1
No, the customer did not ask for a discount or waiver on a price increase.                                                                                                       1
Yes (the customer implies that they are looking for a better price and the agent offers a discount)                                                                              1
Yes, the agent offered a discounted rate.                                                                                                                                        1
No, but the agent offered a goodwill discount.                                                                                                                                   1
No, but the agent offered a same-day discount of £100 after the customer expressed difficulty with the price.                                                                    1
Yes, the customer did not directly ask for a discount, but the agent offered a £50 discount as a compromise.                                                                     1
No (the customer did not ask for a discount or waiver to the price increase, but the agent offered a £380 saving on the original price)                                          1
Yes (the agent offers a discounted price as a goodwill gesture)                                                                                                                  1
No (The customer did not explicitly ask for a discount or waiver on a price increase, but the agent proactively offered a concession.)                                           1
No (the customer did not ask for a discount or waiver to the price increase)                                                                                                     1
No (replaced with a reasonable inference) The customer had previously discussed a potential discount with Chloe, but it was not mentioned as a current request.                  1
**No**                                                                                                                                                                           1
Yes (the customer asked if the price was the best they could do, implying a request for a discount or waiver)                                                                    1
Yes (the customer asked for a reduction on the bill)                                                                                                                             1
No (the customer did not ask for a discount or waiver to a price increase, but the agent offered a discount)                                                                     1
Yes, the agent offered a discount to the customer, and the customer asked the agent to send the offer via email so they could discuss it with their MD.                          1
Name: count, dtype: int64
----------------------------------------
Column: call_reschedule_request
call_reschedule_request
No                81968
NaN               68751
Yes                2547
Not Applicable        3
Name: count, dtype: int64

## Identify Columns with High Null Percentage

Identify columns with more than 80% null values that may need to be removed.

In [29]:
null_percentages = df.isnull().mean()
cols_to_drop_candidates = null_percentages[null_percentages > 0.80].index.tolist()
print('Columns with >80% null fraction:')
print(cols_to_drop_candidates)

Columns with >80% null fraction:
['churn_category', 'complaint_category', 'customer_reaction_category', 'justification_category', 'reason_for_renewal_category', 'agent_response_to_cancel_category', 'argument_that_convinced_customer_to_stay_category']

## Drop High-Null and Complex Columns

Remove columns with high null percentages and complex categorical columns that may not be useful for modeling.

In [30]:
# Drop the specific high-null / high-complexity columns identified from the dataset
cols_to_drop_candidates = [col for col in cols_to_drop_candidates if col in df.columns]
df.drop(columns=cols_to_drop_candidates, inplace=True)

complex_columns_to_drop = [
    'agent_renewal_pitch_category',
    'customer_renewal_response_category',
    'agent_response_category',
    'analysed_call',
    'call_year',
]
complex_columns_to_drop = [col for col in complex_columns_to_drop if col in df.columns]
df.drop(columns=complex_columns_to_drop, inplace=True)

## Data Shape After Column Removal

Check the dimensions of the dataframe after removing high-null and complex columns.

In [31]:
df.shape

(153269, 28)

## Standardize Categorical Column Values

Standardize values in categorical columns to consistent formats like Yes/No/Not Discussed/Unknown.

In [32]:
for col in ['percentage_price_increase_mentioned','monetary_price_increase_mentioned','customer_asked_for_justification','discount_offered']:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )
    df[col] = df[col].apply(
        lambda x: "Yes" if str(x).strip().lower() == "yes"
        else ("No" if str(x).strip().lower() == "no"
        else ("Not Discussed" if "not discussed" in str(x).strip().lower()
        else "Unknown"))
    )
    print(df[col].value_counts(dropna=False))

for col in ['membership_renewal_decision','serious_complaint','other_complaint','discussion_on_price_increase','renewal_impact_due_to_price_increase','discount_or_waiver_requested','call_reschedule_request','agent_flagged_membership_status_alert','agent_renewal_initiation','explicit_competitor_mention','explicit_switching_intent','mentioned_competitors','price_switching_mentioned']:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )
    df[col] = df[col].apply(lambda x: "Yes" if x == "yes" else ("No" if x == "no" else "Unknown"))
    print(df[col].value_counts(dropna=False))

df['competitor_value_comparison'] = df['competitor_value_comparison'].apply(
    lambda x: "Not Discussed" if  "not discussed" in str(x).strip().lower()
    else ("Similar Value" if str(x).strip().lower() == "similar value"
    else ("Better Value" if str(x).strip().lower() == "better value"
    else ("Not Applicable" if "not applicable" in str(x).strip().lower()
    else "Unknown")))
)
print(df['competitor_value_comparison'].value_counts(dropna=False))

df['competitor_benefits_mentioned'] = df['competitor_benefits_mentioned'].apply(
    lambda x: "Not Discussed" if "not discussed" in str(x).strip().lower()
    else ("Discounts" if "discount" in str(x).strip().lower()
    else ("Better Service" if "better service" in str(x).strip().lower()
    else ("Not Applicable" if "not applicable" in str(x).strip().lower()
    else "Unknown")))
)
print(df['competitor_benefits_mentioned'].value_counts(dropna=False))

df['topic_introduced_by'] = df['topic_introduced_by'].apply(
    lambda x: "Not Discussed" if "not discussed" in str(x).strip().lower()
    else ("Agent" if str(x).strip().lower() == "agent"
    else ("Customer" if str(x).strip().lower() == "customer"
    else "Unknown"))
)
print(df['topic_introduced_by'].value_counts(dropna=False))

def process_price_range(x):
    # Handle NaN and Not Discussed
    if "not discussed" in str(x).lower():
        return "Not Discussed"
    
    # Extract numbers
    numbers = re.findall(r'\d+\.?\d*', str(x))
    
    if len(numbers) >= 2:
        nums = list(map(float, numbers[:2]))
        return sum(nums) / 2
    
    return "Unknown"
df['price_range_mentioned'] = df['price_range_mentioned'].apply(process_price_range)

df['customer_response'] = df['customer_response'].apply(
    lambda x: "Not Discussed" if "not discussed" in str(x).strip().lower()
    else ("Positive" if str(x).strip().lower() == "positive"
    else ("Negative" if str(x).strip().lower() == "negative"
    else ("Neutral" if str(x).strip().lower() == "neutral"
    else "Unknown")))
)
print(df['customer_response'].value_counts(dropna=False))

df['desire_to_cancel'] = df['desire_to_cancel'].apply(
    lambda x: "Not Discussed" if "not discussed" in str(x).strip().lower()
    else ("Renewed" if "renew" in str(x).strip().lower()
    else ("Desired to Cancel" if "cancel" in str(x).strip().lower()
    else "Unknown"))
)
print(df['desire_to_cancel'].value_counts(dropna=False))

percentage_price_increase_mentioned
No               83435
Unknown          68617
Yes                657
Not Discussed      560
Name: count, dtype: int64
monetary_price_increase_mentioned
No               81204
Unknown          68617
Yes               2888
Not Discussed      560
Name: count, dtype: int64
customer_asked_for_justification
No               78474
Unknown          68617
Yes               5617
Not Discussed      561
Name: count, dtype: int64
discount_offered
No               77518
Unknown          68617
Yes               6573
Not Discussed      561
Name: count, dtype: int64
membership_renewal_decision
No         73884
Unknown    70647
Yes         8738
Name: count, dtype: int64
serious_complaint
No         79842
Unknown    72838
Yes          589
Name: count, dtype: int64
other_complaint
Unknown    72840
No         61459
Yes        18970
Name: count, dtype: int64
discussion_on_price_increase
No         75911
Unknown    69279
Yes         8079
Name: count, dtype: int64
renewal_impact_due_to_price_increase
No         79877
Unknown    69330
Yes         4062
Name: count, dtype: int64
discount_or_waiver_requested
No         81242
Unknown    69342
Yes         2685
Name: count, dtype: int64
call_reschedule_request
No         81968
Unknown    68754
Yes         2547
Name: count, dtype: int64
agent_flagged_membership_status_alert
Unknown    68754
No         58467
Yes        26048
Name: count, dtype: int64
agent_renewal_initiation
Unknown    68754
No         43135
Yes        41380
Name: count, dtype: int64
explicit_competitor_mention
No         83214
Unknown    68662
Yes         1393
Name: count, dtype: int64
explicit_switching_intent
No         84540
Unknown    68665
Yes           64
Name: count, dtype: int64
mentioned_competitors
No         77844
Unknown    68666
Yes         6759
Name: count, dtype: int64
price_switching_mentioned
No         81537
Unknown    68692
Yes         3040
Name: count, dtype: int64
competitor_value_comparison
Not Applicable    79784
Unknown           68707
Not Discussed      2738
Better Value       1405
Similar Value       635
Name: count, dtype: int64
competitor_benefits_mentioned
Unknown           72244
Not Applicable    61168
Not Discussed     15176
Discounts          2562
Better Service     2119
Name: count, dtype: int64
topic_introduced_by
Unknown          68617
Not Discussed    62902
Agent            16403
Customer          5347
Name: count, dtype: int64
customer_response
Unknown          68617
Neutral          55968
Not Discussed    22315
Negative          5652
Positive           717
Name: count, dtype: int64
desire_to_cancel
Unknown              68678
Renewed              39643
Not Discussed        34275
Desired to Cancel    10673
Name: count, dtype: int64

## Check Desire to Cancel Distribution

Display the distribution of desire_to_cancel values after standardization.

In [33]:
(df['desire_to_cancel'].value_counts(dropna=False))

desire_to_cancel
Unknown              68678
Renewed              39643
Not Discussed        34275
Desired to Cancel    10673
Name: count, dtype: int64

## Check Missing Values After Standardization

Check for missing values after standardizing categorical column values.

In [34]:
df.isnull().sum()

call_id                                  0
call_direction                           0
co_ref                                   0
call_date                                0
membership_renewal_decision              0
serious_complaint                        0
other_complaint                          0
discussion_on_price_increase             0
renewal_impact_due_to_price_increase     0
discount_or_waiver_requested             0
call_reschedule_request                  0
agent_flagged_membership_status_alert    0
agent_renewal_initiation                 0
explicit_competitor_mention              0
explicit_switching_intent                0
mentioned_competitors                    0
price_switching_mentioned                0
competitor_value_comparison              0
competitor_benefits_mentioned            0
topic_introduced_by                      0
percentage_price_increase_mentioned      0
monetary_price_increase_mentioned        0
price_range_mentioned                    0
customer_asked_for_justification         0
customer_response                        0
desire_to_cancel                         0
discount_offered                         0
call_number                              0
dtype: int64

## Data Shape After Standardization

Check the dimensions of the dataframe after standardizing categorical values.

In [35]:
df.shape

(153269, 28)

## Final Cleaned Data

Display the final cleaned and processed dataframe.

In [36]:
df

,call_id,call_direction,co_ref,call_date,membership_renewal_decision,serious_complaint,other_complaint,discussion_on_price_increase,renewal_impact_due_to_price_increase,discount_or_waiver_requested,call_reschedule_request,agent_flagged_membership_status_alert,agent_renewal_initiation,explicit_competitor_mention,explicit_switching_intent,mentioned_competitors,price_switching_mentioned,competitor_value_comparison,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,call_number
0,5.950000e+11,OUT_BOUND,UB0899,2025-01-29,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,3
1,5.970000e+11,OUT_BOUND,HN5141,2025-02-26,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Unknown,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,2
2,5.950000e+11,OUT_BOUND,BP5009,2025-01-24,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,Not Applicable,Better Service,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,1
3,6.520000e+11,OUT_BOUND,XP8119,2025-06-09,No,No,No,No,No,No,No,No,Yes,No,No,No,No,Not Applicable,Unknown,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,1
4,5.370000e+11,OUT_BOUND,ZL7978,2024-08-20,No,No,No,No,No,No,No,No,No,No,No,No,No,Not Applicable,Discounts,Not Discussed,No,No,Not Discussed,No,Not Discussed,Not Discussed,No,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186529,5.050000e+11,OUT_BOUND,EE2165,2024-04-02,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,1
186530,5.050000e+11,OUT_BOUND,IT3598,2024-04-02,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,1
186531,5.050000e+11,OUT_BOUND,ZD8460,2024-04-02,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,1
186532,5.050000e+11,OUT_BOUND,PX0289,2024-04-02,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,1
186533,5.050000e+11,OUT_BOUND,IL3891,2024-04-02,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,1

## Save Cleaned Data

Save the cleaned renewal calls data to the interim data directory as CSV.

In [37]:
df.to_csv('../../data/interim/renewal_calls_cleaned.csv', index=False)